/**
 * T1561b — THE TUNNEL'S CENTRELINE, as a function of distance travelled.
 *
 * The tunnel is endless, so its path cannot be data: it is a function, a few sines of `z`
 * (metres along the tunnel) for the sideways and vertical wander. Three readers need the
 * same line and none may hold a copy that can drift from the others: the robots' joints and
 * the tunnel's own geometry (WGSL, on the GPU), and the camera (an expression, on the CPU).
 * So the line is written ONCE, below, and emitted in each reader's language.
 *
 * It is PERIODIC, on purpose: every term completes a whole number of cycles in `period`
 * metres, so the travel distance wraps there and nothing shows. That keeps `z` small — at
 * 100 km a 32-bit float resolves 8 mm and every joint would shimmer; at 960 m it resolves
 * 0.06 mm.
 */

export interface PathTerm {
  /** Metres. */
  readonly amplitude: number;
  /** Whole cycles per period, so the path closes on itself. */
  readonly cycles: number;
  /** Radians. */
  readonly phase: number;
}

export interface PathSpec {
  /** Metres after which the tunnel repeats exactly. */
  readonly period: number;
  readonly x: readonly PathTerm[];
  readonly y: readonly PathTerm[];
}

/** Long lazy sweeps with a tighter bend riding on them: the tightest radius is about 30 m. */
export const PATH: PathSpec = {
  period: 960,
  x: [
    { amplitude: 14, cycles: 5, phase: 0.4 },
    { amplitude: 5, cycles: 13, phase: 1.9 },
  ],
  y: [
    { amplitude: 6, cycles: 4, phase: 2.2 },
    { amplitude: 2.5, cycles: 11, phase: 0.7 },
  ],
};

const wave = (term: PathTerm, period: number): number => (2 * Math.PI * term.cycles) / period;
const f = (value: number): string => (Number.isInteger(value) ? value.toFixed(1) : String(Number(value.toPrecision(9))));

/** The line itself, in float64: what a test compares the two emitted forms against. */
export function pathAt(z: number, path: PathSpec = PATH): [number, number, number] {
  const sum = (terms: readonly PathTerm[]): number => terms.reduce((total, term) => total + term.amplitude * Math.sin(wave(term, path.period) * z + term.phase), 0);
  return [sum(path.x), sum(path.y), z];
}

/** The same line as two expression strings of `z` (itself an expression), for the camera. */
export function pathExpression(z: string, path: PathSpec = PATH): { readonly x: string; readonly y: string } {
  const sum = (terms: readonly PathTerm[]): string => `(${terms.map((term) => `${f(term.amplitude)} * sin(${f(wave(term, path.period))} * (${z}) + ${f(term.phase)})`).join(" + ")})`;
  return { x: sum(path.x), y: sum(path.y) };
}

/**
 * The same line as WGSL: `pathAt(z)`, its unit tangent, and the frame a thing in the tunnel
 * stands in — `right`, `up`, `forward`, right-handed with right = up × forward, which is the
 * kit's robot frame (tools/blender/sentinel-bot/README.md).
 */
export function pathWgsl(path: PathSpec = PATH): string {
  const position = (terms: readonly PathTerm[]): string => terms.map((term) => `${f(term.amplitude)} * sin(${f(wave(term, path.period))} * z + ${f(term.phase)})`).join(" + ");
  const slope = (terms: readonly PathTerm[]): string => terms.map((term) => `${f(term.amplitude * wave(term, path.period))} * cos(${f(wave(term, path.period))} * z + ${f(term.phase)})`).join(" + ");
  return `// T1561b — the tunnel's centreline (generated by src/projects/sentinel-bot/path.ts).
const PATH_PERIOD: f32 = ${f(path.period)};

fn pathAt(z: f32) -> vec3f {
  return vec3f(${position(path.x)}, ${position(path.y)}, z);
}

fn pathTangent(z: f32) -> vec3f {
  return normalize(vec3f(${slope(path.x)}, ${slope(path.y)}, 1.0));
}

struct Frame {
  origin: vec3f,
  right: vec3f,
  up: vec3f,
  forward: vec3f,
};

fn pathFrame(z: f32) -> Frame {
  var frame: Frame;
  frame.origin = pathAt(z);
  frame.forward = pathTangent(z);
  frame.right = normalize(cross(vec3f(0.0, 1.0, 0.0), frame.forward));
  frame.up = cross(frame.forward, frame.right);
  return frame;
}
`;
}
