/**
 * T1641b — WHY EACH DIAGNOSTIC CODE IS OF ITS CLASS, in a few words.
 *
 * The reading behind `DIAGNOSTIC_CLASSES` (`classes.ts`), one line a code. It is a file of
 * its own because it is PROSE FOR A READER OF THE TABLE and nothing in the product shows it:
 * the compiler asks `leavesPlanUsable`, the save and the headless harness ask
 * `diagnosticClass`, and none of them reads a reason. Beside the classes it was 47 % of that
 * module and half of what the app shipped of it (59.9 KB minified, 10.5 KB gzip; without it
 * 27.8 KB and 5.1 KB), so the app imports the classes and this stays out of the bundle.
 *
 * `classes.test.ts` holds the two to each other in both directions: every row of the class
 * table has its reason here, and every reason names a row. A new code writes both in the
 * diff that adds it. Nothing under `src/` but that gate imports this file; if a surface ever
 * shows a reason to a person, it imports it then, and the split has done its work.
 */
export const DIAGNOSTIC_CLASS_REASONS: Readonly<Record<string, string>> = {
  "animation/structuralDrift": "a frame's plan differs in structure from the installed one",
  "asset.badData": "the attach_asset tool's input",
  "asset.parameterUnresolved": "the attach_asset tool's input",
  "asset.reference.error": "a retained file this session could not open",
  "asset.reference.invalid": "a file reference that does not read",
  "asset.reference.missing": "a retained file this browser no longer holds",
  "asset.reference.pending": "a retained file still opening",
  "asset.reference.permission": "a retained file this session may not read yet",
  "audio.noSession": "recording or reading an audio feature track",
  "audio.noSource": "recording or reading an audio feature track",
  "audio.nothingRecorded": "recording or reading an audio feature track",
  "audio.track.fps": "recording or reading an audio feature track",
  "audio.track.frames": "recording or reading an audio feature track",
  "audio.track.malformed": "recording or reading an audio feature track",
  "audio.track.provenance": "recording or reading an audio feature track",
  "audio.track.version": "recording or reading an audio feature track",
  "audio.trackWriteFailed": "recording or reading an audio feature track",
  "backend/capability-below-baseline": "the device's state",
  "backend/compile-failed": "a stored shader the device refuses",
  "backend/device-lost": "the device's state",
  "backend/device-restored": "the device's state",
  "backend/frame-error": "the plan and the device disagree",
  "backend/init-failed": "the device's state",
  "backend/not-initialized": "the device's state",
  "backend/plan-invalid": "the plan and the device disagree",
  "backend/plan-not-current": "the plan and the device disagree",
  "backend/present-failed": "the device's state",
  "backend/rebuild-failed": "the plan and the device disagree",
  "backend/recover-failed": "the plan and the device disagree",
  "backend/resource-limit": "the device's state",
  "backend/shader-validation-unavailable": "the device's state",
  "backend/submission-halted": "the plan and the device disagree",
  "backend/temporal-reset": "the device's state",
  "backend/timestamp-unavailable": "the device's state",
  "backend/unknown-output": "the plan and the device disagree",
  "backend/unknown-pass": "the plan and the device disagree",
  "backend/unknown-resource": "the plan and the device disagree",
  "bridge/detached": "the MCP bridge's connection",
  "bridge/devices-only": "the MCP bridge's connection",
  "bridge/not-the-owner": "the MCP bridge's connection",
  "bridge/page-error": "the MCP bridge's connection",
  "bridge/proxy-lost": "the MCP bridge's connection",
  "bridge/timeout": "the MCP bridge's connection",
  "capability.denied": "a capability the caller does not hold",
  "capability.unobtainable": "a capability the caller does not hold",
  "channel.reference.unnamed": "a copy of a reference to a node with no name",
  "clipboard.empty": "what the clipboard holds",
  "clipboard.foreign": "what the clipboard holds",
  "command.failed": "the command's input, or its handler threw",
  "command.input": "the command's input, or its handler threw",
  "compile.noCompiler": "no compiler or device to compile with here",
  "compile.noDevice": "no compiler or device to compile with here",
  "compiler.crashed": "the compiler threw",
  "compiler/binding-budget": "a pass binds more than this device allows",
  "compiler/binding-unfilterable": "this device cannot filter the format a pass samples",
  "compiler/bypass-incoherent": "a bypass with no input to pass through: muted instead",
  "compiler/camera-preview-ambiguous": "a camera shared by renderers previews the stock scene",
  "compiler/color-space-mismatch": "it renders as wired: the compiler never converts",
  "compiler/component-id-collision": "two nodes flatten to one id: the second is dropped",
  "compiler/component-missing": "an instance of a component that is not installed",
  "compiler/component-parameter-conflict": "a parent read that cannot resolve, or one a published value shadows",
  "compiler/component-port-unresolved": "an edge onto a port the component does not expose",
  "compiler/component-recursion": "a component that contains itself",
  "compiler/cycle": "a same-frame loop with no temporal node in it",
  "compiler/definition-version": "a node saved against another version of its definition",
  "compiler/edge-endpoint-missing": "an edge whose endpoint is not in the document, or is of an unknown type",
  "compiler/format-depth-on-color": "a depth format on a colour output can never apply",
  "compiler/format-input-missing": "the working format stands in for an unwired input's",
  "compiler/format-no-fallback": "this device lacks the format and nothing can stand in",
  "compiler/format-unsupported": "this device lacks the format: a named one stands in",
  "compiler/input-missing": "a required input not wired yet",
  "compiler/memory-budget": "over the project's own budget: reported, not enforced",
  "compiler/no-active-sinks": "nothing reaches an output yet",
  "compiler/node-compile-failed": "a node definition's compile threw",
  "compiler/node-no-passes": "a node definition emitted no passes",
  "compiler/pass-invalid": "a node definition emitted a malformed pass",
  "compiler/passthrough-unconnected": "a Null chain that reaches no producer yet",
  "compiler/port-incompatible": "two port types with no conversion between them",
  "compiler/port-missing": "an edge on a port the type does not declare",
  "compiler/port-occupied": "a second wire into a single input is ignored",
  "compiler/parent-reference-no-parent": "a parent() read with no component around the node to reach",
  "compiler/parent-reference-unknown-key": "a parent() read of a key the component does not publish",
  "compiler/reference-cross-scope": "a bare name that reaches into an instance binds as stored; a path says which copy",
  "compiler/resolution-clamped": "scaled down to the limit in force",
  "compiler/resolution-custom": "the project resolution stands in for a custom policy",
  "compiler/resolution-input-missing": "the project resolution stands in for an unwired input's",
  "compiler/resolution-parameter": "the project resolution stands in for a parameter that gives none",
  "compiler/scratch-invalid": "a node definition declared malformed scratch",
  "compiler/sink-unknown": "the request's sink, not the document's",
  "compiler/source-reference-ambiguous": "a name and a wire on one input: one is never read",
  "compiler/source-reference-missing": "a named source that no node holds, or that can never fit the input",
  "compiler/substeps-refused": "it runs one step, or a capped count, and says so",
  "compiler/unknown-node-type": "a node type this build does not have",
  "compiler/wgsl-high-half-divide": "valid WGSL that Apple GPUs compute wrongly: nothing is refused",
  "component.channelMaskTargetMissing": "a mask override path naming no internal node",
  "component.create.noCanvas": "a component gesture with nothing to act on",
  "component.create.noSelection": "a component gesture with nothing to act on",
  "component.detach.channelMask": "the copies draw every channel",
  "component.detach.inexact": "a value the copies could not carry exactly",
  "component.detach.instancePaths": "the detach left override paths that name nothing",
  "component.detach.nestedParentReads": "a nested parent read now names one component further out",
  "component.detach.outerTarget": "a published key no longer drives the copies",
  "component.detach.overrideMissing": "an override for an internal node the definition lacks",
  "component.detach.pageBank": "the page bank was rewritten for the copies",
  "component.detach.pageBankInert": "the detach left a root bank targeting parent",
  "component.detach.parentValues": "the copies hold the values their parent reads gave",
  "component.export.failed": "the component file being exported or imported",
  "component.export.input": "the component file being exported or imported",
  "component.export.missingDependency": "the component file being exported or imported",
  "component.export.noWriter": "the component file being exported or imported",
  "component.export.sessionAsset": "the component file being exported or imported",
  "component.id": "a component id the registry will not hold",
  "component.import.input": "the component file being exported or imported",
  "component.import.malformed": "the component file being exported or imported",
  "component.import.missingDependency": "the component file being exported or imported",
  "component.import.noComponent": "the component file being exported or imported",
  "component.import.notAComponent": "the component file being exported or imported",
  "component.import.readFailed": "the component file being exported or imported",
  "component.import.renamed": "imported under another id",
  "component.name": "a component with no name",
  "component.navigation.atRoot": "a component gesture with nothing to act on",
  "component.navigation.noCanvas": "a component gesture with nothing to act on",
  "component.navigation.noSelection": "a component gesture with nothing to act on",
  "component.navigation.notAComponent": "a component gesture with nothing to act on",
  "component.navigation.notInstalled": "a component gesture with nothing to act on",
  "component.notAnInstance": "a component command's input",
  "component.notFlattened": "the compile was given no component catalogue",
  "component.notInsideComponent": "a component command's input",
  "component.notInstalled": "a component command's input",
  "component.parameter.duplicate": "a key published twice",
  "component.parameter.incomplete": "a component command's input",
  "component.parameter.key": "a published parameter with no key",
  "component.parameter.missingTarget": "a published parameter whose target is not in the component",
  "component.parameter.noTargets": "a published key that drives nothing directly",
  "component.parameter.rangeWiderThanTarget": "it works inside the overlap of the two ranges",
  "component.parameter.reserved": "a key the instance's own preset state holds",
  "component.parameter.typeMismatch": "a published parameter of another type than its target",
  "component.parameter.unknown": "a component command's input",
  "component.parentScope.malformed": "a parent binding that is not parent.<key>",
  "component.parentScope.no-scope": "a parent binding on a node with no component around it",
  "component.parentScope.noScope": "a parent binding stored on a root node",
  "component.parentScope.too-deep": "a parent binding that reaches past the outermost component",
  "component.parentScope.type": "a parent value that does not fit the parameter",
  "component.parentScope.unknown-key": "a parent binding to a key the component does not publish",
  "component.path.missingNode": "a component gesture with nothing to act on",
  "component.path.notAComponent": "a component gesture with nothing to act on",
  "component.path.notInstalled": "a component gesture with nothing to act on",
  "component.port.duplicate": "a port exposed twice",
  "component.port.missingNode": "an exposed port mapped to a node that is not in the component",
  "component.port.missingPort": "an exposed port mapped to a port the node does not have",
  "component.presets.parentNamed": "a node named parent cannot be a preset target",
  "component.presets.twoPageBanks": "instances use the first of two page banks",
  "component.recursion": "a component that contains itself",
  "component.resolutionTargetMissing": "a resolution override path naming no internal node",
  "component.selection.empty": "a component gesture with nothing to act on",
  "component.selection.missingNode": "a component gesture with nothing to act on",
  "component.session.stale": "a component command's input",
  "component.starter.invalidDefinition": "a shipped starter component file is broken",
  "component.starter.invalidJson": "a shipped starter component file is broken",
  "component.starter.invalidLibrary": "a shipped starter component file is broken",
  "component.starter.rejected": "a shipped starter component file is broken",
  "component.upgrade.alreadyAtVersion": "a component command's input",
  "component.upgrade.droppedParameters": "values the new version does not publish were removed, and named",
  "component.upgrade.noMigration": "nothing says what changed between the versions",
  "component.upgrade.removedPorts": "edges on ports the new version lacks were removed, and named",
  "component.upgrade.valueReset": "a value the new version refuses was reset to its default",
  "component.version": "a component version that is not an integer from 1",
  "connect.incompatible": "a wire dropped on something it cannot join",
  "connect.incompatibleSwap": "a wire dropped on something it cannot join",
  "connect.noSuchNode": "a wire dropped on something it cannot join",
  "connect.noSuchPort": "a wire dropped on something it cannot join",
  "control.channel": "a Panel control command's input",
  "control.control": "a Panel control command's input",
  "control.default.driven": "a control default command's note: a driven key it left alone",
  "control.default.missing": "a control default command's note: a control with no default it left alone",
  "control.default.noNode": "a control default command's input",
  "control.default.notControl": "a control default command's input",
  "control.midi.mapping": "a Panel control command's input",
  "control.midi.range": "a Panel control command's input",
  "control.midi.source": "a Panel control command's input",
  "control.midi.target": "a Panel control command's input",
  "control.midi.unavailable": "a Panel control command's input",
  "control.midi.unbound": "a Panel control command's input",
  "control.midi.value": "a Panel control command's input",
  "control.node": "a Panel control command's input",
  "control.notBound": "a Panel control command's input",
  "control.panel": "a Panel control command's input",
  "control.panelAmbiguous": "a Panel control command's input",
  "control.parameter": "a Panel control command's input",
  "control.reset.nothing": "a control default command with nothing to change",
  "control.self": "a Panel control command's input",
  "control.setDefault.nothing": "a control default command with nothing to change",
  "control.shape": "a Panel control command's input",
  "control.unsupported": "a Panel control command's input",
  "cornerPin.extract.degenerate": "the quad cannot be pinned at these values: transparent, and said",
  "cornerPin.pin.degenerate": "the quad cannot be pinned at these values: transparent, and said",
  "cue.back.start": "a cue command with nothing to fire, or its input",
  "cue.back.unfired": "a cue command with nothing to fire, or its input",
  "cue.bank.malformed": "a cue's bank whose presets text does not read",
  "cue.bank.missing": "a cue naming a bank that is not in the document",
  "cue.bank.type": "a cue naming a node that is not a bank",
  "cue.current.unknown": "the stored current cue is no longer in the list",
  "cue.fire.nothing": "a cue command with nothing to fire, or its input",
  "cue.go.empty": "a cue list with no cues yet",
  "cue.go.end": "a cue command with nothing to fire, or its input",
  "cue.list.ambiguous": "a cue command with nothing to fire, or its input",
  "cue.list.malformed": "cues text that does not read",
  "cue.list.inInstance": "a cue command with nothing to fire, or its input",
  "cue.list.missing": "a cue command with nothing to fire, or its input",
  "cue.list.none": "a cue command with nothing to fire, or its input",
  "cue.list.type": "a cue command with nothing to fire, or its input",
  "cue.list.unknown": "a cue command with nothing to fire, or its input",
  "cue.preset.missing": "a cue naming a preset its bank does not hold",
  "cue.standby.unknown": "the stored standby names a cue that is gone",
  "cue.timeline": "a cue command with nothing to fire, or its input",
  "cue.timeline.bank": "a timed cue whose bank is missing, is not a bank, or cannot be read here",
  "cue.timeline.drivenMorph": "a timed cue uses the bank's stored fade, not its driver",
  "cue.timeline.malformed": "cues text that does not read: the list drives nothing",
  "cue.timeline.overlap": "two lists set one value: both run, in time order",
  "cue.timeline.preset": "a timed cue whose preset the bank does not hold, or cannot be read",
  "cue.timeline.structural": "a timed cue into a component that cannot be read here",
  "cue.timeline.untimed": "a cue with no At time on a list that follows the timeline",
  "cue.unknown": "a cue command with nothing to fire, or its input",
  "definition.unknown": "the agent tool's input or surface",
  "edge.duplicate": "the same connection twice",
  "edge.missing": "the patch operation's input",
  "edge.orderMismatch": "the patch operation's input",
  "example.unknown": "the agent tool's input or surface",
  "example.unreadable": "the agent tool's input or surface",
  "export.audioEncoderUnavailable": "a take or a readback, not the document",
  "export.audioNotDeterministic": "a take or a readback, not the document",
  "export.cleanupFailed": "a take or a readback, not the document",
  "export.encoderUnavailable": "a take or a readback, not the document",
  "export.failed": "a take or a readback, not the document",
  "export.invalidVideoSize": "a take or a readback, not the document",
  "export.missing": "a take or a readback, not the document",
  "export.noDevice": "a take or a readback, not the document",
  "export.noOutput": "a take or a readback, not the document",
  "export.noSession": "a take or a readback, not the document",
  "export.noTransport": "a take or a readback, not the document",
  "export.nonReproducible": "a take that a second render would not repeat",
  "export.planUpdating": "a take or a readback, not the document",
  "export.rangeNotContiguous": "a take or a readback, not the document",
  "export.recordingSourceFrameMismatch": "a take or a readback, not the document",
  "export.renderCancelled": "a take or a readback, not the document",
  "export.renderFailed": "a take or a readback, not the document",
  "export.renderInFlight": "a take or a readback, not the document",
  "export.renderRangeOutsideTimeline": "a take or a readback, not the document",
  "export.saveDestinationRequired": "a take or a readback, not the document",
  "export.saveDestinationUnavailable": "a take or a readback, not the document",
  "export.snapshotOversize": "a take or a readback, not the document",
  "export.writeFailed": "a take or a readback, not the document",
  "export/encoder-unavailable": "a take or a readback, not the document",
  "export/live-read-too-large": "a take or a readback, not the document",
  "export/malformed-readback": "a take or a readback, not the document",
  "export/readback-during-playback": "a take or a readback, not the document",
  "export/recording-backlog": "a take or a readback, not the document",
  "export/recording-duplicate-frame": "a take or a readback, not the document",
  "export/recording-failed": "a take or a readback, not the document",
  "export/recording-frame-gap": "a take or a readback, not the document",
  "export/recording-out-of-order": "a take or a readback, not the document",
  "export/region-out-of-bounds": "a take or a readback, not the document",
  "export/unknown-output": "a take or a readback, not the document",
  "export/unsupported-format": "a take or a readback, not the document",
  "fixture.noRename": "a test fixture's surface",
  "gpu.unavailable": "this session has no GPU device",
  "gridWarp.folded": "the grid folds over itself at these values: transparent, and said",
  "gridWarp.line.axis": "a Grid Warp line command's input",
  "gridWarp.line.driven": "a Grid Warp line command's input",
  "gridWarp.line.exists": "a Grid Warp line command's input",
  "gridWarp.line.max": "a Grid Warp line command's input",
  "gridWarp.line.min": "a Grid Warp line command's input",
  "gridWarp.line.missing": "a Grid Warp line command's input",
  "gridWarp.line.outside": "a Grid Warp line command's input",
  "gridWarp.node.missing": "a Grid Warp line command's input",
  "gridWarp.node.type": "a Grid Warp line command's input",
  "group.duplicate": "the patch operation's input",
  "group.missing": "the patch operation's input",
  "harness.animateOff": "a headless render asked for with animate off, of a document that holds expression slots",
  "help.noSurface": "an editor command with nothing to act on",
  "history.blocked": "an editor command with nothing to act on",
  "history.dryRun": "an editor command with nothing to act on",
  "history.empty": "an editor command with nothing to act on",
  "history.integrity": "an editor command with nothing to act on",
  "inspect.noPipelineSurface": "an editor command with nothing to act on",
  "inspect.noSurface": "an editor command with nothing to act on",
  "inspect.noTarget": "an editor command with nothing to act on",
  "inspect.unknownNode": "an editor command with nothing to act on",
  "laser.armed": "this session's device, helper or file",
  "laser.disarmed": "this session's device, helper or file",
  "laser.emission.blocked": "this session's device, helper or file",
  "laser.helper.absent": "this session's device, helper or file",
  "laser.source.missing": "a Laser Out with no path wired yet",
  "layout.alreadyTidy": "an editor command with nothing to act on",
  "layout.empty": "an editor command with nothing to act on",
  "layout.noShell": "an editor command with nothing to act on",
  "layout.unknownNodes": "an editor command with nothing to act on",
  "library.badPosition": "an editor command with nothing to act on",
  "library.noSurface": "an editor command with nothing to act on",
  "library.notOpened": "an editor command with nothing to act on",
  "mcp/bridge": "the MCP server's own state",
  "mcp/export-ungranted": "the MCP server's own state",
  "mcp/no-gpu": "the MCP server's own state",
  "media.connecting": "this session's device, helper or file",
  "media.notLoaded": "this session's device, helper or file",
  "media.playback": "this session's device, helper or file",
  "media.screenCapture": "this session's device, helper or file",
  "media.unavailable": "this session's device, helper or file",
  "mesh.decode": "this session's device, helper or file",
  "mesh.empty": "this session's device, helper or file",
  "mesh.note": "this session's device, helper or file",
  "mesh.read": "this session's device, helper or file",
  "mesh.unsizable": "a mesh inside a nested component: this build sizes a mesh one component level down",
  "native.input": "this session's device, helper or file",
  "native.output": "this session's device, helper or file",
  "node.ambiguous": "the patch operation's input",
  "node.camera.reference": "a camera name no camera payload arrived for",
  "node.channelMask.boundaryMissing": "the compiler's own channel boundary has nothing to write",
  "node.channelMask.invalid": "the patch operation's input",
  "node.channelMask.notComponent": "the patch operation's input",
  "node.channelMask.unsupported": "Processing Channels on a node with no texture to process",
  "node.channelMask.unwritten": "a node definition emitted no pass for a processed output",
  "node.compile.historyUnavailable": "a static tap deeper than the ring ever holds",
  "node.compile.missingResource": "an unwired input, or the compiler handing a definition no resource",
  "node.compile.tapClamped": "a tap past the history is clamped to the oldest frame held",
  "node.compile.tooManyInputs": "more wires than the node folds",
  "node.customWgsl.module": "a module the source asks for that does not exist, or an input it reads with no wire",
  "node.customWgsl.params": "a Params field named after one of the node's own keys",
  "node.customWgsl.viewCamera": "a half-declared view camera: the picture renders, the viewport is not offered",
  "node.duplicate": "the patch operation's input",
  "node.emptyLabel": "the patch operation's input",
  "node.format.invalid": "the patch operation's input",
  "node.label.empty": "the patch operation's input",
  "node.label.separator": "the patch operation's input",
  "node.label.tooLong": "the patch operation's input",
  "node.materialWgsl.params": "a Params field named after one of the material's own keys",
  "node.materialWgsl.source": "material source that breaks the surface contract",
  "node.materialWgsl.texture": "a `// @texture` line that names no texture: not a name, a name twice or taken, or a fifth",
  "node.materialWgsl.textureUnread": "a wire into a texture input the source names no texture for: nothing reads it, and the material is whole",
  "node.materialWgsl.textureUnwired": "a texture the source names with no wire into its input: it reads the moment one is wired",
  "node.mesh.clip": "a clip on a selection with no joints",
  "node.mesh.lamps": "more lamp groups than have a gain",
  "node.mesh.size": "past the device's storage binding baseline",
  "node.missing": "the patch operation's input",
  "node.name.kind": "the patch operation's input",
  "node.name.kindMissing": "the patch operation's input",
  "node.name.referencesRewritten": "the patch operation's input",
  "node.name.stranded": "the patch operation's input",
  "node.nameTaken": "two nodes may not share a name",
  "node.notShaderAuthorable": "the patch operation's input",
  "node.parameter.default": "a node definition the registry refuses at boot",
  "node.parameter.map": "a map the node cannot honour, or whose attribute the upstream does not carry",
  "node.parameter.pulse": "a node definition the registry refuses at boot",
  "node.points.attributes": "attributes text that does not read",
  "node.points.capacity": "past the device's storage baseline, or the build's point limit",
  "node.points.clock": "a kernel reading the timeline clock: it takes effect as stored",
  "node.points.curve": "a control set the basis cannot run, or control points that do not read",
  "node.points.curveFrames": "nothing to publish, or a seed the upstream does not carry",
  "node.points.edge": "a pointset input whose producer published nothing",
  "node.points.gather": "links or an attribute that do not fit, or storage past the baseline",
  "node.points.group": "a group predicate reading nothing, or an attribute the upstream lacks",
  "node.points.input": "an incoming pointset this kernel cannot take as it is",
  "node.points.kernel": "kernel source that breaks the contract, lacks its upstream, or passes a device limit",
  "node.points.lifecycle": "not reachable from a document",
  "node.points.module": "a module the kernel asks for that does not exist, or a name it declares twice",
  "node.points.params": "a Params field named after one of the kernel's own keys",
  "node.points.range": "an attribute or component the points do not have, or storage past the baseline",
  "node.points.resample": "an upstream the walk cannot follow, or a rule its padding breaks",
  "node.points.rope": "strands the solver cannot walk",
  "node.points.source": "not reachable from a document",
  "node.points.spawn": "spawn source that breaks the spawn contract",
  "node.points.strips": "an upstream that claims no strips yet",
  "node.points.sweep": "a path or profile the sweep cannot follow yet, or past a device limit",
  "node.points.transform": "storage past the device's baseline",
  "node.port": "a node definition the registry refuses at boot",
  "node.port.duplicate": "a node definition the registry refuses at boot",
  "node.position": "the patch operation's input",
  "node.resolution.invalid": "the patch operation's input",
  "node.scene.camera": "no camera named yet",
  "node.scene.empty": "no geometry named yet",
  "node.scene.endpoint": "beam mode with no endpoint attribute it can read yet",
  "node.scene.environment": "Show Environment with nothing wired: the Background colour stands in",
  "node.scene.geometry": "points that carry no payload yet, or a mode a counted set cannot draw in",
  "node.scene.glass": "glass on a draw this build does not refract",
  "node.scene.group": "a group predicate on a surface",
  "node.scene.instanceAttribute": "an instance binding that does not read, or an attribute the points lack",
  "node.scene.lightCapacity": "more light points than a Render lights from",
  "node.scene.lightDepth": "Light Depth Output with no light that casts yet",
  "node.scene.lightDraw": "a draw the lights of a pointset do not reach: unlit by them, and said",
  "node.scene.lightEverywhere": "more lights reach every pixel than is cheap: lit as stored, and said",
  "node.scene.lightPoints": "a Light in Points mode with no pointset or position to stand at yet",
  "node.scene.lightSpot": "a Spot where nothing reads a cone yet (a casting Light, a draw of instances) shines as a point light, and says so",
  "node.scene.maps": "texture maps on a draw that has no uv",
  "node.scene.material": "a Material · WGSL on a draw it does not run on",
  "node.scene.override": "a material override that does not read, or names nothing the material has",
  "node.scene.reference": "a name that resolves to a node of the wrong kind",
  "node.scene.shadowCasters": "a light that casts nothing in this Render may cast in another",
  "node.scene.shadowMesh": "a pointset on Shadow Mesh that carries no triangles, or no position and normal, yet",
  "node.scene.shadowMeshFit": "a shadow mesh that stands apart from its shape casts from there, as stored",
  "node.scene.shadowOnly": "Shadow Only on a geometry that casts no shadow",
  "node.scene.shape": "no mesh on Shape Mesh yet, or storage past the baseline",
  "node.scene.textureBudget": "past the device baseline of sampled textures",
  "node.scene.topology": "a surface whose points carry no grid or mesh topology yet",
  "node.scene.unlit": "a lit material with no lights named: the ambient floor stands in",
  "node.size.invalid": "the patch operation's input",
  "node.stateful.inconsistent": "a node definition the registry refuses at boot",
  "node.stateful.undeclared": "a node definition the registry refuses at boot",
  "node.surface.topology": "an upstream with no grid yet, or a claim that does not match its points",
  "node.temporal.port": "a node definition the registry refuses at boot",
  "node.type": "a node definition the registry refuses at boot",
  "node.type.duplicate": "a node definition the registry refuses at boot",
  "node.ui.type": "the patch operation's input",
  "node.ui.unknown": "the patch operation's input",
  "node.unknown": "the patch operation's input",
  "node.unknownType": "a node type this build does not have",
  "node.valueExpression.syntax": "a Value Expression statement that does not parse",
  "node.version": "a node definition the registry refuses at boot",
  "osc.helper": "this session's device, helper or file",
  "osc.send": "this session's device, helper or file",
  "output.notTexture": "the agent tool's input or surface",
  "output.toneMapInactive": "a tone map the project's display transform does not apply",
  "output.unknownDefinition": "the agent tool's input or surface",
  "output.unknownNode": "the agent tool's input or surface",
  "output.unknownPort": "the agent tool's input or surface",
  "parameter.bind.empty": "a bind to nothing",
  "parameter.bind.type": "a bind to a parameter of another type: no value of it fits",
  "parameter.bind.unavailable": "this resolution was handed no parent scope or sibling schema",
  "parameter.bind.unreadable": "a bind that names no parameter of its node, no component of it, itself, or no published parent key",
  "parameter.bind.value": "the bound value is past this parameter's limit or options: the stored value stands in",
  "parameter.bindCycle": "a bind chain that returns to itself",
  "parameter.channels.unavailable": "this process has no channel resolver",
  "parameter.clipboard.empty": "a parameter command's input",
  "parameter.clipboard.unreadable": "a parameter command's input",
  "parameter.driven": "a retired driven slot whose channel is not attached",
  "parameter.driven.clamped": "the channel overshot a declared limit: the limit is in effect",
  "parameter.driven.empty": "a driven slot naming no channel",
  "parameter.enum": "an option the parameter does not have",
  "parameter.expression.clamped": "the expression overshot a declared limit: the limit is in effect",
  "parameter.expression.name": "a bare name that is not a clock: nothing supplies it",
  "parameter.expression.syntax": "an expression that does not parse: a token, a function the grammar lacks, an argument count",
  "parameter.expression.type": "an expression on a parameter type that takes none",
  "parameter.expression.value": "arithmetic with no finite answer at this frame: the stored value stands in",
  "parameter.internal.nested": "the patch operation's input",
  "parameter.internal.notComponent": "the patch operation's input",
  "parameter.map.empty": "a map naming no attribute",
  "parameter.mode.payload": "a parameter command's input",
  "parameter.mode.retired": "a parameter command's input",
  "parameter.multipleOwners": "a parameter command's input",
  "parameter.node": "a parameter command's input",
  "parameter.paste.channelNoReading": "a parameter command's input",
  "parameter.paste.nameNotText": "a parameter command's input",
  "parameter.paste.noBinding": "a parameter command's input",
  "parameter.paste.noName": "a parameter command's input",
  "parameter.paste.noReference": "a parameter command's input",
  "parameter.paste.shape": "a parameter command's input",
  "parameter.paste.textIsReference": "a parameter command's input",
  "parameter.pulse.failed": "a parameter command's input",
  "parameter.pulse.node": "a parameter command's input",
  "parameter.pulse.stored": "a document may not hold an armed pulse",
  "parameter.pulse.type": "a parameter command's input",
  "parameter.pulse.unregistered": "a parameter command's input",
  "parameter.range": "a value past a declared limit is replaced by the default",
  "parameter.reference.ambiguous": "an instance publishes that channel on more than one output",
  "parameter.reference.channel": "the target publishes no such channel right now",
  "parameter.reference.node": "no node has that name yet",
  "parameter.reference.notComposed": "the read gives the stored offset, and the app names the channel that gives the composed value",
  "parameter.reference.self": "a parameter command's input",
  "parameter.reference.unavailable": "this read has no graph to resolve op() in",
  "parameter.reference.unknownType": "the target's type is not one this build has",
  "parameter.reference.unnamed": "a parameter command's input",
  "parameter.reference.unreadable": "a path no reader accepts, a parameter the target does not declare, or a value that is not a number",
  "parameter.reference.upstream": "the parameter read carries a finding of its own, and clears with it",
  "parameter.remove.absent": "a parameter command's input",
  "parameter.remove.declared": "a parameter command's input",
  "parameter.remove.none": "a parameter command's input",
  "parameter.referenceCycle": "an op() chain that returns to itself",
  "parameter.reset.cleared": "a parameter command's input",
  "parameter.retained": "a payload a slot keeps for a mode it is not in, which the write gate refuses: nothing reads it, and the default would stand in for it",
  "parameter.revert.created": "a parameter command's input",
  "parameter.revert.unopened": "a parameter command's input",
  "parameter.slot.empty": "a mode with no payload",
  "parameter.slot.shape": "a payload stored under another mode's binding",
  "parameter.slot.unknown": "a mode this build does not have",
  "parameter.stops.count": "more stops than the parameter carries",
  "parameter.type": "a value of the wrong shape is replaced by the default",
  "parameter.undefined": "a key written as undefined",
  "parameter.unknown": "a key the node does not declare: nothing reads it, at the write or at rest",
  "patch.conflict": "the patch operation's input",
  "patch.dryRun": "the patch operation's input",
  "patch.duplicateRef": "the patch operation's input",
  "patch.malformed": "the patch operation's input",
  "patch.staleBase": "the patch operation's input",
  "patch.unresolvedRef": "the patch operation's input",
  "perform.noWindowNode": "an editor command with nothing to act on",
  "perform.popupBlocked": "an editor command with nothing to act on",
  "perform.unavailable": "an editor command with nothing to act on",
  "points.readFailed": "the agent tool's input or surface",
  "points.unavailable": "the agent tool's input or surface",
  "port.incompatible": "two port types with no conversion between them",
  "port.missing": "a port the type does not declare",
  "port.notVariadic": "the patch operation's input",
  "port.occupied": "a second wire into a single input",
  "port.sourceReference": "the patch operation's input",
  "preset.bank.inDefinition": "a preset command's input",
  "preset.bank.malformed": "presets text that does not read",
  "preset.bank.missing": "a preset command's input",
  "preset.bank.inner": "a preset command's input",
  "preset.bank.nested": "a preset command's input",
  "preset.bank.noCatalogue": "this surface has no component catalogue",
  "preset.bank.noPageBank": "a component with no bank targeting parent yet",
  "preset.bank.notInstalled": "an instance of a component that is not installed",
  "preset.bank.type": "a preset command's input",
  "preset.bank.unknown": "a preset command's input",
  "preset.bank.unnamed": "an instance with no name yet",
  "preset.component.written": "a preset command's input",
  "preset.delete.cued": "a preset command's input",
  "preset.delete.recalled": "a preset command's input",
  "preset.delete.unknown": "a preset command's input",
  "preset.move.clash": "a preset command's input",
  "preset.move.noInstance": "a preset command's input",
  "preset.move.notOneLook": "a preset command's input",
  "preset.name": "a preset command's input",
  "preset.on.missing": "on/off for a Layer that is not in the document",
  "preset.on.notLayer": "on/off for a node that is not a Layer",
  "preset.page.notParent": "a page bank's preset holding values for a name other than parent",
  "preset.page.on": "a page bank's preset carrying on/off: it reaches only its page",
  "preset.page.recalls": "a page bank's preset carrying recalls: it reaches only its page",
  "preset.recall.componentOverride": "written, and one channel is still overridden by its own slot",
  "preset.recall.cycle": "recalls that go round in a circle",
  "preset.recall.depth": "recalls nested past the limit",
  "preset.recall.morph": "a preset command's input",
  "preset.recall.morphDropped": "the oldest fade was dropped: its keys jumped",
  "preset.recall.morphUnavailable": "no frame clock here, so the morph is a cut",
  "preset.recall.noName": "a preset command's input",
  "preset.recall.nothing": "a preset command's input",
  "preset.recall.unknown": "a preset command's input",
  "preset.recalls.malformed": "a shot recalls a bank whose text does not read",
  "preset.recalls.missing": "a shot recalls a bank that is not in the document",
  "preset.recalls.noCatalogue": "this surface has no component catalogue",
  "preset.recalls.noPageBank": "a component with no bank targeting parent yet",
  "preset.recalls.notInstalled": "an instance of a component that is not installed",
  "preset.recalls.type": "a shot recalls a node that is not a bank",
  "preset.recalls.unknown": "a shot recalls a preset its bank does not hold",
  "preset.store.noTargets": "a bank with no targets yet",
  "preset.store.nothing": "a preset command's input",
  "preset.target.default": "a stored value for a control's default, which a recall never writes",
  "preset.target.key": "a target key the node does not declare, or that holds no value",
  "preset.target.missing": "a target that is not in the document",
  "preset.target.pulse": "a stored value for a pulse, which fires and holds nothing",
  "preset.target.self": "a bank targeting itself",
  "preset.target.unknownType": "a target of a node type this build does not have",
  "preset.value.invalid": "a stored value the node's parameter refuses",
  "preview.noTarget": "the agent tool's input or surface",
  "preview.statsFailed": "the agent tool's input or surface",
  "preview.statsUnavailable": "the agent tool's input or surface",
  "preview.unknownLens": "the agent tool's input or surface",
  "preview.unknownNode": "the agent tool's input or surface",
  "project.asset.unresolved": "a session's file that is gone after a reload",
  "project.autosave.failed": "opening, saving or autosaving, not what the document holds",
  "project.autosave.unavailable": "opening, saving or autosaving, not what the document holds",
  "project.components.invalid": "a component library this build cannot read",
  "project.components.rejected": "a component definition the registry refuses",
  "project.limit.buffer": "a limit check no product path calls",
  "project.limit.dispatch": "a limit check no product path calls",
  "project.limit.memoryBudget": "over the project's own budget: reported, nothing altered",
  "project.limit.nodeResolution": "a node resolution clamped to the limit",
  "project.limit.preview": "the preview edge clamped to the limit",
  "project.limit.resolution": "the output resolution clamped to the limit",
  "project.limit.settings": "a project limit clamped to the hard limit",
  "project.migration.applied": "the file was upgraded, and says so",
  "project.migration.backwards": "the build's own migration ladder",
  "project.migration.duplicate": "the build's own migration ladder",
  "project.migration.failed": "the build's own migration ladder",
  "project.migration.malformed": "the build's own migration ladder",
  "project.migration.missing": "the build's own migration ladder",
  "project.migration.noVersion": "a file with no schema version does not open",
  "project.new.unsupported": "opening, saving or autosaving, not what the document holds",
  "project.noSurface": "opening, saving or autosaving, not what the document holds",
  "project.node.migrated": "a node was migrated, and says what moved",
  "project.node.migrationFailed": "a node migration threw",
  "project.node.newerVersion": "a newer build's node: kept and written back",
  "project.node.noMigration": "it runs on the current definition: nothing says what moved",
  "project.node.unknownType": "a node type this build does not have: kept as a placeholder",
  "project.open.failed": "opening, saving or autosaving, not what the document holds",
  "project.open.rejected": "opening, saving or autosaving, not what the document holds",
  "project.parameter.unknownKind": "a value shape this build does not read: kept and written back",
  "project.parse.invalidDocument": "a file that is not a project document does not open",
  "project.parse.invalidJson": "a file that is not JSON does not open",
  "project.parse.notAnObject": "a file that holds no project object does not open",
  "project.save.failed": "opening, saving or autosaving, not what the document holds",
  "project.schema.newer": "a newer build's file",
  "project.settings.invalid": "opening, saving or autosaving, not what the document holds",
  "proposal.unknown": "the agent tool's input or surface",
  "ramp.stops.capped": "the first sixteen stops render",
  "ramp.stops.unordered": "it renders exactly as stored",
  "rename.noTarget": "an editor command with nothing to act on",
  "rename.unknownNode": "an editor command with nothing to act on",
  "requirement.unmet": "this machine cannot run the node",
  "runtime.noBackend": "an editor command with nothing to act on",
  "runtime.noFeedback": "an editor command with nothing to act on",
  "selection.empty": "an editor command with nothing to act on",
  "selection.noCanvas": "an editor command with nothing to act on",
  "session.noInstance": "a command about a running instance, fired in a component editor that is open through none",
  "session.projectStep": "a note on a command that changed the project from inside a component editor",
  "settings.noSurface": "an editor command with nothing to act on",
  "shader/compile-error": "a stored shader the device refuses",
  "shader/compile-failed": "the shader pane's compile pipeline failed",
  "shader/compile-info": "the device's remark on a shader that compiled",
  "shader/compile-warning": "the device's warning on a shader that compiled",
  "shader/output-stale": "the shader pane's state",
  "sideEffect.blocked": "this session's device, helper or file",
  "tool.awaitingApproval": "the agent tool's input or surface",
  "tool.dryRun": "the agent tool's input or surface",
  "tool.failed": "the agent tool's input or surface",
  "tool.input": "the agent tool's input or surface",
  "tool.partialSource": "the agent tool's input or surface",
  "tool.truncated": "the agent tool's input or surface",
  "tool.unavailable": "the agent tool's input or surface",
  "tool.unavailableCommand": "the agent tool's input or surface",
  "tool.unavailablePort": "the agent tool's input or surface",
  "tool.unavailableQuery": "the agent tool's input or surface",
  "tool.unknown": "the agent tool's input or surface",
  "transaction.dryRun": "an editor command with nothing to act on",
  "transaction.empty": "an editor command with nothing to act on",
  "transaction.partialRevert": "an editor command with nothing to act on",
  "transaction.unknown": "an editor command with nothing to act on",
  "transport.noLoop": "an editor command with nothing to act on",
  "transport.seekLimit": "an editor command with nothing to act on",
  "transport.seekRange": "an editor command with nothing to act on",
  "valueGraph.channelShadowed": "one of two same-named channels wins",
  "valueGraph.cycle": "a loop through a wire and an op() reference: its members emit nothing",
  "valueGraph.evaluate": "a node definition's evaluate threw",
  "view.fullscreenRefused": "an editor command with nothing to act on",
  "view.fullscreenUnsupported": "an editor command with nothing to act on",
  "view.noCanvas": "an editor command with nothing to act on",
  "view.noFullscreenSurface": "an editor command with nothing to act on",
  "view.nothingToFrame": "an editor command with nothing to act on",
  "viewer.flyDirection": "an editor command with nothing to act on",
  "viewer.noCameraToFly": "an editor command with nothing to act on",
  "viewer.noNode": "an editor command with nothing to act on",
  "viewer.noOrbit": "an editor command with nothing to act on",
  "viewer.noOutput": "an editor command with nothing to act on",
  "viewer.noPane": "an editor command with nothing to act on",
  "vision.helper.absent": "this session's device, helper or file",
  "vision.native.refused": "this session's device, helper or file",
  "vision.native.retirement": "this session's device, helper or file",
  "vision.native.starting": "this session's device, helper or file",
  "vision.refused": "this session's device, helper or file",
  "wgsl/compile": "the device's own message for a stored shader: an error, or a remark",
};
