/**
 * T1641b — THE CLASS OF EVERY DIAGNOSTIC CODE.
 *
 * A `RuntimeDiagnostic` carries a `code`, and until this file there was no list of them and
 * no statement of what one MEANS for the thing it is about. Two defects shipped through that
 * gap in one day (§B262, §B264): a stored expression that could never be evaluated and a
 * stored value under a key nothing reads were each a WARNING, of the same weight as a
 * clamped slider, and the picture looked plausible. So every code has a row here that says
 * which of these it is:
 *
 *  - `never`: as stored it can never do what it says. It cannot be evaluated, nothing reads
 *    it, or no write path would have accepted it. Only changing the stored thing fixes it.
 *  - `notYet`: it takes effect the moment something else arrives (a node of that name, a
 *    wire, an attribute upstream, a channel, a file). Legitimate while editing.
 *  - `elsewhereBuild`: true of this build only: a newer build, or an installed component, has it.
 *  - `elsewhereHost`: true of this device, process or session only.
 *  - `degraded`: it takes effect, not as written, and the diagnostic says what stands in.
 *  - `advice`: it takes effect exactly as stored, and the app has a remark.
 *  - `act`: about a command (its input, or a note on what it did), not about anything stored.
 *  - `build`: about this build's own definitions or an internal contract. Never a document's fault.
 *
 * `docs/never-effective-refusals-2026-10-06.md` holds the reading behind each row and the
 * rule this table is the first slice of.
 *
 * ## The table is total, in both directions
 *
 * `classes.test.ts` reads every diagnostic code out of the source tree and fails when a code
 * has no row here, and when a row names a code nothing emits any more. A new diagnostic
 * therefore chooses its class in the diff that adds it.
 *
 * ## One code, one class, with the debt written down
 *
 * A code means one class. The rows that carry `splits` do not: each is emitted today for
 * conditions of more than one class, listed in `holds`. Until T1641b splits such a code, its
 * `class` is the LEAST refusing of those it holds, so that reading this table refuses
 * nothing that was not refused before. The gate holds the list of them by name: it can only
 * get shorter, and a new code may not join it.
 *
 * ## Who reads it (T1641b)
 *
 * Slice 0 was the table and its gate. Slice 1 gave it its first product reader: the
 * compiler's `hasError` asks `leavesPlanUsable`, so a `never` finding marked `local` is
 * reported as an ERROR while the plan it sits in stays usable. `local` means the stored
 * thing is inert on its own: its stated fallback is in effect and the rest of the document
 * is whole. A document that rendered yesterday with a warning must not open black because
 * the report got louder. Every code that was a warning before the rule and is `never` under
 * it is `local`; a code that was an error before stays as it was. The bus, the save path and
 * the headless harness's document check are the slices that follow.
 */

export type DiagnosticClass = "never" | "notYet" | "elsewhereBuild" | "elsewhereHost" | "degraded" | "advice" | "act" | "build";

export interface DiagnosticClassRow {
  readonly class: DiagnosticClass;
  /** `never` only: the finding leaves the rest of the plan usable. */
  readonly local?: true;
  /** Debt: the classes this one code is emitted for today, and the task that splits it. */
  readonly splits?: { readonly task: string; readonly holds: readonly DiagnosticClass[] };
  /** Why it is of that class, in a few words. */
  readonly reason: string;
}

export const DIAGNOSTIC_CLASSES: Readonly<Record<string, DiagnosticClassRow>> = {
  "animation/structuralDrift": { class: "build", reason: "a frame's plan differs in structure from the installed one" },
  "asset.badData": { class: "act", reason: "the attach_asset tool's input" },
  "asset.parameterUnresolved": { class: "act", reason: "the attach_asset tool's input" },
  "asset.reference.error": { class: "elsewhereHost", reason: "a retained file this session could not open" },
  "asset.reference.invalid": { class: "never", reason: "a file reference that does not read" },
  "asset.reference.missing": { class: "elsewhereHost", reason: "a retained file this browser no longer holds" },
  "asset.reference.pending": { class: "elsewhereHost", reason: "a retained file still opening" },
  "asset.reference.permission": { class: "elsewhereHost", reason: "a retained file this session may not read yet" },
  "audio.noSession": { class: "act", reason: "recording or reading an audio feature track" },
  "audio.noSource": { class: "act", reason: "recording or reading an audio feature track" },
  "audio.nothingRecorded": { class: "act", reason: "recording or reading an audio feature track" },
  "audio.track.fps": { class: "act", reason: "recording or reading an audio feature track" },
  "audio.track.frames": { class: "act", reason: "recording or reading an audio feature track" },
  "audio.track.malformed": { class: "act", reason: "recording or reading an audio feature track" },
  "audio.track.provenance": { class: "act", reason: "recording or reading an audio feature track" },
  "audio.track.version": { class: "act", reason: "recording or reading an audio feature track" },
  "audio.trackWriteFailed": { class: "act", reason: "recording or reading an audio feature track" },
  "backend/capability-below-baseline": { class: "elsewhereHost", reason: "the device's state" },
  "backend/compile-failed": { class: "never", reason: "a stored shader the device refuses" },
  "backend/device-lost": { class: "elsewhereHost", reason: "the device's state" },
  "backend/device-restored": { class: "elsewhereHost", reason: "the device's state" },
  "backend/frame-error": { class: "build", reason: "the plan and the device disagree" },
  "backend/init-failed": { class: "elsewhereHost", reason: "the device's state" },
  "backend/not-initialized": { class: "elsewhereHost", reason: "the device's state" },
  "backend/plan-invalid": { class: "build", reason: "the plan and the device disagree" },
  "backend/plan-not-current": { class: "build", reason: "the plan and the device disagree" },
  "backend/present-failed": { class: "elsewhereHost", reason: "the device's state" },
  "backend/rebuild-failed": { class: "build", reason: "the plan and the device disagree" },
  "backend/recover-failed": { class: "build", reason: "the plan and the device disagree" },
  "backend/resource-limit": { class: "elsewhereHost", reason: "the device's state" },
  "backend/shader-validation-unavailable": { class: "elsewhereHost", reason: "the device's state" },
  "backend/submission-halted": { class: "build", reason: "the plan and the device disagree" },
  "backend/temporal-reset": { class: "elsewhereHost", reason: "the device's state" },
  "backend/timestamp-unavailable": { class: "elsewhereHost", reason: "the device's state" },
  "backend/unknown-output": { class: "build", reason: "the plan and the device disagree" },
  "backend/unknown-pass": { class: "build", reason: "the plan and the device disagree" },
  "backend/unknown-resource": { class: "build", reason: "the plan and the device disagree" },
  "bridge/detached": { class: "act", reason: "the MCP bridge's connection" },
  "bridge/devices-only": { class: "act", reason: "the MCP bridge's connection" },
  "bridge/not-the-owner": { class: "act", reason: "the MCP bridge's connection" },
  "bridge/page-error": { class: "act", reason: "the MCP bridge's connection" },
  "bridge/proxy-lost": { class: "act", reason: "the MCP bridge's connection" },
  "bridge/timeout": { class: "act", reason: "the MCP bridge's connection" },
  "capability.denied": { class: "act", reason: "a capability the caller does not hold" },
  "capability.unobtainable": { class: "act", reason: "a capability the caller does not hold" },
  "channel.reference.unnamed": { class: "act", reason: "a copy of a reference to a node with no name" },
  "clipboard.empty": { class: "act", reason: "what the clipboard holds" },
  "clipboard.foreign": { class: "act", reason: "what the clipboard holds" },
  "command.failed": { class: "act", reason: "the command's input, or its handler threw" },
  "command.input": { class: "act", reason: "the command's input, or its handler threw" },
  "compile.noCompiler": { class: "act", reason: "no compiler or device to compile with here" },
  "compile.noDevice": { class: "act", reason: "no compiler or device to compile with here" },
  "compiler.crashed": { class: "build", reason: "the compiler threw" },
  "compiler/binding-budget": { class: "elsewhereHost", reason: "a pass binds more than this device allows" },
  "compiler/binding-unfilterable": { class: "elsewhereHost", reason: "this device cannot filter the format a pass samples" },
  "compiler/bypass-incoherent": { class: "degraded", reason: "a bypass with no input to pass through: muted instead" },
  "compiler/camera-preview-ambiguous": { class: "advice", reason: "a camera shared by renderers previews the stock scene" },
  "compiler/color-space-mismatch": { class: "advice", reason: "it renders as wired: the compiler never converts" },
  "compiler/component-id-collision": { class: "never", reason: "two nodes flatten to one id: the second is dropped" },
  "compiler/component-missing": { class: "elsewhereBuild", reason: "an instance of a component that is not installed" },
  "compiler/component-parameter-conflict": { class: "never", local: true, reason: "a parent read that cannot resolve, or one a published value shadows" },
  "compiler/component-port-unresolved": { class: "never", reason: "an edge onto a port the component does not expose" },
  "compiler/component-recursion": { class: "never", reason: "a component that contains itself" },
  "compiler/cycle": { class: "never", reason: "a same-frame loop with no temporal node in it" },
  "compiler/definition-version": { class: "degraded", splits: { task: "T1641b", holds: ["degraded", "elsewhereBuild"] }, reason: "a node saved against another version of its definition" },
  "compiler/edge-endpoint-missing": { class: "elsewhereBuild", splits: { task: "T1641b", holds: ["never", "elsewhereBuild"] }, reason: "an edge whose endpoint is not in the document, or is of an unknown type" },
  "compiler/format-depth-on-color": { class: "never", reason: "a depth format on a colour output can never apply" },
  "compiler/format-input-missing": { class: "degraded", reason: "the working format stands in for an unwired input's" },
  "compiler/format-no-fallback": { class: "elsewhereHost", reason: "this device lacks the format and nothing can stand in" },
  "compiler/format-unsupported": { class: "elsewhereHost", reason: "this device lacks the format: a named one stands in" },
  "compiler/input-missing": { class: "notYet", reason: "a required input not wired yet" },
  "compiler/memory-budget": { class: "advice", reason: "over the project's own budget: reported, not enforced" },
  "compiler/no-active-sinks": { class: "notYet", reason: "nothing reaches an output yet" },
  "compiler/node-compile-failed": { class: "build", reason: "a node definition's compile threw" },
  "compiler/node-no-passes": { class: "build", reason: "a node definition emitted no passes" },
  "compiler/pass-invalid": { class: "build", reason: "a node definition emitted a malformed pass" },
  "compiler/passthrough-unconnected": { class: "notYet", reason: "a Null chain that reaches no producer yet" },
  "compiler/port-incompatible": { class: "never", reason: "two port types with no conversion between them" },
  "compiler/port-missing": { class: "never", reason: "an edge on a port the type does not declare" },
  "compiler/port-occupied": { class: "never", reason: "a second wire into a single input is ignored" },
  "compiler/resolution-clamped": { class: "degraded", reason: "scaled down to the limit in force" },
  "compiler/resolution-custom": { class: "degraded", reason: "the project resolution stands in for a custom policy" },
  "compiler/resolution-input-missing": { class: "degraded", reason: "the project resolution stands in for an unwired input's" },
  "compiler/resolution-parameter": { class: "degraded", reason: "the project resolution stands in for a parameter that gives none" },
  "compiler/scratch-invalid": { class: "build", reason: "a node definition declared malformed scratch" },
  "compiler/sink-unknown": { class: "act", reason: "the request's sink, not the document's" },
  "compiler/source-reference-ambiguous": { class: "never", reason: "a name and a wire on one input: one is never read" },
  "compiler/source-reference-missing": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "never"] }, reason: "a named source that no node holds, or that can never fit the input" },
  "compiler/substeps-refused": { class: "degraded", reason: "it runs one step, or a capped count, and says so" },
  "compiler/unknown-node-type": { class: "elsewhereBuild", reason: "a node type this build does not have" },
  "compiler/wgsl-high-half-divide": { class: "advice", reason: "valid WGSL that Apple GPUs compute wrongly: nothing is refused" },
  "component.channelMaskTargetMissing": { class: "never", reason: "a mask override path naming no internal node" },
  "component.create.noCanvas": { class: "act", reason: "a component gesture with nothing to act on" },
  "component.create.noSelection": { class: "act", reason: "a component gesture with nothing to act on" },
  "component.detach.channelMask": { class: "degraded", reason: "the copies draw every channel" },
  "component.detach.inexact": { class: "degraded", reason: "a value the copies could not carry exactly" },
  "component.detach.instancePaths": { class: "never", local: true, reason: "the detach left override paths that name nothing" },
  "component.detach.nestedParentReads": { class: "degraded", reason: "a nested parent read now names one component further out" },
  "component.detach.outerTarget": { class: "degraded", reason: "a published key no longer drives the copies" },
  "component.detach.overrideMissing": { class: "never", local: true, reason: "an override for an internal node the definition lacks" },
  "component.detach.pageBank": { class: "degraded", reason: "the page bank was rewritten for the copies" },
  "component.detach.pageBankInert": { class: "never", local: true, reason: "the detach left a root bank targeting parent" },
  "component.detach.parentValues": { class: "degraded", reason: "the copies hold the values their parent reads gave" },
  "component.export.failed": { class: "act", reason: "the component file being exported or imported" },
  "component.export.input": { class: "act", reason: "the component file being exported or imported" },
  "component.export.missingDependency": { class: "act", reason: "the component file being exported or imported" },
  "component.export.noWriter": { class: "act", reason: "the component file being exported or imported" },
  "component.export.sessionAsset": { class: "act", reason: "the component file being exported or imported" },
  "component.id": { class: "never", reason: "a component id the registry will not hold" },
  "component.import.input": { class: "act", reason: "the component file being exported or imported" },
  "component.import.malformed": { class: "act", reason: "the component file being exported or imported" },
  "component.import.missingDependency": { class: "act", reason: "the component file being exported or imported" },
  "component.import.noComponent": { class: "act", reason: "the component file being exported or imported" },
  "component.import.notAComponent": { class: "act", reason: "the component file being exported or imported" },
  "component.import.readFailed": { class: "act", reason: "the component file being exported or imported" },
  "component.import.renamed": { class: "degraded", reason: "imported under another id" },
  "component.name": { class: "never", reason: "a component with no name" },
  "component.navigation.atRoot": { class: "act", reason: "a component gesture with nothing to act on" },
  "component.navigation.noCanvas": { class: "act", reason: "a component gesture with nothing to act on" },
  "component.navigation.noSelection": { class: "act", reason: "a component gesture with nothing to act on" },
  "component.navigation.notAComponent": { class: "act", reason: "a component gesture with nothing to act on" },
  "component.navigation.notInstalled": { class: "act", reason: "a component gesture with nothing to act on" },
  "component.notAnInstance": { class: "act", reason: "a component command's input" },
  "component.notFlattened": { class: "build", reason: "the compile was given no component catalogue" },
  "component.notInsideComponent": { class: "act", reason: "a component command's input" },
  "component.notInstalled": { class: "act", reason: "a component command's input" },
  "component.parameter.duplicate": { class: "never", reason: "a key published twice" },
  "component.parameter.incomplete": { class: "act", reason: "a component command's input" },
  "component.parameter.key": { class: "never", reason: "a published parameter with no key" },
  "component.parameter.missingTarget": { class: "never", reason: "a published parameter whose target is not in the component" },
  "component.parameter.noTargets": { class: "advice", splits: { task: "T1641b", holds: ["advice", "never"] }, reason: "a published key that drives nothing directly" },
  "component.parameter.rangeWiderThanTarget": { class: "degraded", reason: "it works inside the overlap of the two ranges" },
  "component.parameter.reserved": { class: "never", reason: "a key the instance's own preset state holds" },
  "component.parameter.typeMismatch": { class: "never", reason: "a published parameter of another type than its target" },
  "component.parameter.unknown": { class: "act", reason: "a component command's input" },
  "component.parentScope.malformed": { class: "never", reason: "a parent binding that is not parent.<key>" },
  "component.parentScope.no-scope": { class: "never", reason: "a parent binding on a node with no component around it" },
  "component.parentScope.noScope": { class: "never", local: true, reason: "a parent binding stored on a root node" },
  "component.parentScope.too-deep": { class: "never", reason: "a parent binding that reaches past the outermost component" },
  "component.parentScope.type": { class: "degraded", splits: { task: "T1641b", holds: ["never", "degraded"] }, reason: "a parent value that does not fit the parameter" },
  "component.parentScope.unknown-key": { class: "never", reason: "a parent binding to a key the component does not publish" },
  "component.path.missingNode": { class: "act", reason: "a component gesture with nothing to act on" },
  "component.path.notAComponent": { class: "act", reason: "a component gesture with nothing to act on" },
  "component.path.notInstalled": { class: "act", reason: "a component gesture with nothing to act on" },
  "component.port.duplicate": { class: "never", reason: "a port exposed twice" },
  "component.port.missingNode": { class: "never", reason: "an exposed port mapped to a node that is not in the component" },
  "component.port.missingPort": { class: "never", reason: "an exposed port mapped to a port the node does not have" },
  "component.presets.parentNamed": { class: "advice", reason: "a node named parent cannot be a preset target" },
  "component.presets.twoPageBanks": { class: "degraded", reason: "instances use the first of two page banks" },
  "component.recursion": { class: "never", reason: "a component that contains itself" },
  "component.resolutionTargetMissing": { class: "never", reason: "a resolution override path naming no internal node" },
  "component.selection.empty": { class: "act", reason: "a component gesture with nothing to act on" },
  "component.selection.missingNode": { class: "act", reason: "a component gesture with nothing to act on" },
  "component.session.stale": { class: "act", reason: "a component command's input" },
  "component.starter.invalidDefinition": { class: "build", reason: "a shipped starter component file is broken" },
  "component.starter.invalidJson": { class: "build", reason: "a shipped starter component file is broken" },
  "component.starter.invalidLibrary": { class: "build", reason: "a shipped starter component file is broken" },
  "component.starter.rejected": { class: "build", reason: "a shipped starter component file is broken" },
  "component.upgrade.alreadyAtVersion": { class: "act", reason: "a component command's input" },
  "component.upgrade.droppedParameters": { class: "degraded", reason: "values the new version does not publish were removed, and named" },
  "component.upgrade.noMigration": { class: "degraded", reason: "nothing says what changed between the versions" },
  "component.upgrade.removedPorts": { class: "degraded", reason: "edges on ports the new version lacks were removed, and named" },
  "component.upgrade.valueReset": { class: "degraded", reason: "a value the new version refuses was reset to its default" },
  "component.version": { class: "never", reason: "a component version that is not an integer from 1" },
  "connect.incompatible": { class: "act", reason: "a wire dropped on something it cannot join" },
  "connect.incompatibleSwap": { class: "act", reason: "a wire dropped on something it cannot join" },
  "connect.noSuchNode": { class: "act", reason: "a wire dropped on something it cannot join" },
  "connect.noSuchPort": { class: "act", reason: "a wire dropped on something it cannot join" },
  "control.channel": { class: "act", reason: "a Panel control command's input" },
  "control.control": { class: "act", reason: "a Panel control command's input" },
  "control.default.driven": { class: "act", reason: "a control default command's note: a driven key it left alone" },
  "control.default.missing": { class: "act", reason: "a control default command's note: a control with no default it left alone" },
  "control.default.noNode": { class: "act", reason: "a control default command's input" },
  "control.default.notControl": { class: "act", reason: "a control default command's input" },
  "control.midi.mapping": { class: "act", reason: "a Panel control command's input" },
  "control.midi.range": { class: "act", reason: "a Panel control command's input" },
  "control.midi.source": { class: "act", reason: "a Panel control command's input" },
  "control.midi.target": { class: "act", reason: "a Panel control command's input" },
  "control.midi.unavailable": { class: "act", reason: "a Panel control command's input" },
  "control.midi.unbound": { class: "act", reason: "a Panel control command's input" },
  "control.midi.value": { class: "act", reason: "a Panel control command's input" },
  "control.node": { class: "act", reason: "a Panel control command's input" },
  "control.notBound": { class: "act", reason: "a Panel control command's input" },
  "control.panel": { class: "act", reason: "a Panel control command's input" },
  "control.panelAmbiguous": { class: "act", reason: "a Panel control command's input" },
  "control.parameter": { class: "act", reason: "a Panel control command's input" },
  "control.reset.nothing": { class: "act", reason: "a control default command with nothing to change" },
  "control.self": { class: "act", reason: "a Panel control command's input" },
  "control.setDefault.nothing": { class: "act", reason: "a control default command with nothing to change" },
  "control.shape": { class: "act", reason: "a Panel control command's input" },
  "control.unsupported": { class: "act", reason: "a Panel control command's input" },
  "cornerPin.extract.degenerate": { class: "degraded", reason: "the quad cannot be pinned at these values: transparent, and said" },
  "cornerPin.pin.degenerate": { class: "degraded", reason: "the quad cannot be pinned at these values: transparent, and said" },
  "cue.back.start": { class: "act", reason: "a cue command with nothing to fire, or its input" },
  "cue.back.unfired": { class: "act", reason: "a cue command with nothing to fire, or its input" },
  "cue.bank.malformed": { class: "never", reason: "a cue's bank whose presets text does not read" },
  "cue.bank.missing": { class: "notYet", reason: "a cue naming a bank that is not in the document" },
  "cue.bank.type": { class: "never", reason: "a cue naming a node that is not a bank" },
  "cue.current.unknown": { class: "notYet", reason: "the stored current cue is no longer in the list" },
  "cue.fire.nothing": { class: "act", reason: "a cue command with nothing to fire, or its input" },
  "cue.go.empty": { class: "notYet", reason: "a cue list with no cues yet" },
  "cue.go.end": { class: "act", reason: "a cue command with nothing to fire, or its input" },
  "cue.list.ambiguous": { class: "act", reason: "a cue command with nothing to fire, or its input" },
  "cue.list.malformed": { class: "never", reason: "cues text that does not read" },
  "cue.list.missing": { class: "act", reason: "a cue command with nothing to fire, or its input" },
  "cue.list.none": { class: "act", reason: "a cue command with nothing to fire, or its input" },
  "cue.list.type": { class: "act", reason: "a cue command with nothing to fire, or its input" },
  "cue.list.unknown": { class: "act", reason: "a cue command with nothing to fire, or its input" },
  "cue.preset.missing": { class: "notYet", reason: "a cue naming a preset its bank does not hold" },
  "cue.standby.unknown": { class: "notYet", reason: "the stored standby names a cue that is gone" },
  "cue.timeline": { class: "act", reason: "a cue command with nothing to fire, or its input" },
  "cue.timeline.bank": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "never", "elsewhereBuild"] }, reason: "a timed cue whose bank is missing, is not a bank, or cannot be read here" },
  "cue.timeline.drivenMorph": { class: "degraded", reason: "a timed cue uses the bank's stored fade, not its driver" },
  "cue.timeline.malformed": { class: "never", local: true, reason: "cues text that does not read: the list drives nothing" },
  "cue.timeline.overlap": { class: "advice", reason: "two lists set one value: both run, in time order" },
  "cue.timeline.preset": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "never"] }, reason: "a timed cue whose preset the bank does not hold, or cannot be read" },
  "cue.timeline.structural": { class: "elsewhereBuild", reason: "a timed cue into a component that cannot be read here" },
  "cue.timeline.untimed": { class: "notYet", reason: "a cue with no At time on a list that follows the timeline" },
  "cue.unknown": { class: "act", reason: "a cue command with nothing to fire, or its input" },
  "definition.unknown": { class: "act", reason: "the agent tool's input or surface" },
  "edge.duplicate": { class: "never", reason: "the same connection twice" },
  "edge.missing": { class: "act", reason: "the patch operation's input" },
  "edge.orderMismatch": { class: "act", reason: "the patch operation's input" },
  "example.unknown": { class: "act", reason: "the agent tool's input or surface" },
  "example.unreadable": { class: "act", reason: "the agent tool's input or surface" },
  "export.audioEncoderUnavailable": { class: "act", reason: "a take or a readback, not the document" },
  "export.audioNotDeterministic": { class: "act", reason: "a take or a readback, not the document" },
  "export.cleanupFailed": { class: "act", reason: "a take or a readback, not the document" },
  "export.encoderUnavailable": { class: "act", reason: "a take or a readback, not the document" },
  "export.failed": { class: "act", reason: "a take or a readback, not the document" },
  "export.invalidVideoSize": { class: "act", reason: "a take or a readback, not the document" },
  "export.missing": { class: "act", reason: "a take or a readback, not the document" },
  "export.noDevice": { class: "act", reason: "a take or a readback, not the document" },
  "export.noOutput": { class: "act", reason: "a take or a readback, not the document" },
  "export.noSession": { class: "act", reason: "a take or a readback, not the document" },
  "export.noTransport": { class: "act", reason: "a take or a readback, not the document" },
  "export.nonReproducible": { class: "advice", reason: "a take that a second render would not repeat" },
  "export.planUpdating": { class: "act", reason: "a take or a readback, not the document" },
  "export.rangeNotContiguous": { class: "act", reason: "a take or a readback, not the document" },
  "export.recordingSourceFrameMismatch": { class: "act", reason: "a take or a readback, not the document" },
  "export.renderCancelled": { class: "act", reason: "a take or a readback, not the document" },
  "export.renderFailed": { class: "act", reason: "a take or a readback, not the document" },
  "export.renderInFlight": { class: "act", reason: "a take or a readback, not the document" },
  "export.renderRangeOutsideTimeline": { class: "act", reason: "a take or a readback, not the document" },
  "export.saveDestinationRequired": { class: "act", reason: "a take or a readback, not the document" },
  "export.saveDestinationUnavailable": { class: "act", reason: "a take or a readback, not the document" },
  "export.snapshotOversize": { class: "act", reason: "a take or a readback, not the document" },
  "export.writeFailed": { class: "act", reason: "a take or a readback, not the document" },
  "export/encoder-unavailable": { class: "act", reason: "a take or a readback, not the document" },
  "export/live-read-too-large": { class: "act", reason: "a take or a readback, not the document" },
  "export/malformed-readback": { class: "act", reason: "a take or a readback, not the document" },
  "export/readback-during-playback": { class: "act", reason: "a take or a readback, not the document" },
  "export/recording-backlog": { class: "act", reason: "a take or a readback, not the document" },
  "export/recording-duplicate-frame": { class: "act", reason: "a take or a readback, not the document" },
  "export/recording-failed": { class: "act", reason: "a take or a readback, not the document" },
  "export/recording-frame-gap": { class: "act", reason: "a take or a readback, not the document" },
  "export/recording-out-of-order": { class: "act", reason: "a take or a readback, not the document" },
  "export/region-out-of-bounds": { class: "act", reason: "a take or a readback, not the document" },
  "export/unknown-output": { class: "act", reason: "a take or a readback, not the document" },
  "export/unsupported-format": { class: "act", reason: "a take or a readback, not the document" },
  "fixture.noRename": { class: "act", reason: "a test fixture's surface" },
  "gpu.unavailable": { class: "elsewhereHost", reason: "this session has no GPU device" },
  "gridWarp.folded": { class: "degraded", reason: "the grid folds over itself at these values: transparent, and said" },
  "gridWarp.line.axis": { class: "act", reason: "a Grid Warp line command's input" },
  "gridWarp.line.driven": { class: "act", reason: "a Grid Warp line command's input" },
  "gridWarp.line.exists": { class: "act", reason: "a Grid Warp line command's input" },
  "gridWarp.line.max": { class: "act", reason: "a Grid Warp line command's input" },
  "gridWarp.line.min": { class: "act", reason: "a Grid Warp line command's input" },
  "gridWarp.line.missing": { class: "act", reason: "a Grid Warp line command's input" },
  "gridWarp.line.outside": { class: "act", reason: "a Grid Warp line command's input" },
  "gridWarp.node.missing": { class: "act", reason: "a Grid Warp line command's input" },
  "gridWarp.node.type": { class: "act", reason: "a Grid Warp line command's input" },
  "group.duplicate": { class: "act", reason: "the patch operation's input" },
  "group.missing": { class: "act", reason: "the patch operation's input" },
  "help.noSurface": { class: "act", reason: "an editor command with nothing to act on" },
  "history.blocked": { class: "act", reason: "an editor command with nothing to act on" },
  "history.dryRun": { class: "act", reason: "an editor command with nothing to act on" },
  "history.empty": { class: "act", reason: "an editor command with nothing to act on" },
  "history.integrity": { class: "act", reason: "an editor command with nothing to act on" },
  "inspect.noPipelineSurface": { class: "act", reason: "an editor command with nothing to act on" },
  "inspect.noSurface": { class: "act", reason: "an editor command with nothing to act on" },
  "inspect.noTarget": { class: "act", reason: "an editor command with nothing to act on" },
  "inspect.unknownNode": { class: "act", reason: "an editor command with nothing to act on" },
  "laser.armed": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "laser.disarmed": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "laser.emission.blocked": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "laser.helper.absent": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "laser.source.missing": { class: "notYet", reason: "a Laser Out with no path wired yet" },
  "layout.alreadyTidy": { class: "act", reason: "an editor command with nothing to act on" },
  "layout.empty": { class: "act", reason: "an editor command with nothing to act on" },
  "layout.noShell": { class: "act", reason: "an editor command with nothing to act on" },
  "layout.unknownNodes": { class: "act", reason: "an editor command with nothing to act on" },
  "library.badPosition": { class: "act", reason: "an editor command with nothing to act on" },
  "library.noSurface": { class: "act", reason: "an editor command with nothing to act on" },
  "library.notOpened": { class: "act", reason: "an editor command with nothing to act on" },
  "mcp/bridge": { class: "act", reason: "the MCP server's own state" },
  "mcp/export-ungranted": { class: "act", reason: "the MCP server's own state" },
  "mcp/no-gpu": { class: "act", reason: "the MCP server's own state" },
  "media.connecting": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "media.notLoaded": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "media.playback": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "media.screenCapture": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "media.unavailable": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "mesh.component": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "mesh.decode": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "mesh.empty": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "mesh.note": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "mesh.read": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "native.input": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "native.output": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "node.ambiguous": { class: "act", reason: "the patch operation's input" },
  "node.camera.reference": { class: "notYet", reason: "a camera name no camera payload arrived for" },
  "node.channelMask.boundaryMissing": { class: "build", reason: "the compiler's own channel boundary has nothing to write" },
  "node.channelMask.invalid": { class: "act", reason: "the patch operation's input" },
  "node.channelMask.notComponent": { class: "act", reason: "the patch operation's input" },
  "node.channelMask.unsupported": { class: "never", reason: "Processing Channels on a node with no texture to process" },
  "node.channelMask.unwritten": { class: "build", reason: "a node definition emitted no pass for a processed output" },
  "node.compile.historyUnavailable": { class: "never", local: true, reason: "a static tap deeper than the ring ever holds" },
  "node.compile.missingResource": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "build"] }, reason: "an unwired input, or the compiler handing a definition no resource" },
  "node.compile.tapClamped": { class: "degraded", reason: "a tap past the history is clamped to the oldest frame held" },
  "node.compile.tooManyInputs": { class: "never", reason: "more wires than the node folds" },
  "node.customWgsl.module": { class: "notYet", splits: { task: "T1641b", holds: ["never", "notYet"] }, reason: "a module the source asks for that does not exist, or an input it reads with no wire" },
  "node.customWgsl.params": { class: "never", reason: "a Params field named after one of the node's own keys" },
  "node.customWgsl.viewCamera": { class: "degraded", reason: "a half-declared view camera: the picture renders, the viewport is not offered" },
  "node.duplicate": { class: "act", reason: "the patch operation's input" },
  "node.emptyLabel": { class: "act", reason: "the patch operation's input" },
  "node.format.invalid": { class: "act", reason: "the patch operation's input" },
  "node.label.empty": { class: "act", reason: "the patch operation's input" },
  "node.label.tooLong": { class: "act", reason: "the patch operation's input" },
  "node.materialWgsl.params": { class: "never", reason: "a Params field named after one of the material's own keys" },
  "node.materialWgsl.source": { class: "never", reason: "material source that breaks the surface contract" },
  "node.mesh.clip": { class: "never", reason: "a clip on a selection with no joints" },
  "node.mesh.lamps": { class: "never", reason: "more lamp groups than have a gain" },
  "node.mesh.size": { class: "elsewhereHost", reason: "past the device's storage binding baseline" },
  "node.missing": { class: "act", reason: "the patch operation's input" },
  "node.name.kind": { class: "act", reason: "the patch operation's input" },
  "node.name.kindMissing": { class: "act", reason: "the patch operation's input" },
  "node.name.referencesRewritten": { class: "act", reason: "the patch operation's input" },
  "node.name.stranded": { class: "act", reason: "the patch operation's input" },
  "node.nameTaken": { class: "never", reason: "two nodes may not share a name" },
  "node.notShaderAuthorable": { class: "act", reason: "the patch operation's input" },
  "node.parameter.default": { class: "build", reason: "a node definition the registry refuses at boot" },
  "node.parameter.map": { class: "notYet", splits: { task: "T1641b", holds: ["never", "notYet"] }, reason: "a map the node cannot honour, or whose attribute the upstream does not carry" },
  "node.parameter.pulse": { class: "build", reason: "a node definition the registry refuses at boot" },
  "node.points.attributes": { class: "never", reason: "attributes text that does not read" },
  "node.points.capacity": { class: "elsewhereHost", splits: { task: "T1641b", holds: ["elsewhereHost", "never"] }, reason: "past the device's storage baseline, or the build's point limit" },
  "node.points.clock": { class: "advice", reason: "a kernel reading the timeline clock: it takes effect as stored" },
  "node.points.curve": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "never"] }, reason: "a control set the basis cannot run, or control points that do not read" },
  "node.points.curveFrames": { class: "notYet", splits: { task: "T1641b", holds: ["never", "notYet"] }, reason: "nothing to publish, or a seed the upstream does not carry" },
  "node.points.edge": { class: "notYet", reason: "a pointset input whose producer published nothing" },
  "node.points.gather": { class: "elsewhereHost", splits: { task: "T1641b", holds: ["notYet", "never", "elsewhereHost"] }, reason: "links or an attribute that do not fit, or storage past the baseline" },
  "node.points.group": { class: "notYet", splits: { task: "T1641b", holds: ["never", "notYet"] }, reason: "a group predicate reading nothing, or an attribute the upstream lacks" },
  "node.points.input": { class: "never", reason: "an incoming pointset this kernel cannot take as it is" },
  "node.points.kernel": { class: "elsewhereHost", splits: { task: "T1641b", holds: ["never", "notYet", "elsewhereHost"] }, reason: "kernel source that breaks the contract, lacks its upstream, or passes a device limit" },
  "node.points.lifecycle": { class: "build", reason: "not reachable from a document" },
  "node.points.module": { class: "never", reason: "a module the kernel asks for that does not exist, or a name it declares twice" },
  "node.points.params": { class: "never", reason: "a Params field named after one of the kernel's own keys" },
  "node.points.range": { class: "elsewhereHost", splits: { task: "T1641b", holds: ["notYet", "never", "elsewhereHost"] }, reason: "an attribute or component the points do not have, or storage past the baseline" },
  "node.points.resample": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "never"] }, reason: "an upstream the walk cannot follow, or a rule its padding breaks" },
  "node.points.rope": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "never"] }, reason: "strands the solver cannot walk" },
  "node.points.source": { class: "build", reason: "not reachable from a document" },
  "node.points.spawn": { class: "never", reason: "spawn source that breaks the spawn contract" },
  "node.points.strips": { class: "notYet", reason: "an upstream that claims no strips yet" },
  "node.points.sweep": { class: "elsewhereHost", splits: { task: "T1641b", holds: ["notYet", "elsewhereHost"] }, reason: "a path or profile the sweep cannot follow yet, or past a device limit" },
  "node.points.transform": { class: "elsewhereHost", reason: "storage past the device's baseline" },
  "node.port": { class: "build", reason: "a node definition the registry refuses at boot" },
  "node.port.duplicate": { class: "build", reason: "a node definition the registry refuses at boot" },
  "node.position": { class: "act", reason: "the patch operation's input" },
  "node.resolution.invalid": { class: "act", reason: "the patch operation's input" },
  "node.scene.camera": { class: "notYet", reason: "no camera named yet" },
  "node.scene.empty": { class: "notYet", reason: "no geometry named yet" },
  "node.scene.endpoint": { class: "notYet", reason: "beam mode with no endpoint attribute it can read yet" },
  "node.scene.environment": { class: "notYet", reason: "Show Environment with nothing wired: the Background colour stands in" },
  "node.scene.geometry": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "never"] }, reason: "points that carry no payload yet, or a mode a counted set cannot draw in" },
  "node.scene.glass": { class: "never", reason: "glass on a draw this build does not refract" },
  "node.scene.group": { class: "never", reason: "a group predicate on a surface" },
  "node.scene.instanceAttribute": { class: "notYet", splits: { task: "T1641b", holds: ["never", "notYet"] }, reason: "an instance binding that does not read, or an attribute the points lack" },
  "node.scene.lightCapacity": { class: "never", reason: "more light points than a Render lights from" },
  "node.scene.lightDepth": { class: "notYet", reason: "Light Depth Output with no light that casts yet" },
  "node.scene.lightDraw": { class: "degraded", reason: "a draw the lights of a pointset do not reach: unlit by them, and said" },
  "node.scene.lightPoints": { class: "notYet", reason: "a Light in Points mode with no pointset or position to stand at yet" },
  "node.scene.lightSources": { class: "never", reason: "more Lights in Points mode than a Render gathers" },
  "node.scene.lightSpot": { class: "degraded", reason: "a Spot in Single mode shines as a point light, and says so" },
  "node.scene.maps": { class: "never", reason: "texture maps on a draw that has no uv" },
  "node.scene.material": { class: "never", reason: "a Material · WGSL on a draw it does not run on" },
  "node.scene.override": { class: "never", reason: "a material override that does not read, or names nothing the material has" },
  "node.scene.reference": { class: "never", reason: "a name that resolves to a node of the wrong kind" },
  "node.scene.shadowCasters": { class: "advice", reason: "a light that casts nothing in this Render may cast in another" },
  "node.scene.shadowOnly": { class: "never", reason: "Shadow Only on a geometry that casts no shadow" },
  "node.scene.shape": { class: "elsewhereHost", splits: { task: "T1641b", holds: ["notYet", "elsewhereHost"] }, reason: "no mesh on Shape Mesh yet, or storage past the baseline" },
  "node.scene.textureBudget": { class: "elsewhereHost", reason: "past the device baseline of sampled textures" },
  "node.scene.topology": { class: "notYet", reason: "a surface whose points carry no grid or mesh topology yet" },
  "node.scene.unlit": { class: "degraded", reason: "a lit material with no lights named: the ambient floor stands in" },
  "node.size.invalid": { class: "act", reason: "the patch operation's input" },
  "node.stateful.inconsistent": { class: "build", reason: "a node definition the registry refuses at boot" },
  "node.stateful.undeclared": { class: "build", reason: "a node definition the registry refuses at boot" },
  "node.surface.topology": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "never"] }, reason: "an upstream with no grid yet, or a claim that does not match its points" },
  "node.temporal.port": { class: "build", reason: "a node definition the registry refuses at boot" },
  "node.type": { class: "build", reason: "a node definition the registry refuses at boot" },
  "node.type.duplicate": { class: "build", reason: "a node definition the registry refuses at boot" },
  "node.ui.type": { class: "act", reason: "the patch operation's input" },
  "node.ui.unknown": { class: "act", reason: "the patch operation's input" },
  "node.unknown": { class: "act", reason: "the patch operation's input" },
  "node.unknownType": { class: "elsewhereBuild", reason: "a node type this build does not have" },
  "node.valueExpression.syntax": { class: "never", reason: "a Value Expression statement that does not parse" },
  "node.version": { class: "build", reason: "a node definition the registry refuses at boot" },
  "osc.helper": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "osc.send": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "output.notTexture": { class: "act", reason: "the agent tool's input or surface" },
  "output.toneMapInactive": { class: "degraded", reason: "a tone map the project's display transform does not apply" },
  "output.unknownDefinition": { class: "act", reason: "the agent tool's input or surface" },
  "output.unknownNode": { class: "act", reason: "the agent tool's input or surface" },
  "output.unknownPort": { class: "act", reason: "the agent tool's input or surface" },
  "parameter.bind.empty": { class: "never", reason: "a bind to nothing" },
  "parameter.bind.type": { class: "never", local: true, reason: "a bind to a parameter of another type: no value of it fits" },
  "parameter.bind.unavailable": { class: "build", reason: "this resolution was handed no parent scope or sibling schema" },
  "parameter.bind.unreadable": { class: "never", local: true, reason: "a bind that names no parameter of its node, no component of it, itself, or no published parent key" },
  "parameter.bind.value": { class: "degraded", reason: "the bound value is past this parameter's limit or options: the stored value stands in" },
  "parameter.bindCycle": { class: "never", reason: "a bind chain that returns to itself" },
  "parameter.channels.unavailable": { class: "elsewhereHost", reason: "this process has no channel resolver" },
  "parameter.clipboard.empty": { class: "act", reason: "a parameter command's input" },
  "parameter.clipboard.unreadable": { class: "act", reason: "a parameter command's input" },
  "parameter.driven": { class: "notYet", reason: "a retired driven slot whose channel is not attached" },
  "parameter.driven.clamped": { class: "degraded", reason: "the channel overshot a declared limit: the limit is in effect" },
  "parameter.driven.empty": { class: "never", reason: "a driven slot naming no channel" },
  "parameter.enum": { class: "never", reason: "an option the parameter does not have" },
  "parameter.expression.clamped": { class: "degraded", reason: "the expression overshot a declared limit: the limit is in effect" },
  "parameter.expression.name": { class: "never", local: true, reason: "a bare name that is not a clock: nothing supplies it" },
  "parameter.expression.syntax": { class: "never", local: true, reason: "an expression that does not parse: a token, a function the grammar lacks, an argument count" },
  "parameter.expression.type": { class: "never", local: true, reason: "an expression on a parameter type that takes none" },
  "parameter.expression.value": { class: "degraded", reason: "arithmetic with no finite answer at this frame: the stored value stands in" },
  "parameter.map.empty": { class: "never", reason: "a map naming no attribute" },
  "parameter.mode.payload": { class: "act", reason: "a parameter command's input" },
  "parameter.mode.retired": { class: "act", reason: "a parameter command's input" },
  "parameter.multipleOwners": { class: "act", reason: "a parameter command's input" },
  "parameter.node": { class: "act", reason: "a parameter command's input" },
  "parameter.paste.channelNoReading": { class: "act", reason: "a parameter command's input" },
  "parameter.paste.nameNotText": { class: "act", reason: "a parameter command's input" },
  "parameter.paste.noBinding": { class: "act", reason: "a parameter command's input" },
  "parameter.paste.noName": { class: "act", reason: "a parameter command's input" },
  "parameter.paste.noReference": { class: "act", reason: "a parameter command's input" },
  "parameter.paste.shape": { class: "act", reason: "a parameter command's input" },
  "parameter.paste.textIsReference": { class: "act", reason: "a parameter command's input" },
  "parameter.pulse.failed": { class: "act", reason: "a parameter command's input" },
  "parameter.pulse.node": { class: "act", reason: "a parameter command's input" },
  "parameter.pulse.stored": { class: "never", reason: "a document may not hold an armed pulse" },
  "parameter.pulse.type": { class: "act", reason: "a parameter command's input" },
  "parameter.pulse.unregistered": { class: "act", reason: "a parameter command's input" },
  "parameter.range": { class: "never", reason: "a value past a declared limit is replaced by the default" },
  "parameter.reference.ambiguous": { class: "never", local: true, reason: "an instance publishes that channel on more than one output" },
  "parameter.reference.channel": { class: "notYet", reason: "the target publishes no such channel right now" },
  "parameter.reference.node": { class: "notYet", reason: "no node has that name yet" },
  "parameter.reference.self": { class: "act", reason: "a parameter command's input" },
  "parameter.reference.unavailable": { class: "elsewhereHost", reason: "this read has no graph to resolve op() in" },
  "parameter.reference.unknownType": { class: "elsewhereBuild", reason: "the target's type is not one this build has" },
  "parameter.reference.unnamed": { class: "act", reason: "a parameter command's input" },
  "parameter.reference.unreadable": { class: "never", local: true, reason: "a path no reader accepts, a parameter the target does not declare, or a value that is not a number" },
  "parameter.reference.upstream": { class: "notYet", reason: "the parameter read carries a finding of its own, and clears with it" },
  "parameter.remove.absent": { class: "act", reason: "a parameter command's input" },
  "parameter.remove.declared": { class: "act", reason: "a parameter command's input" },
  "parameter.remove.none": { class: "act", reason: "a parameter command's input" },
  "parameter.referenceCycle": { class: "never", reason: "an op() chain that returns to itself" },
  "parameter.reset.cleared": { class: "act", reason: "a parameter command's input" },
  "parameter.revert.created": { class: "act", reason: "a parameter command's input" },
  "parameter.revert.unopened": { class: "act", reason: "a parameter command's input" },
  "parameter.slot.empty": { class: "never", local: true, reason: "a mode with no payload" },
  "parameter.slot.shape": { class: "never", reason: "a payload stored under another mode's binding" },
  "parameter.slot.unknown": { class: "elsewhereBuild", reason: "a mode this build does not have" },
  "parameter.stops.count": { class: "never", reason: "more stops than the parameter carries" },
  "parameter.type": { class: "never", reason: "a value of the wrong shape is replaced by the default" },
  "parameter.undefined": { class: "never", reason: "a key written as undefined" },
  "parameter.unknown": { class: "never", local: true, reason: "a key the node does not declare: nothing reads it, at the write or at rest" },
  "patch.conflict": { class: "act", reason: "the patch operation's input" },
  "patch.dryRun": { class: "act", reason: "the patch operation's input" },
  "patch.duplicateRef": { class: "act", reason: "the patch operation's input" },
  "patch.malformed": { class: "act", reason: "the patch operation's input" },
  "patch.staleBase": { class: "act", reason: "the patch operation's input" },
  "patch.unresolvedRef": { class: "act", reason: "the patch operation's input" },
  "perform.noWindowNode": { class: "act", reason: "an editor command with nothing to act on" },
  "perform.popupBlocked": { class: "act", reason: "an editor command with nothing to act on" },
  "perform.unavailable": { class: "act", reason: "an editor command with nothing to act on" },
  "points.readFailed": { class: "act", reason: "the agent tool's input or surface" },
  "points.unavailable": { class: "act", reason: "the agent tool's input or surface" },
  "port.incompatible": { class: "never", reason: "two port types with no conversion between them" },
  "port.missing": { class: "never", reason: "a port the type does not declare" },
  "port.notVariadic": { class: "act", reason: "the patch operation's input" },
  "port.occupied": { class: "never", reason: "a second wire into a single input" },
  "port.sourceReference": { class: "act", reason: "the patch operation's input" },
  "preset.bank.inDefinition": { class: "act", reason: "a preset command's input" },
  "preset.bank.malformed": { class: "never", reason: "presets text that does not read" },
  "preset.bank.missing": { class: "act", reason: "a preset command's input" },
  "preset.bank.nested": { class: "act", reason: "a preset command's input" },
  "preset.bank.noCatalogue": { class: "elsewhereHost", reason: "this surface has no component catalogue" },
  "preset.bank.noPageBank": { class: "notYet", reason: "a component with no bank targeting parent yet" },
  "preset.bank.notInstalled": { class: "elsewhereBuild", reason: "an instance of a component that is not installed" },
  "preset.bank.type": { class: "act", reason: "a preset command's input" },
  "preset.bank.unknown": { class: "act", reason: "a preset command's input" },
  "preset.bank.unnamed": { class: "notYet", reason: "an instance with no name yet" },
  "preset.component.written": { class: "act", reason: "a preset command's input" },
  "preset.delete.cued": { class: "act", reason: "a preset command's input" },
  "preset.delete.recalled": { class: "act", reason: "a preset command's input" },
  "preset.delete.unknown": { class: "act", reason: "a preset command's input" },
  "preset.move.clash": { class: "act", reason: "a preset command's input" },
  "preset.move.noInstance": { class: "act", reason: "a preset command's input" },
  "preset.move.notOneLook": { class: "act", reason: "a preset command's input" },
  "preset.name": { class: "act", reason: "a preset command's input" },
  "preset.on.missing": { class: "notYet", reason: "on/off for a Layer that is not in the document" },
  "preset.on.notLayer": { class: "never", local: true, reason: "on/off for a node that is not a Layer" },
  "preset.page.notParent": { class: "never", local: true, reason: "a page bank's preset holding values for a name other than parent" },
  "preset.page.on": { class: "never", local: true, reason: "a page bank's preset carrying on/off: it reaches only its page" },
  "preset.page.recalls": { class: "never", local: true, reason: "a page bank's preset carrying recalls: it reaches only its page" },
  "preset.recall.componentOverride": { class: "degraded", reason: "written, and one channel is still overridden by its own slot" },
  "preset.recall.cycle": { class: "never", reason: "recalls that go round in a circle" },
  "preset.recall.depth": { class: "never", reason: "recalls nested past the limit" },
  "preset.recall.morph": { class: "act", reason: "a preset command's input" },
  "preset.recall.morphDropped": { class: "degraded", reason: "the oldest fade was dropped: its keys jumped" },
  "preset.recall.morphUnavailable": { class: "elsewhereHost", reason: "no frame clock here, so the morph is a cut" },
  "preset.recall.noName": { class: "act", reason: "a preset command's input" },
  "preset.recall.nothing": { class: "act", reason: "a preset command's input" },
  "preset.recall.unknown": { class: "act", reason: "a preset command's input" },
  "preset.recalls.malformed": { class: "never", local: true, reason: "a shot recalls a bank whose text does not read" },
  "preset.recalls.missing": { class: "notYet", reason: "a shot recalls a bank that is not in the document" },
  "preset.recalls.noCatalogue": { class: "elsewhereHost", reason: "this surface has no component catalogue" },
  "preset.recalls.noPageBank": { class: "notYet", reason: "a component with no bank targeting parent yet" },
  "preset.recalls.notInstalled": { class: "elsewhereBuild", reason: "an instance of a component that is not installed" },
  "preset.recalls.type": { class: "never", local: true, reason: "a shot recalls a node that is not a bank" },
  "preset.recalls.unknown": { class: "notYet", reason: "a shot recalls a preset its bank does not hold" },
  "preset.store.noTargets": { class: "notYet", reason: "a bank with no targets yet" },
  "preset.store.nothing": { class: "act", reason: "a preset command's input" },
  "preset.target.default": { class: "never", local: true, reason: "a stored value for a control's default, which a recall never writes" },
  "preset.target.key": { class: "never", local: true, reason: "a target key the node does not declare, or that holds no value" },
  "preset.target.missing": { class: "notYet", reason: "a target that is not in the document" },
  "preset.target.pulse": { class: "never", local: true, reason: "a stored value for a pulse, which fires and holds nothing" },
  "preset.target.self": { class: "never", local: true, reason: "a bank targeting itself" },
  "preset.target.unknownType": { class: "elsewhereBuild", reason: "a target of a node type this build does not have" },
  "preset.value.invalid": { class: "never", local: true, reason: "a stored value the node's parameter refuses" },
  "preview.noTarget": { class: "act", reason: "the agent tool's input or surface" },
  "preview.statsFailed": { class: "act", reason: "the agent tool's input or surface" },
  "preview.statsUnavailable": { class: "act", reason: "the agent tool's input or surface" },
  "preview.unknownLens": { class: "act", reason: "the agent tool's input or surface" },
  "preview.unknownNode": { class: "act", reason: "the agent tool's input or surface" },
  "project.asset.unresolved": { class: "elsewhereHost", reason: "a session's file that is gone after a reload" },
  "project.autosave.failed": { class: "act", reason: "opening, saving or autosaving, not what the document holds" },
  "project.autosave.unavailable": { class: "act", reason: "opening, saving or autosaving, not what the document holds" },
  "project.components.invalid": { class: "elsewhereBuild", splits: { task: "T1641b", holds: ["never", "elsewhereBuild"] }, reason: "a component library this build cannot read" },
  "project.components.rejected": { class: "never", reason: "a component definition the registry refuses" },
  "project.limit.buffer": { class: "build", reason: "a limit check no product path calls" },
  "project.limit.dispatch": { class: "build", reason: "a limit check no product path calls" },
  "project.limit.memoryBudget": { class: "advice", reason: "over the project's own budget: reported, nothing altered" },
  "project.limit.nodeResolution": { class: "degraded", reason: "a node resolution clamped to the limit" },
  "project.limit.preview": { class: "degraded", reason: "the preview edge clamped to the limit" },
  "project.limit.resolution": { class: "degraded", reason: "the output resolution clamped to the limit" },
  "project.limit.settings": { class: "degraded", reason: "a project limit clamped to the hard limit" },
  "project.migration.applied": { class: "degraded", reason: "the file was upgraded, and says so" },
  "project.migration.backwards": { class: "build", reason: "the build's own migration ladder" },
  "project.migration.duplicate": { class: "build", reason: "the build's own migration ladder" },
  "project.migration.failed": { class: "build", reason: "the build's own migration ladder" },
  "project.migration.malformed": { class: "build", reason: "the build's own migration ladder" },
  "project.migration.missing": { class: "build", reason: "the build's own migration ladder" },
  "project.migration.noVersion": { class: "never", reason: "a file with no schema version does not open" },
  "project.new.unsupported": { class: "act", reason: "opening, saving or autosaving, not what the document holds" },
  "project.noSurface": { class: "act", reason: "opening, saving or autosaving, not what the document holds" },
  "project.node.migrated": { class: "degraded", reason: "a node was migrated, and says what moved" },
  "project.node.migrationFailed": { class: "build", reason: "a node migration threw" },
  "project.node.newerVersion": { class: "elsewhereBuild", reason: "a newer build's node: kept and written back" },
  "project.node.noMigration": { class: "degraded", reason: "it runs on the current definition: nothing says what moved" },
  "project.node.unknownType": { class: "elsewhereBuild", reason: "a node type this build does not have: kept as a placeholder" },
  "project.open.failed": { class: "act", reason: "opening, saving or autosaving, not what the document holds" },
  "project.open.rejected": { class: "act", reason: "opening, saving or autosaving, not what the document holds" },
  "project.parameter.unknownKind": { class: "elsewhereBuild", reason: "a value shape this build does not read: kept and written back" },
  "project.parse.invalidDocument": { class: "never", reason: "a file that is not a project document does not open" },
  "project.parse.invalidJson": { class: "never", reason: "a file that is not JSON does not open" },
  "project.parse.notAnObject": { class: "never", reason: "a file that holds no project object does not open" },
  "project.save.failed": { class: "act", reason: "opening, saving or autosaving, not what the document holds" },
  "project.schema.newer": { class: "elsewhereBuild", reason: "a newer build's file" },
  "project.settings.invalid": { class: "act", reason: "opening, saving or autosaving, not what the document holds" },
  "proposal.unknown": { class: "act", reason: "the agent tool's input or surface" },
  "ramp.stops.capped": { class: "degraded", reason: "the first sixteen stops render" },
  "ramp.stops.unordered": { class: "advice", reason: "it renders exactly as stored" },
  "rename.noTarget": { class: "act", reason: "an editor command with nothing to act on" },
  "rename.unknownNode": { class: "act", reason: "an editor command with nothing to act on" },
  "requirement.unmet": { class: "elsewhereHost", reason: "this machine cannot run the node" },
  "runtime.noBackend": { class: "act", reason: "an editor command with nothing to act on" },
  "runtime.noFeedback": { class: "act", reason: "an editor command with nothing to act on" },
  "selection.empty": { class: "act", reason: "an editor command with nothing to act on" },
  "selection.noCanvas": { class: "act", reason: "an editor command with nothing to act on" },
  "settings.noSurface": { class: "act", reason: "an editor command with nothing to act on" },
  "shader/compile-error": { class: "never", reason: "a stored shader the device refuses" },
  "shader/compile-failed": { class: "build", reason: "the shader pane's compile pipeline failed" },
  "shader/compile-info": { class: "advice", reason: "the device's remark on a shader that compiled" },
  "shader/compile-warning": { class: "advice", reason: "the device's warning on a shader that compiled" },
  "shader/output-stale": { class: "act", reason: "the shader pane's state" },
  "sideEffect.blocked": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "tool.awaitingApproval": { class: "act", reason: "the agent tool's input or surface" },
  "tool.dryRun": { class: "act", reason: "the agent tool's input or surface" },
  "tool.failed": { class: "act", reason: "the agent tool's input or surface" },
  "tool.input": { class: "act", reason: "the agent tool's input or surface" },
  "tool.partialSource": { class: "act", reason: "the agent tool's input or surface" },
  "tool.truncated": { class: "act", reason: "the agent tool's input or surface" },
  "tool.unavailable": { class: "act", reason: "the agent tool's input or surface" },
  "tool.unavailableCommand": { class: "act", reason: "the agent tool's input or surface" },
  "tool.unavailablePort": { class: "act", reason: "the agent tool's input or surface" },
  "tool.unavailableQuery": { class: "act", reason: "the agent tool's input or surface" },
  "tool.unknown": { class: "act", reason: "the agent tool's input or surface" },
  "transaction.dryRun": { class: "act", reason: "an editor command with nothing to act on" },
  "transaction.empty": { class: "act", reason: "an editor command with nothing to act on" },
  "transaction.partialRevert": { class: "act", reason: "an editor command with nothing to act on" },
  "transaction.unknown": { class: "act", reason: "an editor command with nothing to act on" },
  "transport.noLoop": { class: "act", reason: "an editor command with nothing to act on" },
  "transport.seekLimit": { class: "act", reason: "an editor command with nothing to act on" },
  "transport.seekRange": { class: "act", reason: "an editor command with nothing to act on" },
  "valueGraph.channelShadowed": { class: "degraded", reason: "one of two same-named channels wins" },
  "valueGraph.cycle": { class: "never", reason: "a loop through a wire and an op() reference: its members emit nothing" },
  "valueGraph.evaluate": { class: "build", reason: "a node definition's evaluate threw" },
  "view.fullscreenRefused": { class: "act", reason: "an editor command with nothing to act on" },
  "view.fullscreenUnsupported": { class: "act", reason: "an editor command with nothing to act on" },
  "view.noCanvas": { class: "act", reason: "an editor command with nothing to act on" },
  "view.noFullscreenSurface": { class: "act", reason: "an editor command with nothing to act on" },
  "view.nothingToFrame": { class: "act", reason: "an editor command with nothing to act on" },
  "viewer.flyDirection": { class: "act", reason: "an editor command with nothing to act on" },
  "viewer.noNode": { class: "act", reason: "an editor command with nothing to act on" },
  "viewer.noOrbit": { class: "act", reason: "an editor command with nothing to act on" },
  "viewer.noOutput": { class: "act", reason: "an editor command with nothing to act on" },
  "viewer.noPane": { class: "act", reason: "an editor command with nothing to act on" },
  "vision.helper.absent": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "vision.native.refused": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "vision.native.retirement": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "vision.native.starting": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "vision.refused": { class: "elsewhereHost", reason: "this session's device, helper or file" },
  "wgsl/compile": { class: "advice", splits: { task: "T1641b", holds: ["never", "advice"] }, reason: "the device's own message for a stored shader: an error, or a remark" },
};

/**
 * The one answer to "what class is this code". Total: a code with no row is `unclassified`,
 * which the gate keeps from happening for any code the source tree can be seen to emit.
 */
export function diagnosticClass(code: string): DiagnosticClass | "unclassified" {
  return Object.hasOwn(DIAGNOSTIC_CLASSES, code) ? (DIAGNOSTIC_CLASSES[code] as DiagnosticClassRow).class : "unclassified";
}

/**
 * Does an ERROR of this code leave the rest of the plan usable? True for the rows marked
 * `local`. A code with no row answers false: an error nobody classed withdraws the plan, as
 * every error did before the table.
 */
export function leavesPlanUsable(code: string): boolean {
  return Object.hasOwn(DIAGNOSTIC_CLASSES, code) && (DIAGNOSTIC_CLASSES[code] as DiagnosticClassRow).local === true;
}

/**
 * What a FINAL render stops on, as one question for every guard that asks it: an error; a
 * finding that can never take effect; one that is still waiting, because a final render has
 * no "later"; and a code with no row, which nobody has judged. A guard that named codes
 * instead went blind the day a code was split (`parameter.expression`, slice 1).
 */
export function stopsFinalRender(diagnostic: { readonly severity: string; readonly code: string }): boolean {
  if (diagnostic.severity === "error") return true;
  const found = diagnosticClass(diagnostic.code);
  return found === "never" || found === "notYet" || found === "unclassified";
}
