/**
 * T1641b — THE CLASS OF EVERY DIAGNOSTIC CODE.
 *
 * A `RuntimeDiagnostic` carries a `code`, and until this file there was no list of them and
 * no statement of what one MEANS for the thing it is about. Two defects shipped through that
 * gap in one day (§B262, §B264): a stored expression that could never be evaluated and a
 * stored value under a key nothing reads were each a WARNING, of the same weight as a
 * clamped slider, and the picture looked plausible. So every code has a row here that says
 * which of these it is:
 *
 *  - `never`: as stored it can never do what it says. It cannot be evaluated, nothing reads
 *    it, or no write path would have accepted it. Only changing the stored thing fixes it.
 *  - `notYet`: it takes effect the moment something else arrives (a node of that name, a
 *    wire, an attribute upstream, a channel, a file). Legitimate while editing.
 *  - `elsewhereBuild`: true of this build only: a newer build, or an installed component, has it.
 *  - `elsewhereHost`: true of this device, process or session only.
 *  - `degraded`: it takes effect, not as written, and the diagnostic says what stands in.
 *  - `advice`: it takes effect exactly as stored, and the app has a remark.
 *  - `act`: about a command (its input, or a note on what it did), not about anything stored.
 *  - `build`: about this build's own definitions or an internal contract. Never a document's fault.
 *
 * `docs/never-effective-refusals-2026-10-06.md` holds the reading behind each row and the
 * rule this table is the first slice of.
 *
 * ## The table is total, in both directions
 *
 * `classes.test.ts` reads every diagnostic code out of the source tree and fails when a code
 * has no row here, and when a row names a code nothing emits any more. A new diagnostic
 * therefore chooses its class in the diff that adds it.
 *
 * WHY a code is of its class is one line a code in `class-reasons.ts`, held to this table in
 * both directions by the same gate. It is a file of its own because nothing in the product
 * shows a reason, and beside the classes it was half of what the app shipped of this module.
 *
 * ## One code, one class, with the debt written down
 *
 * A code means one class. The rows that carry `splits` do not: each is emitted today for
 * conditions of more than one class, listed in `holds`. Until T1641b splits such a code, its
 * `class` is the LEAST refusing of those it holds, so that reading this table refuses
 * nothing that was not refused before. The gate holds the list of them by name: it can only
 * get shorter, and a new code may not join it.
 *
 * ## Who reads it (T1641b)
 *
 * Slice 0 was the table and its gate. Slice 1 gave it its first product reader: the
 * compiler's `hasError` asks `leavesPlanUsable`, so a `never` finding marked `local` is
 * reported as an ERROR while the plan it sits in stays usable. `local` means the stored
 * thing is inert on its own: its stated fallback is in effect and the rest of the document
 * is whole. A document that rendered yesterday with a warning must not open black because
 * the report got louder. Every code that was a warning before the rule and is `never` under
 * it is `local`; a code that was an error before stays as it was. Slice 3 gave it the
 * rest: `documentFindings` classes everything a document at rest holds, the save by code
 * and the shipped-set gate refuse by class (`refusedAtCodeSave`), the app's save reports
 * what is `never`, and a strict headless render asks `stopsFinalRender` of every frame.
 */

export type DiagnosticClass = "never" | "notYet" | "elsewhereBuild" | "elsewhereHost" | "degraded" | "advice" | "act" | "build";

export interface DiagnosticClassRow {
  readonly class: DiagnosticClass;
  /** `never` only: the finding leaves the rest of the plan usable. */
  readonly local?: true;
  /** Debt: the classes this one code is emitted for today, and the task that splits it. */
  readonly splits?: { readonly task: string; readonly holds: readonly DiagnosticClass[] };
}

export const DIAGNOSTIC_CLASSES: Readonly<Record<string, DiagnosticClassRow>> = {
  "animation/structuralDrift": { class: "build" },
  "asset.badData": { class: "act" },
  "asset.parameterUnresolved": { class: "act" },
  "asset.reference.error": { class: "elsewhereHost" },
  "asset.reference.invalid": { class: "never" },
  "asset.reference.missing": { class: "elsewhereHost" },
  "asset.reference.pending": { class: "elsewhereHost" },
  "asset.reference.permission": { class: "elsewhereHost" },
  "audio.noSession": { class: "act" },
  "audio.noSource": { class: "act" },
  "audio.nothingRecorded": { class: "act" },
  "audio.track.fps": { class: "act" },
  "audio.track.frames": { class: "act" },
  "audio.track.malformed": { class: "act" },
  "audio.track.provenance": { class: "act" },
  "audio.track.version": { class: "act" },
  "audio.trackWriteFailed": { class: "act" },
  "backend/capability-below-baseline": { class: "elsewhereHost" },
  "backend/compile-failed": { class: "never" },
  "backend/device-lost": { class: "elsewhereHost" },
  "backend/device-restored": { class: "elsewhereHost" },
  "backend/frame-error": { class: "build" },
  "backend/init-failed": { class: "elsewhereHost" },
  "backend/not-initialized": { class: "elsewhereHost" },
  "backend/plan-invalid": { class: "build" },
  "backend/plan-not-current": { class: "build" },
  "backend/present-failed": { class: "elsewhereHost" },
  "backend/rebuild-failed": { class: "build" },
  "backend/recover-failed": { class: "build" },
  "backend/resource-limit": { class: "elsewhereHost" },
  "backend/shader-validation-unavailable": { class: "elsewhereHost" },
  "backend/submission-halted": { class: "build" },
  "backend/temporal-reset": { class: "elsewhereHost" },
  "backend/timestamp-unavailable": { class: "elsewhereHost" },
  "backend/unknown-output": { class: "build" },
  "backend/unknown-pass": { class: "build" },
  "backend/unknown-resource": { class: "build" },
  "bridge/detached": { class: "act" },
  "bridge/devices-only": { class: "act" },
  "bridge/not-the-owner": { class: "act" },
  "bridge/page-error": { class: "act" },
  "bridge/proxy-lost": { class: "act" },
  "bridge/timeout": { class: "act" },
  "capability.denied": { class: "act" },
  "capability.unobtainable": { class: "act" },
  "channel.reference.unnamed": { class: "act" },
  "clipboard.empty": { class: "act" },
  "clipboard.foreign": { class: "act" },
  "command.failed": { class: "act" },
  "command.input": { class: "act" },
  "compile.noCompiler": { class: "act" },
  "compile.noDevice": { class: "act" },
  "compiler.crashed": { class: "build" },
  "compiler/binding-budget": { class: "elsewhereHost" },
  "compiler/binding-unfilterable": { class: "elsewhereHost" },
  "compiler/bypass-incoherent": { class: "degraded" },
  "compiler/camera-preview-ambiguous": { class: "advice" },
  "compiler/color-space-mismatch": { class: "advice" },
  "compiler/component-id-collision": { class: "never" },
  "compiler/component-missing": { class: "elsewhereBuild" },
  "compiler/component-parameter-conflict": { class: "never", local: true },
  "compiler/component-port-unresolved": { class: "never" },
  "compiler/component-recursion": { class: "never" },
  "compiler/cycle": { class: "never" },
  "compiler/definition-version": { class: "degraded", splits: { task: "T1641b", holds: ["degraded", "elsewhereBuild"] } },
  "compiler/edge-endpoint-missing": { class: "elsewhereBuild", splits: { task: "T1641b", holds: ["never", "elsewhereBuild"] } },
  "compiler/format-depth-on-color": { class: "never" },
  "compiler/format-input-missing": { class: "degraded" },
  "compiler/format-no-fallback": { class: "elsewhereHost" },
  "compiler/format-unsupported": { class: "elsewhereHost" },
  "compiler/input-missing": { class: "notYet" },
  "compiler/memory-budget": { class: "advice" },
  "compiler/no-active-sinks": { class: "notYet" },
  "compiler/node-compile-failed": { class: "build" },
  "compiler/node-no-passes": { class: "build" },
  "compiler/pass-invalid": { class: "build" },
  "compiler/passthrough-unconnected": { class: "notYet" },
  "compiler/port-incompatible": { class: "never" },
  "compiler/port-missing": { class: "never" },
  "compiler/port-occupied": { class: "never" },
  "compiler/parent-reference-no-parent": { class: "never" },
  "compiler/parent-reference-unknown-key": { class: "never" },
  "compiler/reference-cross-scope": { class: "advice" },
  "compiler/resolution-clamped": { class: "degraded" },
  "compiler/resolution-custom": { class: "degraded" },
  "compiler/resolution-input-missing": { class: "degraded" },
  "compiler/resolution-parameter": { class: "degraded" },
  "compiler/scratch-invalid": { class: "build" },
  "compiler/sink-unknown": { class: "act" },
  "compiler/source-reference-ambiguous": { class: "never" },
  "compiler/source-reference-missing": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "never"] } },
  "compiler/substeps-refused": { class: "degraded" },
  "compiler/unknown-node-type": { class: "elsewhereBuild" },
  "compiler/wgsl-high-half-divide": { class: "advice" },
  "component.channelMaskTargetMissing": { class: "never" },
  "component.create.noCanvas": { class: "act" },
  "component.create.noSelection": { class: "act" },
  "component.detach.channelMask": { class: "degraded" },
  "component.detach.inexact": { class: "degraded" },
  "component.detach.instancePaths": { class: "never", local: true },
  "component.detach.nestedParentReads": { class: "degraded" },
  "component.detach.outerTarget": { class: "degraded" },
  "component.detach.overrideMissing": { class: "never", local: true },
  "component.detach.pageBank": { class: "degraded" },
  "component.detach.pageBankInert": { class: "never", local: true },
  "component.detach.parentValues": { class: "degraded" },
  "component.export.failed": { class: "act" },
  "component.export.input": { class: "act" },
  "component.export.missingDependency": { class: "act" },
  "component.export.noWriter": { class: "act" },
  "component.export.sessionAsset": { class: "act" },
  "component.id": { class: "never" },
  "component.import.input": { class: "act" },
  "component.import.malformed": { class: "act" },
  "component.import.missingDependency": { class: "act" },
  "component.import.noComponent": { class: "act" },
  "component.import.notAComponent": { class: "act" },
  "component.import.readFailed": { class: "act" },
  "component.import.renamed": { class: "degraded" },
  "component.name": { class: "never" },
  "component.navigation.atRoot": { class: "act" },
  "component.navigation.noCanvas": { class: "act" },
  "component.navigation.noSelection": { class: "act" },
  "component.navigation.notAComponent": { class: "act" },
  "component.navigation.notInstalled": { class: "act" },
  "component.notAnInstance": { class: "act" },
  "component.notFlattened": { class: "build" },
  "component.notInsideComponent": { class: "act" },
  "component.notInstalled": { class: "act" },
  "component.parameter.duplicate": { class: "never" },
  "component.parameter.incomplete": { class: "act" },
  "component.parameter.key": { class: "never" },
  "component.parameter.missingTarget": { class: "never" },
  "component.parameter.noTargets": { class: "advice", splits: { task: "T1641b", holds: ["advice", "never"] } },
  "component.parameter.rangeWiderThanTarget": { class: "degraded" },
  "component.parameter.reserved": { class: "never" },
  "component.parameter.typeMismatch": { class: "never" },
  "component.parameter.unknown": { class: "act" },
  "component.parentScope.malformed": { class: "never" },
  "component.parentScope.no-scope": { class: "never" },
  "component.parentScope.noScope": { class: "never", local: true },
  "component.parentScope.too-deep": { class: "never" },
  "component.parentScope.type": { class: "degraded", splits: { task: "T1641b", holds: ["never", "degraded"] } },
  "component.parentScope.unknown-key": { class: "never" },
  "component.path.missingNode": { class: "act" },
  "component.path.notAComponent": { class: "act" },
  "component.path.notInstalled": { class: "act" },
  "component.port.duplicate": { class: "never" },
  "component.port.missingNode": { class: "never" },
  "component.port.missingPort": { class: "never" },
  "component.port.variadic": { class: "never" },
  "component.presets.parentNamed": { class: "advice" },
  "component.presets.twoPageBanks": { class: "degraded" },
  "component.recursion": { class: "never" },
  "component.resolutionTargetMissing": { class: "never" },
  "component.selection.empty": { class: "act" },
  "component.selection.inputOrder": { class: "act" },
  "component.selection.missingNode": { class: "act" },
  "component.session.stale": { class: "act" },
  "component.starter.invalidDefinition": { class: "build" },
  "component.starter.invalidJson": { class: "build" },
  "component.starter.invalidLibrary": { class: "build" },
  "component.starter.rejected": { class: "build" },
  "component.upgrade.alreadyAtVersion": { class: "act" },
  "component.upgrade.droppedParameters": { class: "degraded" },
  "component.upgrade.noMigration": { class: "degraded" },
  "component.upgrade.removedPorts": { class: "degraded" },
  "component.upgrade.valueReset": { class: "degraded" },
  "component.version": { class: "never" },
  "connect.incompatible": { class: "act" },
  "connect.incompatibleSwap": { class: "act" },
  "connect.noSuchNode": { class: "act" },
  "connect.noSuchPort": { class: "act" },
  "control.channel": { class: "act" },
  "control.control": { class: "act" },
  "control.default.driven": { class: "act" },
  "control.default.missing": { class: "act" },
  "control.default.noNode": { class: "act" },
  "control.default.notControl": { class: "act" },
  "control.midi.mapping": { class: "act" },
  "control.midi.range": { class: "act" },
  "control.midi.source": { class: "act" },
  "control.midi.target": { class: "act" },
  "control.midi.unavailable": { class: "act" },
  "control.midi.unbound": { class: "act" },
  "control.midi.value": { class: "act" },
  "control.node": { class: "act" },
  "control.notBound": { class: "act" },
  "control.panel": { class: "act" },
  "control.panelAmbiguous": { class: "act" },
  "control.parameter": { class: "act" },
  "control.reset.nothing": { class: "act" },
  "control.self": { class: "act" },
  "control.setDefault.nothing": { class: "act" },
  "control.shape": { class: "act" },
  "control.unsupported": { class: "act" },
  "cornerPin.extract.degenerate": { class: "degraded" },
  "cornerPin.pin.degenerate": { class: "degraded" },
  "cue.back.start": { class: "act" },
  "cue.back.unfired": { class: "act" },
  "cue.bank.malformed": { class: "never" },
  "cue.bank.missing": { class: "notYet" },
  "cue.bank.type": { class: "never" },
  "cue.current.unknown": { class: "notYet" },
  "cue.fire.nothing": { class: "act" },
  "cue.go.empty": { class: "notYet" },
  "cue.go.end": { class: "act" },
  "cue.list.ambiguous": { class: "act" },
  "cue.list.malformed": { class: "never" },
  "cue.list.inInstance": { class: "act" },
  "cue.list.missing": { class: "act" },
  "cue.list.none": { class: "act" },
  "cue.list.type": { class: "act" },
  "cue.list.unknown": { class: "act" },
  "cue.preset.missing": { class: "notYet" },
  "cue.standby.unknown": { class: "notYet" },
  "cue.timeline": { class: "act" },
  "cue.timeline.bank": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "never", "elsewhereBuild"] } },
  "cue.timeline.drivenMorph": { class: "degraded" },
  "cue.timeline.malformed": { class: "never", local: true },
  "cue.timeline.overlap": { class: "advice" },
  "cue.timeline.preset": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "never"] } },
  "cue.timeline.structural": { class: "elsewhereBuild" },
  "cue.timeline.untimed": { class: "notYet" },
  "cue.unknown": { class: "act" },
  "definition.unknown": { class: "act" },
  "edge.duplicate": { class: "never" },
  "edge.missing": { class: "act" },
  "edge.orderMismatch": { class: "act" },
  "example.unknown": { class: "act" },
  "example.unreadable": { class: "act" },
  "export.audioEncoderUnavailable": { class: "act" },
  "export.audioNotDeterministic": { class: "act" },
  "export.cleanupFailed": { class: "act" },
  "export.encoderUnavailable": { class: "act" },
  "export.failed": { class: "act" },
  "export.invalidVideoSize": { class: "act" },
  "export.missing": { class: "act" },
  "export.noDevice": { class: "act" },
  "export.noOutput": { class: "act" },
  "export.noSession": { class: "act" },
  "export.noTransport": { class: "act" },
  "export.nonReproducible": { class: "advice" },
  "export.planUpdating": { class: "act" },
  "export.rangeNotContiguous": { class: "act" },
  "export.recordingSourceFrameMismatch": { class: "act" },
  "export.renderCancelled": { class: "act" },
  "export.renderFailed": { class: "act" },
  "export.renderInFlight": { class: "act" },
  "export.renderRangeOutsideTimeline": { class: "act" },
  "export.saveDestinationRequired": { class: "act" },
  "export.saveDestinationUnavailable": { class: "act" },
  "export.snapshotOversize": { class: "act" },
  "export.writeFailed": { class: "act" },
  "export/encoder-unavailable": { class: "act" },
  "export/live-read-too-large": { class: "act" },
  "export/malformed-readback": { class: "act" },
  "export/readback-during-playback": { class: "act" },
  "export/recording-backlog": { class: "act" },
  "export/recording-duplicate-frame": { class: "act" },
  "export/recording-failed": { class: "act" },
  "export/recording-frame-gap": { class: "act" },
  "export/recording-out-of-order": { class: "act" },
  "export/region-out-of-bounds": { class: "act" },
  "export/unknown-output": { class: "act" },
  "export/unsupported-format": { class: "act" },
  "fixture.noRename": { class: "act" },
  "gpu.unavailable": { class: "elsewhereHost" },
  "gridWarp.folded": { class: "degraded" },
  "gridWarp.line.axis": { class: "act" },
  "gridWarp.line.driven": { class: "act" },
  "gridWarp.line.exists": { class: "act" },
  "gridWarp.line.max": { class: "act" },
  "gridWarp.line.min": { class: "act" },
  "gridWarp.line.missing": { class: "act" },
  "gridWarp.line.outside": { class: "act" },
  "gridWarp.node.missing": { class: "act" },
  "gridWarp.node.type": { class: "act" },
  "group.duplicate": { class: "act" },
  "group.missing": { class: "act" },
  "harness.animateOff": { class: "act" },
  "help.noSurface": { class: "act" },
  "history.blocked": { class: "act" },
  "history.dryRun": { class: "act" },
  "history.empty": { class: "act" },
  "history.integrity": { class: "act" },
  "inspect.noPipelineSurface": { class: "act" },
  "inspect.noSurface": { class: "act" },
  "inspect.noTarget": { class: "act" },
  "inspect.unknownNode": { class: "act" },
  "laser.armed": { class: "elsewhereHost" },
  "laser.disarmed": { class: "elsewhereHost" },
  "laser.emission.blocked": { class: "elsewhereHost" },
  "laser.helper.absent": { class: "elsewhereHost" },
  "laser.source.missing": { class: "notYet" },
  "layout.alreadyTidy": { class: "act" },
  "layout.empty": { class: "act" },
  "layout.noShell": { class: "act" },
  "layout.unknownNodes": { class: "act" },
  "library.badPosition": { class: "act" },
  "library.noSurface": { class: "act" },
  "library.notOpened": { class: "act" },
  "mcp/bridge": { class: "act" },
  "mcp/export-ungranted": { class: "act" },
  "mcp/no-gpu": { class: "act" },
  "media.connecting": { class: "elsewhereHost" },
  "media.notLoaded": { class: "elsewhereHost" },
  "media.playback": { class: "elsewhereHost" },
  "media.screenCapture": { class: "elsewhereHost" },
  "media.unavailable": { class: "elsewhereHost" },
  "mesh.decode": { class: "elsewhereHost" },
  "mesh.empty": { class: "elsewhereHost" },
  "mesh.note": { class: "elsewhereHost" },
  "mesh.read": { class: "elsewhereHost" },
  "native.input": { class: "elsewhereHost" },
  "native.output": { class: "elsewhereHost" },
  "node.ambiguous": { class: "act" },
  "node.camera.reference": { class: "notYet" },
  "node.channelMask.boundaryMissing": { class: "build" },
  "node.channelMask.invalid": { class: "act" },
  "node.channelMask.notComponent": { class: "act" },
  "node.channelMask.unsupported": { class: "never" },
  "node.channelMask.unwritten": { class: "build" },
  "node.compile.historyUnavailable": { class: "never", local: true },
  "node.compile.missingResource": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "build"] } },
  "node.compile.tapClamped": { class: "degraded" },
  "node.compile.tooManyInputs": { class: "never" },
  "node.customWgsl.module": { class: "notYet", splits: { task: "T1641b", holds: ["never", "notYet"] } },
  "node.customWgsl.params": { class: "never" },
  "node.customWgsl.viewCamera": { class: "degraded" },
  "node.duplicate": { class: "act" },
  "node.emptyLabel": { class: "act" },
  "node.format.invalid": { class: "act" },
  "node.label.empty": { class: "act" },
  "node.label.separator": { class: "act" },
  "node.label.tooLong": { class: "act" },
  "node.materialWgsl.params": { class: "never" },
  "node.materialWgsl.source": { class: "never" },
  "node.materialWgsl.texture": { class: "never" },
  "node.materialWgsl.textureUnread": { class: "never", local: true },
  "node.materialWgsl.textureUnwired": { class: "notYet" },
  "node.mesh.clip": { class: "never" },
  "node.mesh.lamps": { class: "never" },
  "node.mesh.size": { class: "elsewhereHost" },
  "node.missing": { class: "act" },
  "node.name.kind": { class: "act" },
  "node.name.kindMissing": { class: "act" },
  "node.name.referencesRewritten": { class: "act" },
  "node.name.stranded": { class: "act" },
  "node.nameTaken": { class: "never" },
  "node.notShaderAuthorable": { class: "act" },
  "node.parameter.default": { class: "build" },
  "node.parameter.map": { class: "notYet", splits: { task: "T1641b", holds: ["never", "notYet"] } },
  "node.parameter.pulse": { class: "build" },
  "node.parameters.internalRemoval": { class: "act" },
  "node.parameters.internalSlot": { class: "act" },
  "node.parameters.noFlattening": { class: "act" },
  "node.parameters.notComponent": { class: "act" },
  "node.parameters.staleFlattening": { class: "act" },
  "node.points.attributes": { class: "never" },
  "node.points.capacity": { class: "elsewhereHost", splits: { task: "T1641b", holds: ["elsewhereHost", "never"] } },
  "node.points.clock": { class: "advice" },
  "node.points.curve": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "never"] } },
  "node.points.curveFrames": { class: "notYet", splits: { task: "T1641b", holds: ["never", "notYet"] } },
  "node.points.edge": { class: "notYet" },
  "node.points.gather": { class: "elsewhereHost", splits: { task: "T1641b", holds: ["notYet", "never", "elsewhereHost"] } },
  "node.points.group": { class: "notYet", splits: { task: "T1641b", holds: ["never", "notYet"] } },
  "node.points.input": { class: "never" },
  "node.points.kernel": { class: "elsewhereHost", splits: { task: "T1641b", holds: ["never", "notYet", "elsewhereHost"] } },
  "node.points.lifecycle": { class: "build" },
  "node.points.module": { class: "never" },
  "node.points.params": { class: "never" },
  "node.points.range": { class: "elsewhereHost", splits: { task: "T1641b", holds: ["notYet", "never", "elsewhereHost"] } },
  "node.points.resample": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "never"] } },
  "node.points.rope": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "never"] } },
  "node.points.source": { class: "build" },
  "node.points.spawn": { class: "never" },
  "node.points.strips": { class: "notYet" },
  "node.points.sweep": { class: "elsewhereHost", splits: { task: "T1641b", holds: ["notYet", "elsewhereHost"] } },
  "node.points.transform": { class: "elsewhereHost" },
  "node.port": { class: "build" },
  "node.port.duplicate": { class: "build" },
  "node.position": { class: "act" },
  "node.resolution.invalid": { class: "act" },
  "node.scene.camera": { class: "notYet" },
  "node.scene.empty": { class: "notYet" },
  "node.scene.endpoint": { class: "notYet" },
  "node.scene.environment": { class: "notYet" },
  "node.scene.geometry": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "never"] } },
  "node.scene.glass": { class: "never" },
  "node.scene.group": { class: "never" },
  "node.scene.instanceAttribute": { class: "notYet", splits: { task: "T1641b", holds: ["never", "notYet"] } },
  "node.scene.lightCapacity": { class: "never" },
  "node.scene.lightDepth": { class: "notYet" },
  "node.scene.lightDraw": { class: "degraded" },
  "node.scene.lightEverywhere": { class: "advice" },
  "node.scene.lightPoints": { class: "notYet" },
  "node.scene.lightSpot": { class: "degraded" },
  "node.scene.maps": { class: "never" },
  "node.scene.material": { class: "never" },
  "node.scene.override": { class: "never" },
  "node.scene.reference": { class: "never" },
  "node.scene.shadowCasters": { class: "advice" },
  "node.scene.shadowMesh": { class: "notYet" },
  "node.scene.shadowMeshFit": { class: "advice" },
  "node.scene.shadowOnly": { class: "never" },
  "node.scene.shape": { class: "elsewhereHost", splits: { task: "T1641b", holds: ["notYet", "elsewhereHost"] } },
  "node.scene.textureBudget": { class: "elsewhereHost" },
  "node.scene.topology": { class: "notYet" },
  "node.scene.unlit": { class: "degraded" },
  "node.size.invalid": { class: "act" },
  "node.stateful.inconsistent": { class: "build" },
  "node.stateful.undeclared": { class: "build" },
  "node.surface.topology": { class: "notYet", splits: { task: "T1641b", holds: ["notYet", "never"] } },
  "node.temporal.port": { class: "build" },
  "node.type": { class: "build" },
  "node.type.duplicate": { class: "build" },
  "node.ui.type": { class: "act" },
  "node.ui.unknown": { class: "act" },
  "node.unknown": { class: "act" },
  "node.unknownType": { class: "elsewhereBuild" },
  "node.valueExpression.syntax": { class: "never" },
  "node.version": { class: "build" },
  "osc.helper": { class: "elsewhereHost" },
  "osc.send": { class: "elsewhereHost" },
  "output.notTexture": { class: "act" },
  "output.toneMapInactive": { class: "degraded" },
  "output.unknownDefinition": { class: "act" },
  "output.unknownNode": { class: "act" },
  "output.unknownPort": { class: "act" },
  "parameter.bind.empty": { class: "never" },
  "parameter.bind.type": { class: "never", local: true },
  "parameter.bind.unavailable": { class: "build" },
  "parameter.bind.unreadable": { class: "never", local: true },
  "parameter.bind.value": { class: "degraded" },
  "parameter.bindCycle": { class: "never" },
  "parameter.channels.unavailable": { class: "elsewhereHost" },
  "parameter.clipboard.empty": { class: "act" },
  "parameter.clipboard.unreadable": { class: "act" },
  "parameter.driven": { class: "notYet" },
  "parameter.driven.clamped": { class: "degraded" },
  "parameter.driven.empty": { class: "never" },
  "parameter.enum": { class: "never" },
  "parameter.expression.clamped": { class: "degraded" },
  "parameter.expression.name": { class: "never", local: true },
  "parameter.expression.syntax": { class: "never", local: true },
  "parameter.expression.type": { class: "never", local: true },
  "parameter.expression.value": { class: "degraded" },
  "parameter.map.empty": { class: "never" },
  "parameter.mode.payload": { class: "act" },
  "parameter.mode.retired": { class: "act" },
  "parameter.multipleOwners": { class: "act" },
  "parameter.node": { class: "act" },
  "parameter.paste.channelNoReading": { class: "act" },
  "parameter.paste.nameNotText": { class: "act" },
  "parameter.paste.noBinding": { class: "act" },
  "parameter.paste.noName": { class: "act" },
  "parameter.paste.noReference": { class: "act" },
  "parameter.paste.shape": { class: "act" },
  "parameter.paste.textIsReference": { class: "act" },
  "parameter.pulse.failed": { class: "act" },
  "parameter.pulse.node": { class: "act" },
  "parameter.pulse.stored": { class: "never" },
  "parameter.pulse.type": { class: "act" },
  "parameter.pulse.unregistered": { class: "act" },
  "parameter.range": { class: "never" },
  "parameter.reference.ambiguous": { class: "never", local: true },
  "parameter.reference.channel": { class: "notYet" },
  "parameter.reference.node": { class: "notYet" },
  "parameter.reference.notComposed": { class: "advice" },
  "parameter.reference.self": { class: "act" },
  "parameter.reference.unavailable": { class: "elsewhereHost" },
  "parameter.reference.unknownType": { class: "elsewhereBuild" },
  "parameter.reference.unnamed": { class: "act" },
  "parameter.reference.unreadable": { class: "never", local: true },
  "parameter.reference.upstream": { class: "notYet" },
  "parameter.remove.absent": { class: "act" },
  "parameter.remove.declared": { class: "act" },
  "parameter.remove.none": { class: "act" },
  "parameter.referenceCycle": { class: "never" },
  "parameter.referenceProjection.missing": { class: "act" },
  "parameter.reset.cleared": { class: "act" },
  "parameter.retained": { class: "never", local: true },
  "parameter.revert.created": { class: "act" },
  "parameter.revert.unopened": { class: "act" },
  "parameter.slot.empty": { class: "never", local: true },
  "parameter.slot.shape": { class: "never" },
  "parameter.slot.unknown": { class: "elsewhereBuild" },
  "parameter.stops.count": { class: "never" },
  "parameter.type": { class: "never" },
  "parameter.undefined": { class: "never" },
  "parameter.unknown": { class: "never", local: true },
  "patch.conflict": { class: "act" },
  "patch.dryRun": { class: "act" },
  "patch.duplicateRef": { class: "act" },
  "patch.malformed": { class: "act" },
  "patch.staleBase": { class: "act" },
  "patch.unresolvedRef": { class: "act" },
  "perform.noWindowNode": { class: "act" },
  "perform.popupBlocked": { class: "act" },
  "perform.unavailable": { class: "act" },
  "points.readFailed": { class: "act" },
  "points.unavailable": { class: "act" },
  "port.incompatible": { class: "never" },
  "port.missing": { class: "never" },
  "port.notVariadic": { class: "act" },
  "port.occupied": { class: "never" },
  "port.sourceReference": { class: "act" },
  "preset.bank.inDefinition": { class: "act" },
  "preset.bank.malformed": { class: "never" },
  "preset.bank.missing": { class: "act" },
  "preset.bank.inner": { class: "act" },
  "preset.bank.nested": { class: "act" },
  "preset.bank.noCatalogue": { class: "elsewhereHost" },
  "preset.bank.noPageBank": { class: "notYet" },
  "preset.bank.notInstalled": { class: "elsewhereBuild" },
  "preset.bank.type": { class: "act" },
  "preset.bank.unknown": { class: "act" },
  "preset.bank.unnamed": { class: "notYet" },
  "preset.component.written": { class: "act" },
  "preset.delete.cued": { class: "act" },
  "preset.delete.recalled": { class: "act" },
  "preset.delete.unknown": { class: "act" },
  "preset.move.clash": { class: "act" },
  "preset.move.noInstance": { class: "act" },
  "preset.move.notOneLook": { class: "act" },
  "preset.name": { class: "act" },
  "preset.on.missing": { class: "notYet" },
  "preset.on.notLayer": { class: "never", local: true },
  "preset.page.notParent": { class: "never", local: true },
  "preset.page.on": { class: "never", local: true },
  "preset.page.recalls": { class: "never", local: true },
  "preset.recall.componentOverride": { class: "degraded" },
  "preset.recall.cycle": { class: "never" },
  "preset.recall.depth": { class: "never" },
  "preset.recall.morph": { class: "act" },
  "preset.recall.morphDropped": { class: "degraded" },
  "preset.recall.morphUnavailable": { class: "elsewhereHost" },
  "preset.recall.noName": { class: "act" },
  "preset.recall.nothing": { class: "act" },
  "preset.recall.unknown": { class: "act" },
  "preset.recalls.malformed": { class: "never", local: true },
  "preset.recalls.missing": { class: "notYet" },
  "preset.recalls.noCatalogue": { class: "elsewhereHost" },
  "preset.recalls.noPageBank": { class: "notYet" },
  "preset.recalls.notInstalled": { class: "elsewhereBuild" },
  "preset.recalls.type": { class: "never", local: true },
  "preset.recalls.unknown": { class: "notYet" },
  "preset.store.noTargets": { class: "notYet" },
  "preset.store.nothing": { class: "act" },
  "preset.target.default": { class: "never", local: true },
  "preset.target.key": { class: "never", local: true },
  "preset.target.missing": { class: "notYet" },
  "preset.target.pulse": { class: "never", local: true },
  "preset.target.self": { class: "never", local: true },
  "preset.target.unknownType": { class: "elsewhereBuild" },
  "preset.value.invalid": { class: "never", local: true },
  "preview.noTarget": { class: "act" },
  "preview.statsFailed": { class: "act" },
  "preview.statsUnavailable": { class: "act" },
  "preview.unknownLens": { class: "act" },
  "preview.unknownNode": { class: "act" },
  "project.asset.unresolved": { class: "elsewhereHost" },
  "project.autosave.failed": { class: "act" },
  "project.autosave.unavailable": { class: "act" },
  "project.components.invalid": { class: "elsewhereBuild", splits: { task: "T1641b", holds: ["never", "elsewhereBuild"] } },
  "project.components.rejected": { class: "never" },
  "project.limit.buffer": { class: "build" },
  "project.limit.dispatch": { class: "build" },
  "project.limit.memoryBudget": { class: "advice" },
  "project.limit.nodeResolution": { class: "degraded" },
  "project.limit.preview": { class: "degraded" },
  "project.limit.resolution": { class: "degraded" },
  "project.limit.settings": { class: "degraded" },
  "project.migration.applied": { class: "degraded" },
  "project.migration.backwards": { class: "build" },
  "project.migration.duplicate": { class: "build" },
  "project.migration.failed": { class: "build" },
  "project.migration.malformed": { class: "build" },
  "project.migration.missing": { class: "build" },
  "project.migration.noVersion": { class: "never" },
  "project.new.unsupported": { class: "act" },
  "project.noSurface": { class: "act" },
  "project.node.migrated": { class: "degraded" },
  "project.node.migrationFailed": { class: "build" },
  "project.node.newerVersion": { class: "elsewhereBuild" },
  "project.node.noMigration": { class: "degraded" },
  "project.node.unknownType": { class: "elsewhereBuild" },
  "project.open.failed": { class: "act" },
  "project.open.rejected": { class: "act" },
  "project.parameter.unknownKind": { class: "elsewhereBuild" },
  "project.parse.invalidDocument": { class: "never" },
  "project.parse.invalidJson": { class: "never" },
  "project.parse.notAnObject": { class: "never" },
  "project.save.failed": { class: "act" },
  "project.schema.newer": { class: "elsewhereBuild" },
  "project.settings.invalid": { class: "act" },
  "proposal.unknown": { class: "act" },
  "ramp.stops.capped": { class: "degraded" },
  "ramp.stops.unordered": { class: "advice" },
  "rename.noTarget": { class: "act" },
  "rename.unknownNode": { class: "act" },
  "requirement.unmet": { class: "elsewhereHost" },
  "runtime.noBackend": { class: "act" },
  "runtime.noFeedback": { class: "act" },
  "selection.empty": { class: "act" },
  "session.noInstance": { class: "act" },
  "session.projectStep": { class: "act" },
  "selection.noCanvas": { class: "act" },
  "settings.noSurface": { class: "act" },
  "shader/compile-error": { class: "never" },
  "shader/compile-failed": { class: "build" },
  "shader/compile-info": { class: "advice" },
  "shader/compile-warning": { class: "advice" },
  "shader/output-stale": { class: "act" },
  "sideEffect.blocked": { class: "elsewhereHost" },
  "tool.awaitingApproval": { class: "act" },
  "tool.dryRun": { class: "act" },
  "tool.failed": { class: "act" },
  "tool.input": { class: "act" },
  "tool.partialSource": { class: "act" },
  "tool.truncated": { class: "act" },
  "tool.unavailable": { class: "act" },
  "tool.unavailableCommand": { class: "act" },
  "tool.unavailablePort": { class: "act" },
  "tool.unavailableQuery": { class: "act" },
  "tool.unknown": { class: "act" },
  "transaction.dryRun": { class: "act" },
  "transaction.empty": { class: "act" },
  "transaction.partialRevert": { class: "act" },
  "transaction.unknown": { class: "act" },
  "transport.noLoop": { class: "act" },
  "transport.seekLimit": { class: "act" },
  "transport.seekRange": { class: "act" },
  "valueGraph.channelShadowed": { class: "degraded" },
  "valueGraph.cycle": { class: "never" },
  "valueGraph.evaluate": { class: "build" },
  "view.fullscreenRefused": { class: "act" },
  "view.fullscreenUnsupported": { class: "act" },
  "view.noCanvas": { class: "act" },
  "view.noFullscreenSurface": { class: "act" },
  "view.nothingToFrame": { class: "act" },
  "viewer.flyDirection": { class: "act" },
  "viewer.noCameraToFly": { class: "act" },
  "viewer.noNode": { class: "act" },
  "viewer.noOrbit": { class: "act" },
  "viewer.noOutput": { class: "act" },
  "viewer.noPane": { class: "act" },
  "vision.helper.absent": { class: "elsewhereHost" },
  "vision.native.refused": { class: "elsewhereHost" },
  "vision.native.retirement": { class: "elsewhereHost" },
  "vision.native.starting": { class: "elsewhereHost" },
  "vision.refused": { class: "elsewhereHost" },
  "wgsl/compile": { class: "advice", splits: { task: "T1641b", holds: ["never", "advice"] } },
};

/**
 * The one answer to "what class is this code". Total: a code with no row is `unclassified`,
 * which the gate keeps from happening for any code the source tree can be seen to emit.
 */
export function diagnosticClass(code: string): DiagnosticClass | "unclassified" {
  return Object.hasOwn(DIAGNOSTIC_CLASSES, code) ? (DIAGNOSTIC_CLASSES[code] as DiagnosticClassRow).class : "unclassified";
}

/**
 * Does an ERROR of this code leave the rest of the plan usable? True for the rows marked
 * `local`. A code with no row answers false: an error nobody classed withdraws the plan, as
 * every error did before the table.
 */
export function leavesPlanUsable(code: string): boolean {
  return Object.hasOwn(DIAGNOSTIC_CLASSES, code) && (DIAGNOSTIC_CLASSES[code] as DiagnosticClassRow).local === true;
}

/**
 * What a FINAL render stops on, as one question for every guard that asks it: an error; a
 * finding that can never take effect; one that is still waiting, because a final render has
 * no "later"; and a code with no row, which nobody has judged. A guard that named codes
 * instead went blind the day a code was split (`parameter.expression`, slice 1).
 *
 * And ONE degraded code, by the lead's ruling on slice 1: `parameter.expression.value`, an
 * expression with no finite answer at a frame (a division by zero). The stored value
 * standing in is right for an editor and a wrong picture that looks plausible in a film
 * frame. Both project render scripts wrote that clause by hand beside this function; it is
 * here now, and `strict: true` on a headless render is this question asked of every frame.
 */
export function stopsFinalRender(diagnostic: { readonly severity: string; readonly code: string }): boolean {
  if (diagnostic.severity === "error" || diagnostic.code === "parameter.expression.value") return true;
  const found = diagnosticClass(diagnostic.code);
  return found === "never" || found === "notYet" || found === "unclassified";
}
