export {
  evaluateAst,
  evaluateExpression,
  FREE_RUNNING_CLOCK_NAMES,
  FRAME_RATE_NAMES,
  WRAPPING_CLOCK_NAMES,
  functionNames,
  functionSignature,
  nearestSpelling,
  parseExpression,
  scopeFromFrame,
  type EvaluateResult,
  type ExpressionAst,
  type ExpressionFailure,
  type ExpressionFailureKind,
  type ExpressionScope,
  type KindedNodeReferenceResult,
  type NodeReferenceReader,
  type NodeReferenceResult,
  type ParseResult,
  type ReferenceFailureKind,
  type SpelledLike,
} from "./evaluate.ts";
