import type { FurnaceSceneFacts } from "./scene-facts.ts";
import { markerAt, wgslVec3 } from "./scene-facts.ts";
import { SHARED_UNIFORMS_WGSL } from "../../runtime/backend/shared-uniforms.ts";
import { fixtureTableWgsl, fixturesOf, LAMP_FUNCTIONS, LAMP_PARAMS } from "./fixtures.ts";
import type { SunView } from "./sun.ts";
import { sunLitWgsl } from "./sun.ts";

/**
 * T1354b — the shop's AIR: smoke that the lights live in.
 *
 * A Custom WGSL · Multi post pass (§T1365b) over the lit render, reading the Render's Depth
 * output as its second image. Per pixel it
 * rebuilds the view ray from the camera parameters, marches it to the surface through a
 * participating medium — thick near the floor and under the roof, drifting, turbulent — and
 * accumulates in-scattered light from two kinds of source:
 *
 *  - the process lights (furnace glow, arc, slag door, tap, tundish), at their GLB
 *    positions, inverse-square with a forward-scattering phase, each with its own intensity
 *    knob so the audio can flare one without the others;
 *  - the 65 lamp FIXTURES (fixtures.ts) — each a cone of light hanging in the smoke, with
 *    the same dimmers, crane travel and failing ballasts as the deferred lamp pass;
 *  - the SUN, wherever it reaches the smoke: every march step asks the sun's own depth view
 *    (sun.ts) whether the plant stands between — so the shafts are cut by the windows, the
 *    louvres and the trusses, not painted;
 *  - soft skylight SHAFTS under the roof louvres: analytic cylinders, the diffuse half.
 *
 * The surface colour is attenuated by the transmittance on the way. Unshadowed in-scatter
 * (a lamp's glow passes through the crane bridge) is the stated limit until §T1362b.
 */

interface ScatterLight {
  readonly marker: string;
  readonly param: string;
  readonly color: readonly [number, number, number];
  readonly rest: number;
  readonly help: string;
}

export const SCATTER_LIGHTS: readonly ScatterLight[] = [
  { marker: "light.furnace_glow", param: "furnaceGlow", color: [1, 0.42, 0.12], rest: 60, help: "Glow of the open furnace in the smoke." },
  { marker: "light.arc", param: "arcFlash", color: [0.62, 0.72, 1], rest: 10, help: "The arc's blue-white flash in the smoke (flicker it)." },
  { marker: "light.slag_door", param: "slagGlow", color: [1, 0.35, 0.08], rest: 25, help: "Slag door glow." },
  { marker: "light.tap", param: "tapGlow", color: [1, 0.5, 0.15], rest: 15, help: "Tapping stream glow." },
  { marker: "light.tundish", param: "tundishGlow", color: [1, 0.45, 0.14], rest: 12, help: "Caster tundish glow." },
];

/** The key light's travel direction; the louvre shafts slant along it. */
export const KEY_DIRECTION: readonly [number, number, number] = (() => {
  const [x, y, z] = [0.3, -0.85, -0.43];
  const length = Math.hypot(x, y, z);
  return [x / length, y / length, z / length] as const;
})();

export function atmosphereWgsl(facts: FurnaceSceneFacts, sun: SunView): string {
  const lights = SCATTER_LIGHTS.map((light) => ({ ...light, position: markerAt(facts, light.marker) }));
  const params = [...new Map(lights.map((light) => [light.param, light])).values()];
  const louvres = [...facts.markers.values()].filter((marker) => marker.name.startsWith("emit.louvre_shaft"));
  const cases = lights
    .map((light, index) => `    case ${index}u: { return ${wgslVec3(light.color)} * params.${light.param}; }`)
    .join("\n");
  return `${SHARED_UNIFORMS_WGSL}
// T1354b — furnace atmosphere (generated by src/projects/furnace/atmosphere.ts from the GLB).
struct Params {
  eye: vec3f, // @default 0  Camera position (drive from the camera).
  aim: vec3f, // @default 0  Camera look-at (drive from the camera).
  fov: f32, // @default 50  Camera vertical field of view, degrees.
  far: f32, // @default 400  Camera far plane — depth arrives as distance ÷ far.
  density: f32, // @default 0.018  Smoke extinction per metre at the floor.
  roofSmoke: f32, // @default 0.6  Extra smoke pooled under the roof.
  turbulence: f32, // @default 0.7  How lumpy and drifting the smoke is.
  ambientSmoke: vec3f, // @default 0.012  Base light the smoke carries everywhere (linear).
${params.map((light) => `  ${light.param}: f32, // @default ${light.rest}  ${light.help}`).join("\n")}
${LAMP_PARAMS}
  lampScatter: f32, // @default 1  How much of the fixtures' light the smoke catches.
  shafts: f32, // @default 2.5  Brightness of the light shafts under the roof louvres.
  sunShafts: f32, // @default 120  Radiance of sunlight in the smoke where the sun reaches it.
  sunColor: vec3f, // @default 1  Colour of the sunlight in the smoke.
  sunForward: f32, // @default 0.6  How strongly the smoke throws sunlight forward (HG g).
  shaftColor: vec3f, // @default 0.75  Colour of the shafts (daylight through smoke).
};

@group(0) @binding(0) var inputSampler: sampler;
@group(0) @binding(1) var inputTexture: texture_2d<f32>;
@group(0) @binding(2) var<uniform> frameU: SharedFrame;
@group(0) @binding(3) var<uniform> params: Params;
@group(0) @binding(4) var inputTexture1: texture_2d<f32>;
@group(0) @binding(5) var inputTexture2: texture_2d<f32>;

const LIGHT_COUNT: u32 = ${lights.length}u;
const LIGHT_POSITION = array<vec3f, ${lights.length}>(${lights.map((light) => wgslVec3(light.position)).join(", ")});
const SHAFT_COUNT: u32 = ${louvres.length}u;
const SHAFT_TOP = array<vec3f, ${Math.max(1, louvres.length)}>(${
    louvres.length === 0 ? "vec3f(0.0)" : louvres.map((marker) => wgslVec3(marker.position)).join(", ")
  });
const SHAFT_DIRECTION: vec3f = ${wgslVec3(KEY_DIRECTION)};
const SHAFT_RADIUS: f32 = 1.8;
const STEPS: u32 = 28u;
${sunLitWgsl(sun, "inputTexture2")}${fixtureTableWgsl(fixturesOf(facts))}${LAMP_FUNCTIONS}

fn lightRadiance(index: u32) -> vec3f {
  switch index {
${cases}
    default: { return vec3f(0.0); }
  }
}

fn airHash(p: vec3f) -> f32 {
  var q = fract(p * vec3f(0.1031, 0.1030, 0.0973));
  q = q + dot(q, q.yxz + 33.33);
  return fract((q.x + q.y) * q.z);
}

fn airNoise(p: vec3f) -> f32 {
  let i = floor(p);
  let f = fract(p);
  let u = f * f * (3.0 - 2.0 * f);
  return mix(
    mix(mix(airHash(i), airHash(i + vec3f(1.0, 0.0, 0.0)), u.x), mix(airHash(i + vec3f(0.0, 1.0, 0.0)), airHash(i + vec3f(1.0, 1.0, 0.0)), u.x), u.y),
    mix(mix(airHash(i + vec3f(0.0, 0.0, 1.0)), airHash(i + vec3f(1.0, 0.0, 1.0)), u.x), mix(airHash(i + vec3f(0.0, 1.0, 1.0)), airHash(i + vec3f(1.0, 1.0, 1.0)), u.x), u.y),
    u.z,
  );
}

fn smoke(x: vec3f, time: f32) -> f32 {
  let floorLayer = exp(-max(x.y, 0.0) * 0.07);
  let roofLayer = smoothstep(18.0, 32.0, x.y) * params.roofSmoke;
  let drift = vec3f(time * 0.35, time * 0.12, time * 0.2);
  let lumps = airNoise(x * 0.09 + drift * 0.09) * 0.65 + airNoise(x * 0.23 - drift * 0.2) * 0.35;
  let shape = mix(1.0, lumps * 2.0, params.turbulence);
  return params.density * (floorLayer + roofLayer) * max(shape, 0.0);
}

// Henyey-Greenstein, g = 0.35: smoke scatters mostly forward, so a light behind the haze blooms.
fn phase(cosTheta: f32) -> f32 {
  let g = 0.35;
  let denominator = 1.0 + g * g - 2.0 * g * cosTheta;
  return (1.0 - g * g) / (12.566371 * pow(denominator, 1.5));
}

fn phaseG(cosTheta: f32, g: f32) -> f32 {
  let denominator = 1.0 + g * g - 2.0 * g * cosTheta;
  return (1.0 - g * g) / (12.566371 * pow(max(denominator, 1e-4), 1.5));
}

fn shaftDensity(x: vec3f) -> f32 {
  var total = 0.0;
  for (var i = 0u; i < SHAFT_COUNT; i = i + 1u) {
    let offset = x - SHAFT_TOP[i];
    let along = dot(offset, SHAFT_DIRECTION);
    if (along < 0.0 || along > 70.0) { continue; }
    let across = length(offset - SHAFT_DIRECTION * along);
    total = total + exp(-(across * across) / (SHAFT_RADIUS * SHAFT_RADIUS)) * (1.0 - along / 70.0);
  }
  return total;
}

@fragment
fn fs(@location(0) uv: vec2f) -> @location(0) vec4f {
  let sample = textureSampleLevel(inputTexture, inputSampler, uv, 0.0);
  let aspect = frameU.resolution.x / max(frameU.resolution.y, 1.0);
  let forward = normalize(params.aim - params.eye);
  let right = normalize(cross(forward, vec3f(0.0, 1.0, 0.0)));
  let up = cross(right, forward);
  let tanHalf = tan(radians(params.fov) * 0.5);
  let ndc = vec2f(uv.x * 2.0 - 1.0, 1.0 - uv.y * 2.0);
  let direction = normalize(forward + right * ndc.x * tanHalf * aspect + up * ndc.y * tanHalf);
  // Depth is VIEW-PLANE distance ÷ far; along this ray that is z ÷ cos. The background
  // (depth 1, or nothing written) marches to a fixed horizon.
  let depthSize = vec2f(textureDimensions(inputTexture1));
  let depth = textureLoad(inputTexture1, clamp(vec2i(uv * depthSize), vec2i(0), vec2i(depthSize) - vec2i(1)), 0).r;
  let distance = select(depth * params.far / max(dot(direction, forward), 1e-3), 140.0, depth >= 0.9999 || depth <= 0.0);
  let step = distance / f32(STEPS);
  // Interleaved gradient noise: a dither the eye reads as texture, not as speckle.
  let pixel = uv * frameU.resolution + vec2f(frameU.absFrame * 5.588238);
  let jitter = fract(52.9829189 * fract(dot(pixel, vec2f(0.06711056, 0.00583715))));
  var transmittance = 1.0;
  var scatter = vec3f(0.0);
  for (var k = 0u; k < STEPS; k = k + 1u) {
    let x = params.eye + direction * (f32(k) + jitter) * step;
    let sigma = smoke(x, frameU.absTime);
    var inscatter = params.ambientSmoke;
    for (var i = 0u; i < LIGHT_COUNT; i = i + 1u) {
      let toLight = LIGHT_POSITION[i] - x;
      let d2 = dot(toLight, toLight);
      // A light is a small source, not a point: no sample within ~2 m of it sees more than a
      // bounded radiance, so a camera near the slag door is not engulfed.
      inscatter = inscatter + lightRadiance(i) * phase(dot(direction, toLight / sqrt(max(d2, 1e-4)))) / (4.0 + d2);
    }
    // The fixtures: cones in the smoke, reach windowed as in the lamp pass.
    for (var i = 0u; i < LAMP_COUNT; i = i + 1u) {
      let toLamp = lampPosition(i) - x;
      let d2 = dot(toLamp, toLamp);
      if (d2 > 1600.0) { continue; }
      let l = toLamp * inverseSqrt(max(d2, 1e-4));
      let cone = lampCone(i, -l, frameU.absTime);
      if (cone <= 0.0) { continue; }
      let fade = 1.0 - d2 / 1600.0;
      inscatter = inscatter + lampFlux(i, frameU.absTime) * (params.lampScatter * cone * fade * fade) * phase(dot(direction, l)) / (1.0 + d2);
    }
    inscatter = inscatter + params.shaftColor * params.shafts * shaftDensity(x) * phase(dot(direction, -SHAFT_DIRECTION));
    // Two shadow taps across the step: the shafts' edges are the sharpest thing in the air,
    // and one binary tap per step is what reads as speckle.
    let sunSeen = 0.5 * (sunLit(x) + sunLit(x + direction * step * 0.5));
    inscatter = inscatter + params.sunColor * (params.sunShafts * sunSeen) * phaseG(dot(direction, -SHAFT_DIRECTION), params.sunForward);
    scatter = scatter + transmittance * sigma * inscatter * step;
    transmittance = transmittance * exp(-sigma * step);
  }
  return vec4f(sample.rgb * transmittance + scatter, 1.0);
}`;
}
