import { SHARED_UNIFORMS_WGSL } from "../../runtime/backend/shared-uniforms.ts";
import type { Fixture } from "./fixtures.ts";
import { fixtureTableWgsl, LAMP_FUNCTIONS, LAMP_PARAMS } from "./fixtures.ts";

/**
 * T1354b — the DEFERRED LAMP PASS: the shop's 65 fixtures lighting the surfaces.
 *
 * A forward light is a block of shader per light in every surface draw; 65 of them over a
 * 1.2 M-vertex plant is not a budget anyone has. So the lamps light the frame AFTER it is
 * drawn, from the Render's G-buffer (§T1371b normal + roughness, §T1380b albedo + metallic,
 * and depth): per pixel, rebuild the world position, and for every fixture within reach add
 * GGX specular and the diffuse the specular left over — the same lobe the Render uses.
 *
 * Each fixture is a spot (its cone from the export), falls off with inverse-square windowed
 * to zero at a range set by its own brightness, and casts no shadow: occlusion (GTAO) runs
 * after this pass and darkens what it lit, which is what keeps a lamp under the roof from
 * reading as a light leak through the catwalks. Custom WGSL · Multi: input = the lit
 * render, More = [depth, normal, albedo].
 */
export function lampsWgsl(fixtures: readonly Fixture[]): string {
  return `${SHARED_UNIFORMS_WGSL}
// T1354b — furnace lamp fixtures, deferred (generated by src/projects/furnace/lamps.ts from the GLB).
struct Params {
  eye: vec3f, // @default 0  Camera position (drive from the camera).
  aim: vec3f, // @default 0  Camera look-at (drive from the camera).
  fov: f32, // @default 50  Camera vertical field of view, degrees.
  far: f32, // @default 400  Camera far plane (depth arrives as distance ÷ far).
${LAMP_PARAMS}
  cutoff: f32, // @default 0.004  Radiance below which a fixture's reach ends (sets each range).
  solo: f32, // @default 0  1 shows the lamps' light alone (tuning).
};

@group(0) @binding(0) var inputSampler: sampler;
@group(0) @binding(1) var inputTexture: texture_2d<f32>;
@group(0) @binding(2) var<uniform> frameU: SharedFrame;
@group(0) @binding(3) var<uniform> params: Params;
@group(0) @binding(4) var inputTexture1: texture_2d<f32>;
@group(0) @binding(5) var inputTexture2: texture_2d<f32>;
@group(0) @binding(6) var inputTexture3: texture_2d<f32>;

${fixtureTableWgsl(fixtures)}${LAMP_FUNCTIONS}

fn texel(size: vec2u, uv: vec2f) -> vec2i {
  let extent = vec2f(size);
  return clamp(vec2i(uv * extent), vec2i(0), vec2i(extent) - vec2i(1));
}

@fragment
fn fs(@location(0) uv: vec2f) -> @location(0) vec4f {
  let lit = textureSampleLevel(inputTexture, inputSampler, uv, 0.0);
  let gnormal = textureLoad(inputTexture2, texel(textureDimensions(inputTexture2), uv), 0);
  let depth = textureLoad(inputTexture1, texel(textureDimensions(inputTexture1), uv), 0).r;
  // No surface (sky, sparks, glass) or nothing at depth: the lamps have nothing to light.
  if (gnormal.a <= 0.0 || depth <= 0.0 || depth >= 0.9999) { return vec4f(lit.rgb * (1.0 - params.solo), lit.a); }
  let base = textureLoad(inputTexture3, texel(textureDimensions(inputTexture3), uv), 0);

  let forward = normalize(params.aim - params.eye);
  let right = normalize(cross(forward, vec3f(0.0, 1.0, 0.0)));
  let up = cross(right, forward);
  let tanHalf = tan(radians(params.fov) * 0.5);
  let aspect = frameU.resolution.x / max(frameU.resolution.y, 1.0);
  let ndc = vec2f(uv.x * 2.0 - 1.0, 1.0 - uv.y * 2.0);
  let ray = normalize(forward + right * ndc.x * tanHalf * aspect + up * ndc.y * tanHalf);
  let world = params.eye + ray * (depth * params.far / max(dot(ray, forward), 1e-3));

  let n = normalize(gnormal.rgb * 2.0 - vec3f(1.0));
  let roughness = clamp(gnormal.a, 0.04, 1.0);
  let metallic = base.a;
  let albedo = base.rgb;
  let v = -ray;
  let f0 = mix(vec3f(0.04), albedo, metallic);
  let alpha = roughness * roughness;
  let alpha2 = alpha * alpha;
  let nv = max(dot(n, v), 1e-4);
  let k = (roughness + 1.0) * (roughness + 1.0) / 8.0;
  let time = frameU.absTime;

  var sum = vec3f(0.0);
  for (var i = 0u; i < LAMP_COUNT; i = i + 1u) {
    let gain = lampGain(i, time);
    let flux = LAMP_COLOR[i] * gain;
    let peak = max(flux.r, max(flux.g, flux.b));
    // Reach: where inverse-square falls to the cutoff; windowed smoothly to zero there.
    let range2 = peak / max(params.cutoff, 1e-6);
    let toLamp = lampPosition(i) - world;
    let d2 = dot(toLamp, toLamp);
    if (d2 >= range2 || peak <= 0.0) { continue; }
    let l = toLamp * inverseSqrt(max(d2, 1e-6));
    let nl = dot(n, l);
    if (nl <= 0.0) { continue; }
    let cone = lampCone(i, -l, time);
    if (cone <= 0.0) { continue; }
    let window = pow(clamp(1.0 - (d2 / range2) * (d2 / range2), 0.0, 1.0), 2.0);
    let radiance = flux * cone * window / max(d2, 0.25);
    let h = normalize(l + v);
    let nh = max(dot(n, h), 0.0);
    let denominator = nh * nh * (alpha2 - 1.0) + 1.0;
    let distribution = alpha2 / (3.1415927 * denominator * denominator);
    let geometry = (nv / (nv * (1.0 - k) + k)) * (nl / (nl * (1.0 - k) + k));
    let fresnel = f0 + (vec3f(1.0) - f0) * pow(1.0 - max(dot(h, v), 0.0), 5.0);
    let specular = distribution * geometry * fresnel / max(4.0 * nv * nl, 1e-4);
    // No 1/π on the diffuse: the Render's own lights leave it out, and the two must agree.
    let diffuse = albedo * (vec3f(1.0) - fresnel) * (1.0 - metallic);
    sum = sum + (diffuse + specular) * radiance * nl;
  }
  return vec4f(lit.rgb * (1.0 - params.solo) + sum, lit.a);
}`;
}
