import type { FurnaceSceneFacts } from "./scene-facts.ts";
import { markerAt, wgslVec3 } from "./scene-facts.ts";

/**
 * T1354b — SPARKS: a stateless ballistic pool, drawn as additive beams (streaks).
 *
 * Every spark is a pure function of its id and the absolute clock: it belongs to one emitter
 * (by id), lives a seeded life, and re-rolls its launch every cycle. Position is the
 * closed-form flight under gravity with linear drag, folded at the floor so a spark bounces
 * once and skids; the endpoint trails along the current velocity, so the streak's length IS
 * the speed. Nothing accumulates, so a scrub or an offline take lands on the same sparks.
 *
 * Each emitter group has a RATE knob (0..1: the share of its pool alive this cycle) and the
 * pool shares one BRIGHTNESS — the audio lanes drive both. A dead spark collapses onto its
 * emitter with zero length and zero tint, which additive blending draws as nothing.
 */

interface Emitter {
  readonly marker: string;
  /** Metres above the marker the sparks leave from. */
  readonly lift?: number;
  readonly rate: string;
  /** Launch direction (pre-normalisation) and cone half-width. */
  readonly direction: readonly [number, number, number];
  readonly spread: number;
  readonly speed: readonly [number, number];
  readonly life: readonly [number, number];
}

const EMITTERS: readonly Emitter[] = [
  { marker: "emit.spark_tap", rate: "tapRate", direction: [1, 0.35, 0], spread: 0.55, speed: [4, 9], life: [0.8, 1.8] },
  // Oxygen lancing: the spray leaves the lance TIP, blown back out of the door.
  { marker: "emit.lance_tip", rate: "slagRate", direction: [-1, 0.35, 0], spread: 0.6, speed: [3, 9], life: [0.6, 1.5] },
  // The arc is hidden under the roof; what BLASTS OUT is at the electrode PORTS, where each
  // electrode passes through the roof — sparks from there, not from the hidden tips.
  { marker: "emit.arc_1", lift: 3.35, rate: "arcRate", direction: [0, 1, 0], spread: 0.7, speed: [3, 9], life: [0.4, 1.0] },
  { marker: "emit.arc_2", lift: 3.35, rate: "arcRate", direction: [0, 1, 0], spread: 0.7, speed: [3, 9], life: [0.4, 1.0] },
  { marker: "emit.arc_3", lift: 3.35, rate: "arcRate", direction: [0, 1, 0], spread: 0.7, speed: [3, 9], life: [0.4, 1.0] },
  { marker: "emit.spark_roof_gap", rate: "arcRate", direction: [0.3, 1, 0], spread: 0.6, speed: [4, 9], life: [0.3, 0.8] },
  { marker: "emit.spark_torch", rate: "torchRate", direction: [0, 0.2, 1], spread: 0.35, speed: [3, 7], life: [0.5, 1.2] },
  { marker: "emit.ladle_lip", rate: "pourRate", direction: [1, 0.2, 0], spread: 0.6, speed: [2, 6], life: [0.8, 1.6] },
];

export const SPARK_ATTRIBUTES = JSON.stringify([
  { name: "position", type: "vec3f", semantic: "position", default: [0, 0, 0] },
  { name: "endpoint", type: "vec3f", default: [0, 0, 0] },
  { name: "tint", type: "vec4f", semantic: "color", qualifier: "color", default: [0, 0, 0, 0] },
]);

export const SPARK_RATES: readonly string[] = [...new Set(EMITTERS.map((emitter) => emitter.rate))];

export function sparksKernel(facts: FurnaceSceneFacts): string {
  const origins = EMITTERS.map((emitter) => {
    const at = markerAt(facts, emitter.marker);
    return wgslVec3([at[0], at[1] + (emitter.lift ?? 0), at[2]]);
  });
  const directions = EMITTERS.map((emitter) => {
    const [x, y, z] = emitter.direction;
    const length = Math.hypot(x, y, z);
    return wgslVec3([x / length, y / length, z / length]);
  });
  const rateCases = EMITTERS.map((emitter, index) => `    case ${index}u: { return ctx.params.${emitter.rate}; }`).join("\n");
  const tuning = EMITTERS.map(
    (emitter) => `vec4f(${emitter.spread.toFixed(3)}, ${emitter.speed[0].toFixed(2)}, ${emitter.speed[1].toFixed(2)}, ${emitter.life[0].toFixed(2)})`,
  );
  const lifeMax = EMITTERS.map((emitter) => emitter.life[1].toFixed(2));
  const rates = SPARK_RATES.map((rate) => `  ${rate}: f32, // @default 0.3  Share of this emitter's sparks alive (0..1).`).join("\n");
  return `// T1354b — furnace sparks (generated by src/projects/furnace/sparks-kernel.ts from the GLB markers).
struct Params {
${rates}
  brightness: f32, // @default 6  HDR radiance of a fresh spark.
  streak: f32, // @default 0.035  Streak length in seconds of flight.
  gravity: f32, // @default 9.81  Metres per second squared.
};

const EMITTER_COUNT: u32 = ${EMITTERS.length}u;
const EMITTER_ORIGIN = array<vec3f, ${EMITTERS.length}>(${origins.join(", ")});
const EMITTER_DIRECTION = array<vec3f, ${EMITTERS.length}>(${directions.join(", ")});
// spread (radians), speed min, speed max, life min
const EMITTER_TUNING = array<vec4f, ${EMITTERS.length}>(${tuning.join(", ")});
const EMITTER_LIFE_MAX = array<f32, ${EMITTERS.length}>(${lifeMax.join(", ")});
const DRAG: f32 = 1.4;
const FLOOR: f32 = 0.03;

fn emitterRate(index: u32, ctx: PointCtx) -> f32 {
  switch index {
${rateCases}
    default: { return 0.0; }
  }
}

fn sparkHash(a: u32, b: u32) -> f32 {
  var h = a * 747796405u + b * 2891336453u + 12345u;
  h = ((h >> ((h >> 28u) + 4u)) ^ h) * 277803737u;
  h = (h >> 22u) ^ h;
  return f32(h) / 4294967295.0;
}

// Blackbody-ish ramp for a cooling spark: white-yellow fresh, deep orange, then red.
fn sparkHeat(heat: f32) -> vec3f {
  let h = clamp(heat, 0.0, 1.0);
  return mix(vec3f(1.0, 0.18, 0.02), mix(vec3f(1.0, 0.55, 0.12), vec3f(1.0, 0.92, 0.7), smoothstep(0.55, 1.0, h)), smoothstep(0.0, 0.55, h));
}

fn process(p: Point, ctx: PointCtx) -> Point {
  var q = p;
  let id = ctx.index;
  let emitter = id % EMITTER_COUNT;
  let tuning = EMITTER_TUNING[emitter];
  let life = mix(tuning.w, EMITTER_LIFE_MAX[emitter], sparkHash(id, 1u));
  let clock = ctx.absTime / life + sparkHash(id, 2u);
  let cycle = u32(floor(clock));
  let t = fract(clock) * life;
  let origin = EMITTER_ORIGIN[emitter];
  let alive = sparkHash(id, cycle * 7u + 3u) < clamp(emitterRate(emitter, ctx), 0.0, 1.0);
  if (!alive) {
    q.position = origin;
    q.endpoint = origin;
    q.tint = vec4f(0.0);
    return q;
  }
  // Launch: a cone around the emitter's direction, re-rolled every cycle.
  let axis = EMITTER_DIRECTION[emitter];
  let helper = select(vec3f(0.0, 1.0, 0.0), vec3f(1.0, 0.0, 0.0), abs(axis.y) > 0.9);
  let side = normalize(cross(axis, helper));
  let up = cross(side, axis);
  let angle = sparkHash(id, cycle * 7u + 4u) * 6.2831853;
  let tilt = sqrt(sparkHash(id, cycle * 7u + 5u)) * tuning.x;
  let direction = normalize(axis * cos(tilt) + (side * cos(angle) + up * sin(angle)) * sin(tilt));
  let speed = mix(tuning.y, tuning.z, sparkHash(id, cycle * 7u + 6u));
  let v0 = direction * speed;
  // Linear drag, closed form of dv/dt = g − k·v: v(t) = (v0 − g/k)e^{−kt} + g/k and
  // x(t) = x0 + (v0 − g/k)(1 − e^{−kt})/k + (g/k)·t. (The signs were once flipped, which
  // made gravity pull UP: sparks curling skyward.) At v0 = 0 and small t this is x0 + g·t²/2.
  let g = vec3f(0.0, -ctx.params.gravity, 0.0);
  let decay = exp(-DRAG * t);
  var position = origin + (v0 - g / DRAG) * (1.0 - decay) / DRAG + (g / DRAG) * t;
  var velocity = (v0 - g / DRAG) * decay + g / DRAG;
  // One bounce: fold below the floor, keep a third of the height and slow the skid.
  if (position.y < FLOOR) {
    position = vec3f(origin.x + (position.x - origin.x) * 0.85, FLOOR + (FLOOR - position.y) * 0.3, origin.z + (position.z - origin.z) * 0.85);
    velocity = vec3f(velocity.x * 0.5, -velocity.y * 0.3, velocity.z * 0.5);
  }
  let heat = 1.0 - t / life;
  q.position = position;
  q.endpoint = position - velocity * ctx.params.streak;
  // Cooling is fast: a spark is white-hot on the way up and nearly out by the time it falls.
  q.tint = vec4f(sparkHeat(heat) * ctx.params.brightness * heat * heat * heat, 1.0);
  return q;
}`;
}
