import { SHARED_UNIFORMS_WGSL } from "../../runtime/backend/shared-uniforms.ts";
import { CAMERA_PARAMS, VIEW } from "../furnace/screen-space.ts";
import type { OnNothingFacts } from "./scene-facts.ts";
import { wgslVec3 } from "./scene-facts.ts";

/**
 * T1400b — the reference's layer 1: light HAZE, and the ENVIRONMENT the chrome and the clear
 * coat reflect.
 *
 * Haze: every view ray is marched from the eye to the surface it hits (or `reach` metres),
 * and at each step every light in the table adds its in-scatter — spot cones for the
 * headlights and the backlight, small spheres for the LED tubes — through a Henyey-Greenstein
 * phase, forward-peaked, so a beam aimed down the lens blooms into a wall of light around the
 * silhouette that stands in it. The density is even (the reference keeps its haze subtle so
 * the blacks hold); a slow, faint drift keeps it from reading as a flat grey card.
 * Custom WGSL · Multi: Input = the lit frame, More = [depth].
 */

interface HazeLight {
  readonly position: readonly [number, number, number];
  readonly direction: readonly [number, number, number];
  /** cos of the outer half-angle; −2 for an omni light. */
  readonly cosOuter: number;
  readonly cosInner: number;
  readonly color: readonly [number, number, number];
  /** 0 headlights, 1 tubes, 2 the backlight. */
  readonly group: number;
}

function num3(value: unknown, fallback: readonly [number, number, number]): readonly [number, number, number] {
  return Array.isArray(value) && value.length === 3 && value.every((entry) => typeof entry === "number") ? [value[0] as number, value[1] as number, value[2] as number] : fallback;
}

/** The haze's light table, from the GLB's `lamp.*` markers (colour × lumens, cone, aim). */
export function hazeLights(facts: OnNothingFacts, groups: readonly ("head" | "tube" | "back")[]): HazeLight[] {
  const lights: HazeLight[] = [];
  for (const marker of [...facts.markers.values()].sort((a, b) => (a.name < b.name ? -1 : 1))) {
    const kind = marker.name.split(".")[1];
    const group = kind === "head" ? 0 : kind === "tube" ? 1 : kind === "back" ? 2 : -1;
    if (group < 0 || !groups.includes(kind as "head" | "tube" | "back")) continue;
    const extras = marker.extras ?? {};
    const lumens = typeof extras["loom_light_lumens"] === "number" ? (extras["loom_light_lumens"] as number) : 1000;
    const cone = typeof extras["loom_light_cone_deg"] === "number" ? (extras["loom_light_cone_deg"] as number) : 360;
    const color = num3(extras["loom_light_color"], [1, 1, 1]);
    const half = (Math.min(cone, 359) / 2) * (Math.PI / 180);
    lights.push({
      position: marker.position,
      direction: num3(extras["loom_light_dir"], [0, -1, 0]),
      cosOuter: cone >= 359 ? -2 : Math.cos(half),
      cosInner: cone >= 359 ? -1 : Math.cos(half * 0.45),
      color: [color[0] * lumens * 0.001, color[1] * lumens * 0.001, color[2] * lumens * 0.001],
      group,
    });
  }
  return lights;
}

export function hazeWgsl(lights: readonly HazeLight[]): string {
  const count = Math.max(1, lights.length);
  const list = (values: string[], empty: string): string => (values.length === 0 ? empty : values.join(",\n  "));
  return `${SHARED_UNIFORMS_WGSL}
// T1400b — On Nothing haze (generated by src/projects/on-nothing/atmosphere.ts from the GLB's lamps).
struct Params {
${CAMERA_PARAMS}
  density: f32, // @default 0.02  Scattering per metre.
  anisotropy: f32, // @default 0.7  Henyey-Greenstein g: how forward-peaked (toward the lens) the scatter is.
  ambient: vec3f, // @default 0  Radiance the haze carries everywhere (the room's own faint light).
  reach: f32, // @default 40  Longest march where a ray hits nothing, metres.
  head: f32, // @default 1  Headlight scatter gain.
  tube: f32, // @default 1  LED tube scatter gain.
  back: f32, // @default 1  Backlight scatter gain.
  drift: f32, // @default 0.25  Depth of the slow density variation.
  core: f32, // @default 0.08  Metres: the soft core radius around each source (caps 1/d²).
};

@group(0) @binding(0) var inputSampler: sampler;
@group(0) @binding(1) var inputTexture: texture_2d<f32>;
@group(0) @binding(2) var<uniform> frameU: SharedFrame;
@group(0) @binding(3) var<uniform> params: Params;
@group(0) @binding(4) var inputTexture1: texture_2d<f32>;
${VIEW}
const LIGHTS: u32 = ${lights.length}u;
const L_POS = array<vec3f, ${count}>(
  ${list(lights.map((light) => wgslVec3(light.position)), "vec3f(0.0)")});
const L_DIR = array<vec3f, ${count}>(
  ${list(lights.map((light) => wgslVec3(light.direction)), "vec3f(0.0, -1.0, 0.0)")});
const L_COLOR = array<vec3f, ${count}>(
  ${list(lights.map((light) => wgslVec3(light.color)), "vec3f(0.0)")});
const L_SHAPE = array<vec4f, ${count}>(
  ${list(lights.map((light) => `vec4f(${light.cosOuter.toFixed(5)}, ${light.cosInner.toFixed(5)}, ${light.group}.0, 0.0)`), "vec4f(-2.0, -1.0, 0.0, 0.0)")});
const STEPS: u32 = 72u;

fn hg(cosTheta: f32, g: f32) -> f32 {
  let g2 = g * g;
  return (1.0 - g2) / (12.566371 * pow(max(1.0 + g2 - 2.0 * g * cosTheta, 1e-4), 1.5));
}

fn groupGain(group: f32) -> f32 {
  return select(select(params.back, params.tube, group < 1.5), params.head, group < 0.5);
}

fn driftDensity(p: vec3f, t: f32) -> f32 {
  let q = p * 0.35 + vec3f(t * 0.05, 0.0, t * 0.03);
  let n = sin(q.x * 1.3 + sin(q.z * 0.9)) * sin(q.z * 1.1 + sin(q.y * 1.7 + q.x * 0.4)) * 0.5 + 0.5;
  return 1.0 + (n - 0.5) * 2.0 * params.drift;
}

@fragment
fn fs(@location(0) uv: vec2f) -> @location(0) vec4f {
  let lit = textureSampleLevel(inputTexture, inputSampler, uv, 0.0);
  let v = makeView();
  let ray = rayAt(v, uv);
  let z = viewDepth(uv);
  let distance = select(params.reach, z / max(dot(ray, v.forward), 1e-4), z > 0.0);
  let jitter = ignHash(uv * frameU.resolution + vec2f(frameU.absFrame * 5.3, 0.0));
  let dt = distance / f32(STEPS);
  var scatter = vec3f(0.0);
  var optical = 0.0;
  for (var i = 0u; i < STEPS; i = i + 1u) {
    let travel = (f32(i) + jitter) * dt;
    let p = params.eye + ray * travel;
    let sigma = params.density * driftDensity(p, frameU.absTime);
    var inscatter = params.ambient;
    for (var k = 0u; k < LIGHTS; k = k + 1u) {
      let toP = p - L_POS[k];
      let d2 = dot(toP, toP);
      let l = toP * inverseSqrt(max(d2, 1e-6));
      let shape = L_SHAPE[k];
      let cone = select(smoothstep(shape.x, shape.y, dot(l, L_DIR[k])), 1.0, shape.x < -1.5);
      if (cone <= 0.0) { continue; }
      inscatter = inscatter + L_COLOR[k] * groupGain(shape.z) * cone * hg(dot(l, -ray), params.anisotropy) / (d2 + params.core * params.core);
    }
    scatter = scatter + inscatter * sigma * exp(-optical) * dt;
    optical = optical + sigma * dt;
  }
  return vec4f(lit.rgb * exp(-optical) + scatter, lit.a);
}`;
}

/**
 * The warehouse as an EQUIRECT, for reflections only: black, a faint roof, and a ring of
 * vertical bright bars at the horizon — the tubes and the headlight columns — so the chrome
 * grille and the clear coat carry the reference's vertical highlights wherever they face.
 * The cyc variant is a bright white room.
 * Direction convention is the Render's: u = atan2(R.x, −R.z)/2π + 0.5, v = acos(R.y)/π.
 */
export const ENVIRONMENT_WGSL = `struct Params {
  bars: f32, // @default 3  Radiance of the vertical light bars.
  barCount: f32, // @default 22  Bars around the horizon.
  roof: f32, // @default 0.006  Radiance of the roof.
  floor: f32, // @default 0.002  Radiance below the horizon.
  white: f32, // @default 0  1 = the white cyc room instead.
};

@group(0) @binding(0) var inputSampler: sampler;
@group(0) @binding(1) var inputTexture: texture_2d<f32>;
@group(0) @binding(3) var<uniform> params: Params;

fn barHash(i: f32) -> f32 {
  return fract(sin(i * 91.3458 + 7.1) * 47453.5453);
}

@fragment
fn fs(@location(0) uv: vec2f) -> @location(0) vec4f {
  let unused = textureSampleLevel(inputTexture, inputSampler, uv, 0.0).a * 0.0;
  let phi = (uv.x - 0.5) * 6.2831853;
  let theta = uv.y * 3.1415927;
  let d = vec3f(sin(theta) * sin(phi), cos(theta), -sin(theta) * cos(phi));
  if (params.white > 0.5) {
    let wall = mix(0.55, 1.0, smoothstep(-0.3, 0.4, d.y));
    return vec4f(vec3f(wall * 1.6) + vec3f(unused), 1.0);
  }
  var radiance = mix(vec3f(params.floor), vec3f(params.roof), smoothstep(-0.05, 0.2, d.y));
  // Vertical bars: each its own azimuth jitter, width and height.
  let slot = uv.x * params.barCount;
  let index = floor(slot);
  let within = fract(slot) - 0.5 - (barHash(index) - 0.5) * 0.6;
  let width = 0.05 + 0.06 * barHash(index + 3.0);
  let top = 0.1 + 0.35 * barHash(index + 7.0);
  let lit = step(0.35, barHash(index + 11.0));
  let bar = smoothstep(width, width * 0.4, abs(within)) * smoothstep(-0.08, -0.04, d.y) * (1.0 - smoothstep(top - 0.04, top, d.y)) * lit;
  radiance = radiance + vec3f(0.92, 0.96, 1.0) * params.bars * bar;
  return vec4f(radiance + vec3f(unused), 1.0);
}`;

/** The cookie a car's projector throws: two soft hot spots (its headlights) with a wider, dimmer spill. */
export const HEADLIGHT_COOKIE_WGSL = `struct Params {
  hotspot: f32, // @default 0.22  Radius of the hot spot (fraction of the image height).
  spill: f32, // @default 0.8  Radius of the spill.
  separation: f32, // @default 0.3  Distance between the two beams' centres (fraction of the image width).
};

@group(0) @binding(0) var inputSampler: sampler;
@group(0) @binding(1) var inputTexture: texture_2d<f32>;
@group(0) @binding(3) var<uniform> params: Params;

@fragment
fn fs(@location(0) uv: vec2f) -> @location(0) vec4f {
  let unused = textureSampleLevel(inputTexture, inputSampler, uv, 0.0).a * 0.0;
  // Two low beams side by side (the projector sits between a car's headlights): each wide,
  // flat on top (the cut-off), brightest a little below the axis.
  var value = 0.0;
  for (var k = 0; k < 2; k = k + 1) {
    let c = (uv - vec2f(0.5 + (f32(k) - 0.5) * params.separation, 0.56)) * vec2f(1.0, 2.0);
    let r = length(c);
    value = value + exp(-(r * r) / (2.0 * params.hotspot * params.hotspot)) + 0.25 * exp(-(r * r) / (2.0 * params.spill * params.spill));
  }
  value = value * mix(0.15, 1.0, smoothstep(0.38, 0.44, uv.y));
  // Fade to nothing at the image's border: a projector's frame edge must never draw a hard rectangle.
  let border = smoothstep(0.0, 0.12, uv.x) * smoothstep(1.0, 0.88, uv.x) * smoothstep(0.0, 0.15, uv.y) * smoothstep(1.0, 0.85, uv.y);
  value = value * border;
  return vec4f(vec3f(value) + vec3f(unused), 1.0);
}`;

/**
 * T1407b — the environment from a real HDRI (Poly Haven, CC0), arriving RGBM-packed through a
 * Movie File In (hdri.ts): rgb × a × `range`, turned by `turn` (fraction of a revolution) and
 * scaled by `gain`, with a `crush` that pulls the dim room down while keeping its windows and
 * lamps — the reference's room is near black but its chrome still catches bright shapes.
 */
export const ENVIRONMENT_HDRI_WGSL = `struct Params {
  range: f32, // @default 16  RGBM range the picture was packed with.
  gain: f32, // @default 1  Radiance scale.
  turn: f32, // @default 0  Rotation about the vertical, fraction of a revolution.
  crush: f32, // @default 0  0 keeps the room; 1 keeps only what is brighter than 1.
  desaturate: f32, // @default 0.6  Chroma removed (the grade wants steel, not sunset).
};

@group(0) @binding(0) var inputSampler: sampler;
@group(0) @binding(1) var inputTexture: texture_2d<f32>;
@group(0) @binding(3) var<uniform> params: Params;

@fragment
fn fs(@location(0) uv: vec2f) -> @location(0) vec4f {
  let p = textureSampleLevel(inputTexture, inputSampler, vec2f(fract(uv.x + params.turn), uv.y), 0.0);
  var c = p.rgb * p.a * params.range;
  let luma = dot(c, vec3f(0.2126, 0.7152, 0.0722));
  c = mix(c, vec3f(luma), params.desaturate);
  c = c * mix(1.0, smoothstep(0.3, 1.5, luma), params.crush);
  return vec4f(c * params.gain, 1.0);
}`;
