import type { PartFacts } from "./scene-facts.ts";
import { rotateByQuaternion, wgslVec3 } from "./scene-facts.ts";

/**
 * T1407b — the DRIVING CAR: one Point Kernel over the cars mesh that stands the car the Blender
 * build rigged (`car<n>` with its `_trim` and four `_wheel_*` parts) on a shot's own mark —
 * turned `turn` radians about its origin, then moved by `place` — drives it forward `drive`
 * metres, and rolls each wheel about its hub by drive ÷ its radius, so the tyre never skids. A
 * wheel's radius is its hub's height (the car stands on the floor at y = 0), so a real model's
 * wheels (wheel_rig.py) roll true whatever their size. Every other car (part 0) stands still.
 * Stateless: the rest pose comes from upstream each frame.
 */

export const CAR_RIG_ATTRIBUTES = JSON.stringify([
  { name: "position", type: "vec3f", semantic: "position", default: [0, 0, 0] },
  { name: "normal", type: "vec3f", qualifier: "direction", default: [0, 1, 0] },
  { name: "surface", type: "vec4f", default: [1, 0, 0, 0] },
]);

export interface DrivenCar {
  readonly body: PartFacts;
  /** World unit vectors of the car: its forward and its right (the wheels' axle). */
  readonly forward: readonly [number, number, number];
  readonly right: readonly [number, number, number];
}

export function drivenCar(parts: readonly PartFacts[]): DrivenCar {
  const body = parts.find((part) => /^car\d+$/.test(part.name));
  if (body === undefined) throw new Error("drivenCar: the cars mesh has no rigged car part (car<n>).");
  // A car faces −Y in Blender, +Z in glTF; its axle is +X.
  return { body, forward: rotateByQuaternion(body.rotation, [0, 0, 1]), right: rotateByQuaternion(body.rotation, [1, 0, 0]) };
}

export function carRigKernel(parts: readonly PartFacts[]): string {
  const car = drivenCar(parts);
  const count = Math.max(0, ...parts.map((part) => part.index)) + 1;
  const parent = new Array<number>(count).fill(0);
  const pivot = new Array<string>(count).fill("vec3f(0.0)");
  const kind = new Array<number>(count).fill(0);
  const radius = new Array<string>(count).fill("1.0");
  const byName = new Map(parts.map((part) => [part.name, part]));
  for (const part of parts) {
    pivot[part.index] = wgslVec3(part.pivot);
    if (part.parent !== undefined) parent[part.index] = byName.get(part.parent)?.index ?? 0;
    kind[part.index] = part === car.body ? 1 : /_wheel_/.test(part.name) ? 2 : 0;
    if (kind[part.index] === 2) radius[part.index] = Math.max(part.pivot[1], 0.05).toFixed(4);
  }
  return `// T1407b — the driving car (generated by src/projects/on-nothing/car-rig.ts from the GLB's parts).
struct Params {
  drive: f32, // @default 0  How far the rigged car has driven forward, metres.
  place: vec3f, // @default 0  Where the rigged car stands, as an offset from its mark in the GLB (metres).
  turn: f32, // @default 0  The car turned about its origin before it is placed, radians (about +y).
};

const PARTS: u32 = ${count}u;
const PART_PARENT = array<u32, ${count}>(${parent.map((value) => `${value}u`).join(", ")});
const PART_PIVOT = array<vec3f, ${count}>(${pivot.join(", ")});
const PART_KIND = array<u32, ${count}>(${kind.map((value) => `${value}u`).join(", ")});
const FORWARD: vec3f = ${wgslVec3(car.forward)};
const ORIGIN: vec3f = ${wgslVec3(car.body.pivot)};
const AXLE: vec3f = ${wgslVec3(car.right)};
const PART_RADIUS = array<f32, ${count}>(${radius.join(", ")});

fn axisAngle(axis: vec3f, angle: f32) -> mat3x3f {
  let c = cos(angle);
  let s = sin(angle);
  let t = 1.0 - c;
  let a = normalize(axis);
  return mat3x3f(
    vec3f(t * a.x * a.x + c, t * a.x * a.y + s * a.z, t * a.x * a.z - s * a.y),
    vec3f(t * a.x * a.y - s * a.z, t * a.y * a.y + c, t * a.y * a.z + s * a.x),
    vec3f(t * a.x * a.z + s * a.y, t * a.y * a.z - s * a.x, t * a.z * a.z + c),
  );
}

fn process(p: Point, ctx: PointCtx) -> Point {
  var q = p;
  var part = u32(max(p.surface.w, 0.0) + 0.5);
  for (var level = 0u; level < 4u; level = level + 1u) {
    if (part == 0u || part >= PARTS) { break; }
    let k = PART_KIND[part];
    if (k == 1u) {
      let turn = axisAngle(vec3f(0.0, 1.0, 0.0), ctx.params.turn);
      q.position = ORIGIN + turn * (q.position - ORIGIN) + turn * FORWARD * ctx.params.drive + ctx.params.place;
      q.normal = turn * q.normal;
    } else if (k == 2u) {
      // Rolling forward: the top of the tyre moves ahead, about the axle.
      let r = axisAngle(AXLE, ctx.params.drive / PART_RADIUS[part]);
      let pv = PART_PIVOT[part];
      q.position = pv + r * (q.position - pv);
      q.normal = r * q.normal;
    }
    part = PART_PARENT[part];
  }
  return q;
}`;
}
