import type { Bone, OnNothingFacts } from "./scene-facts.ts";
import { wgslVec3 } from "./scene-facts.ts";

/**
 * T1400b — the FIGURE'S SKIN: one Point Kernel that poses the mannequin from per-bone knobs.
 *
 * T1401b: the figure is a real glTF skin. Mesh File In publishes each vertex's four joint
 * indices and weights (`joints`, `weights`) and the decoder's joint table (name, parent, rest
 * head) is `facts.bones`, baked in here. Each bone's world transform is its own rotation about
 * its REST head, then its parent's, up to the pelvis (the furnace rig's child-first walk); the
 * vertex blends its four transforms linearly (linear-blend skinning) and the whole figure is
 * then turned by `yaw` and set down at `place`.
 *
 * A bone's knob is a vec3 of Euler angles in radians about the REST figure's world axes
 * (x = the figure's left, y = up, z = the way it faces), applied x, then y, then z. All zero is
 * the export's A-pose. Stateless: the rest pose is read from upstream every frame.
 */

export const SKIN_ATTRIBUTES = JSON.stringify([
  { name: "position", type: "vec3f", semantic: "position", default: [0, 0, 0] },
  { name: "normal", type: "vec3f", qualifier: "direction", default: [0, 1, 0] },
  { name: "joints", type: "vec4f", default: [0, 0, 0, 0] },
  { name: "weights", type: "vec4f", default: [0, 0, 0, 0] },
]);

/** A bone's knob name: `upperarm.L` → `upperarmL`. */
export function boneParam(bone: Bone): string {
  return bone.name.replace(/[^A-Za-z0-9]/g, "");
}

export function skinKernel(facts: OnNothingFacts): string {
  const bones = facts.bones;
  if (bones.length === 0) throw new Error("skinKernel: the GLB's figure has no skin joints.");
  const count = bones.length;
  const params = bones.map((bone) => `  ${boneParam(bone)}: vec3f, // @default 0  ${bone.name}: rotation about its head, radians (x, y, z about the rest axes).`).join("\n");
  const cases = bones.map((bone) => `    case ${bone.index}u: { return ctx.params.${boneParam(bone)}; }`).join("\n");
  return `// T1400b — the figure's skin (generated by src/projects/on-nothing/skin-kernel.ts from the GLB's bones).
struct Params {
  place: vec3f, // @default 0  Where the figure stands (world metres).
  yaw: f32, // @default 0  Which way it faces: radians about +Y (0 faces +Z).
${params}
};

const BONES: u32 = ${count}u;
const BONE_PARENT = array<i32, ${count}>(${bones.map((bone) => `${bone.parent}`).join(", ")});
const BONE_HEAD = array<vec3f, ${count}>(${bones.map((bone) => wgslVec3(bone.head)).join(", ")});

fn boneAngles(i: u32, ctx: PointCtx) -> vec3f {
  switch i {
${cases}
    default: { return vec3f(0.0); }
  }
}

fn euler(e: vec3f) -> mat3x3f {
  let cx = cos(e.x); let sx = sin(e.x);
  let cy = cos(e.y); let sy = sin(e.y);
  let cz = cos(e.z); let sz = sin(e.z);
  let rx = mat3x3f(vec3f(1.0, 0.0, 0.0), vec3f(0.0, cx, sx), vec3f(0.0, -sx, cx));
  let ry = mat3x3f(vec3f(cy, 0.0, -sy), vec3f(0.0, 1.0, 0.0), vec3f(sy, 0.0, cy));
  let rz = mat3x3f(vec3f(cz, sz, 0.0), vec3f(-sz, cz, 0.0), vec3f(0.0, 0.0, 1.0));
  return rz * ry * rx;
}

struct Xf {
  m: mat3x3f,
  t: vec3f,
};

// The bone's world transform: its own rotation about its head, then each ancestor's.
fn boneXf(bone: u32, ctx: PointCtx) -> Xf {
  var acc: Xf;
  acc.m = mat3x3f(vec3f(1.0, 0.0, 0.0), vec3f(0.0, 1.0, 0.0), vec3f(0.0, 0.0, 1.0));
  acc.t = vec3f(0.0);
  var j = i32(bone);
  for (var level = 0u; level < 8u; level = level + 1u) {
    if (j < 0 || u32(j) >= BONES) { break; }
    let r = euler(boneAngles(u32(j), ctx));
    let h = BONE_HEAD[u32(j)];
    acc.m = r * acc.m;
    acc.t = r * (acc.t - h) + h;
    j = BONE_PARENT[u32(j)];
  }
  return acc;
}

fn process(p: Point, ctx: PointCtx) -> Point {
  var q = p;
  // Linear-blend skinning over the four influences the decoder normalised to sum 1.
  var posed = vec3f(0.0);
  var bent = vec3f(0.0);
  var total = 0.0;
  for (var k = 0u; k < 4u; k = k + 1u) {
    let w = p.weights[k];
    if (w <= 0.0) { continue; }
    let x = boneXf(min(u32(p.joints[k] + 0.5), BONES - 1u), ctx);
    posed = posed + w * (x.m * p.position + x.t);
    bent = bent + w * (x.m * p.normal);
    total = total + w;
  }
  if (total <= 0.0) {
    // Nothing skins this vertex: it keeps its rest place.
    posed = p.position;
    bent = p.normal;
  } else {
    posed = posed / total;
  }
  let normal = normalize(bent);
  let c = cos(ctx.params.yaw);
  let s = sin(ctx.params.yaw);
  let turn = mat3x3f(vec3f(c, 0.0, -s), vec3f(0.0, 1.0, 0.0), vec3f(s, 0.0, c));
  q.position = ctx.params.place + turn * posed;
  q.normal = turn * normal;
  return q;
}`;
}

/** The yaw that turns the figure's rest facing (+Z) onto a stage's facing. */
export function yawFor(facing: readonly [number, number, number]): number {
  return Math.atan2(facing[0], facing[2]);
}
