import type { Bone, OnNothingFacts } from "./scene-facts.ts";
import { wgslVec3 } from "./scene-facts.ts";

/**
 * T1400b — the FIGURE'S SKIN: one Point Kernel that poses the mannequin from per-bone knobs.
 *
 * T1401b: the figure is a real glTF skin. Mesh File In publishes each vertex's four joint
 * indices and weights (`joints`, `weights`) and the decoder's joint table (name, parent, rest
 * head) is `facts.bones`, baked in here. Each bone's world transform is its own rotation about
 * its REST head, then its parent's, up to the pelvis (the furnace rig's child-first walk); the
 * vertex blends its four transforms linearly (linear-blend skinning) and the whole figure is
 * then turned by `yaw` and set down at `place`.
 *
 * A bone's knob is a vec3 of Euler angles in radians about the REST figure's world axes
 * (x = the figure's left, y = up, z = the way it faces), applied x, then y, then z. All zero is
 * the export's A-pose. Stateless: the rest pose is read from upstream every frame.
 */

export const SKIN_ATTRIBUTES = JSON.stringify([
  { name: "position", type: "vec3f", semantic: "position", default: [0, 0, 0] },
  { name: "normal", type: "vec3f", qualifier: "direction", default: [0, 1, 0] },
  { name: "joints", type: "vec4f", default: [0, 0, 0, 0] },
  { name: "weights", type: "vec4f", default: [0, 0, 0, 0] },
]);

/** A bone's knob name: `upperarm.L` → `upperarmL`. */
export function boneParam(bone: Bone): string {
  return bone.name.replace(/[^A-Za-z0-9]/g, "");
}

export function skinKernel(facts: OnNothingFacts): string {
  const bones = facts.bones;
  if (bones.length === 0) throw new Error("skinKernel: the GLB's figure has no skin joints.");
  const count = bones.length;
  const params = bones.map((bone) => `  ${boneParam(bone)}: vec3f, // @default 0  ${bone.name}: rotation about its head, radians (x, y, z about the rest axes).`).join("\n");
  const cases = bones.map((bone) => `    case ${bone.index}u: { return ctx.params.${boneParam(bone)}; }`).join("\n");
  const hands = handKnobs(bones);
  return `// T1400b — the figure's skin (generated by src/projects/on-nothing/skin-kernel.ts from the GLB's bones).
struct Params {
  place: vec3f, // @default 0  Where the figure stands (world metres).
  yaw: f32, // @default 0  Which way it faces: radians about +Y (0 faces +Z).
${params}${hands.params}
};

const BONES: u32 = ${count}u;
const BONE_PARENT = array<i32, ${count}>(${bones.map((bone) => `${bone.parent}`).join(", ")});
const BONE_HEAD = array<vec3f, ${count}>(${bones.map((bone) => wgslVec3(bone.head)).join(", ")});

fn boneAngles(i: u32, ctx: PointCtx) -> vec3f {
  switch i {
${cases}
    default: { return vec3f(0.0); }
  }
}

fn euler(e: vec3f) -> mat3x3f {
  let cx = cos(e.x); let sx = sin(e.x);
  let cy = cos(e.y); let sy = sin(e.y);
  let cz = cos(e.z); let sz = sin(e.z);
  let rx = mat3x3f(vec3f(1.0, 0.0, 0.0), vec3f(0.0, cx, sx), vec3f(0.0, -sx, cx));
  let ry = mat3x3f(vec3f(cy, 0.0, -sy), vec3f(0.0, 1.0, 0.0), vec3f(sy, 0.0, cy));
  let rz = mat3x3f(vec3f(cz, sz, 0.0), vec3f(-sz, cz, 0.0), vec3f(0.0, 0.0, 1.0));
  return rz * ry * rx;
}

${hands.functions}
struct Xf {
  m: mat3x3f,
  t: vec3f,
};

// The bone's world transform: its own rotation about its head, then each ancestor's.
fn boneXf(bone: u32, ctx: PointCtx) -> Xf {
  var acc: Xf;
  acc.m = mat3x3f(vec3f(1.0, 0.0, 0.0), vec3f(0.0, 1.0, 0.0), vec3f(0.0, 0.0, 1.0));
  acc.t = vec3f(0.0);
  var j = i32(bone);
  // T1419b: pelvis → spine → chest → shoulder → upper arm → forearm → hand → three phalanges is
  // ten bones deep; the walk allows twelve.
  for (var level = 0u; level < 12u; level = level + 1u) {
    if (j < 0 || u32(j) >= BONES) { break; }
    let r = euler(boneAngles(u32(j), ctx))${hands.rotate};
    let h = BONE_HEAD[u32(j)];
    acc.m = r * acc.m;
    acc.t = r * (acc.t - h) + h;
    j = BONE_PARENT[u32(j)];
  }
  return acc;
}

fn process(p: Point, ctx: PointCtx) -> Point {
  var q = p;
  // Linear-blend skinning over the four influences the decoder normalised to sum 1.
  var posed = vec3f(0.0);
  var bent = vec3f(0.0);
  var total = 0.0;
  for (var k = 0u; k < 4u; k = k + 1u) {
    let w = p.weights[k];
    if (w <= 0.0) { continue; }
    let x = boneXf(min(u32(p.joints[k] + 0.5), BONES - 1u), ctx);
    posed = posed + w * (x.m * p.position + x.t);
    bent = bent + w * (x.m * p.normal);
    total = total + w;
  }
  if (total <= 0.0) {
    // Nothing skins this vertex: it keeps its rest place.
    posed = p.position;
    bent = p.normal;
  } else {
    posed = posed / total;
  }
  let normal = normalize(bent);
  let c = cos(ctx.params.yaw);
  let s = sin(ctx.params.yaw);
  let turn = mat3x3f(vec3f(c, 0.0, -s), vec3f(0.0, 1.0, 0.0), vec3f(s, 0.0, c));
  q.position = ctx.params.place + turn * posed;
  q.normal = turn * normal;
  return q;
}`;
}

/** The yaw that turns the figure's rest facing (+Z) onto a stage's facing. */
export function yawFor(facing: readonly [number, number, number]): number {
  return Math.atan2(facing[0], facing[2]);
}

// ── T1419b: the hands ──

type V3 = readonly [number, number, number];
const sub = (a: V3, b: V3): [number, number, number] => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
const cross = (a: V3, b: V3): [number, number, number] => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];
const dot = (a: V3, b: V3): number => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
const unit = (a: V3): [number, number, number] => {
  const l = Math.hypot(a[0], a[1], a[2]) || 1;
  return [a[0] / l, a[1] / l, a[2] / l];
};
const reject = (v: V3, n: V3): [number, number, number] => unit(sub(v, [n[0] * dot(v, n), n[1] * dot(v, n), n[2] * dot(v, n)]));

/** The four long fingers, in the order a hand's `curl` vec4 carries them. */
export const LONG_FINGERS = ["index", "middle", "ring", "pinky"] as const;
/** How much of a finger's curl each knuckle takes (base, middle, end): a fist closes the middle knuckle most. */
const KNUCKLE_SHARE = [1, 1.15, 0.8] as const;
/** How far each long finger fans with `spread` (index out one way, ring and pinky the other). */
const SPREAD_SHARE = { index: 1, middle: 0.15, ring: -0.6, pinky: -1.2 } as const;
/** How much of the thumb's fold each of its joints takes. */
const THUMB_SHARE = [0.35, 0.8, 0.9] as const;

/**
 * T1419b — the way a hand's palm faces at rest (unit, figure-local): along the middle finger ×
 * across the knuckles, turned to the midline (the rest A-pose's palms face the thighs).
 */
export function restPalm(bones: readonly Bone[], side: "L" | "R"): [number, number, number] {
  const at = (name: string): Bone => {
    const bone = bones.find((b) => b.name === `${name}.${side}`);
    if (bone === undefined) throw new Error(`restPalm: the rig has no ${name}.${side} (rebuild the GLB with hands.py's finger bones, T1419b).`);
    return bone;
  };
  const palm = unit(cross(unit(sub(at("middle2").head, at("middle1").head)), sub(at("index1").head, at("pinky1").head)));
  return palm[0] * Math.sign(at("hand").head[0]) > 0 ? [-palm[0], -palm[1], -palm[2]] : palm;
}

/** One turn of a finger bone: `share` × the knob's value, radians about `axis` (rest frame, unit). */
export interface FingerTurn {
  readonly axis: readonly [number, number, number];
  /** The kernel parameter it reads: `curlL.x`, `spreadL`, `thumbL.y` … */
  readonly knob: string;
  readonly share: number;
}

/**
 * T1419b — every finger bone's turns, in the order they compose (left to right: the first turn
 * is applied LAST). The kernel's `fingerTurn` is generated from this table, and the tests read it.
 */
export function fingerTurns(bones: readonly Bone[]): Map<number, FingerTurn[]> {
  const byName = new Map(bones.map((bone) => [bone.name, bone]));
  const turns = new Map<number, FingerTurn[]>();
  for (const side of ["L", "R"] as const) {
    const at = (name: string): Bone | undefined => byName.get(`${name}.${side}`);
    const index1 = at("index1");
    const pinky1 = at("pinky1");
    if (index1 === undefined || pinky1 === undefined || at("middle1") === undefined || at("middle2") === undefined || at("hand") === undefined) continue;
    const across = sub(index1.head, pinky1.head);
    const palm = restPalm(bones, side);
    const direction = (finger: string, knuckle: number): [number, number, number] => {
      const a = at(`${finger}${knuckle}`);
      if (a === undefined) throw new Error(`fingerTurns: no bone ${finger}${knuckle}.${side}.`);
      // the end phalanx has no child: it points the way the one before it does
      const [from, to] = knuckle === 3 ? [at(`${finger}2`), a] : [a, at(`${finger}${knuckle + 1}`)];
      if (from === undefined || to === undefined) throw new Error(`fingerTurns: ${finger}.${side} lacks a phalanx.`);
      return unit(sub(to.head, from.head));
    };
    LONG_FINGERS.forEach((finger, slot) => {
      for (const knuckle of [1, 2, 3] as const) {
        const bone = at(`${finger}${knuckle}`);
        if (bone === undefined) continue;
        const d = direction(finger, knuckle);
        // a turn of +θ about d × n carries the finger toward the palm
        const curl: FingerTurn = { axis: unit(cross(d, reject(palm, d))), knob: `curl${side}.${"xyzw"[slot]}`, share: KNUCKLE_SHARE[knuckle - 1]! };
        if (knuckle === 1) {
          // spread: about the palm's normal, signed so a positive share moves toward the index side
          const toward = Math.sign(dot(cross(palm, d), across)) || 1;
          turns.set(bone.index, [{ axis: palm, knob: `spread${side}`, share: SPREAD_SHARE[finger] * toward }, curl]);
        } else {
          turns.set(bone.index, [curl]);
        }
      }
    });
    // the thumb folds across the palm: toward the little finger's side and into the palm
    const fold = unit([-across[0] + palm[0] * 0.6, -across[1] + palm[1] * 0.6, -across[2] + palm[2] * 0.6]);
    for (const knuckle of [1, 2, 3] as const) {
      const bone = at(`thumb${knuckle}`);
      if (bone === undefined) continue;
      const d = direction("thumb", knuckle);
      const folds: FingerTurn = { axis: unit(cross(d, reject(fold, d))), knob: `thumb${side}.x`, share: THUMB_SHARE[knuckle - 1]! };
      // the swing: off the palm (+), about the axis across the thumb and the palm's normal
      turns.set(bone.index, knuckle === 1 ? [{ axis: unit(cross(palm, d)), knob: `thumb${side}.y`, share: 1 }, folds] : [folds]);
    }
  }
  return turns;
}

/**
 * T1419b — the HAND KNOBS, when the rig has finger bones (tools/blender/on-nothing/hands.py).
 * Per hand (`L`, `R`):
 *  - `curlL: vec4f` — index, middle, ring, pinky: radians of curl at the base knuckle (the middle
 *    and end knuckles follow at KNUCKLE_SHARE), toward the palm; 0 = straight, ~1.5 = a fist;
 *  - `spreadL: f32` — radians the fingers fan apart at the base knuckles (negative closes them);
 *  - `thumbL: vec2f` — x folds the thumb across the palm (all three joints), y swings it off
 *    the palm (+) at its base.
 * The axes are MEASURED from the rest heads (fingerTurns): a finger's direction is head to next
 * head, the palm's normal is along the middle finger × across the knuckles, turned to face the
 * midline (the rest A-pose's palms face the thighs). A finger bone's own Euler knob still applies
 * on top. The kernel composes them in the rest frame, like every other bone: spread, then curl.
 */
export function handKnobs(bones: readonly Bone[]): { params: string; functions: string; rotate: string } {
  const turns = fingerTurns(bones);
  const cases = [...turns].map(([index, list]) =>
    `    case ${index}u: { return ${list.map((turn) => `axisAngle(${wgslVec3(turn.axis)}, ctx.params.${turn.knob} * ${turn.share.toFixed(3)})`).join(" * ")}; }`);
  const params: string[] = [];
  for (const side of ["L", "R"] as const) {
    if (![...turns.values()].some((list) => list.some((turn) => turn.knob.startsWith(`curl${side}`)))) continue;
    params.push(
      `  curl${side}: vec4f, // @default 0  T1419b: ${side} hand — index, middle, ring, pinky curl at the base knuckle, radians (0 straight, ~1.5 a fist).`,
      `  spread${side}: f32, // @default 0  T1419b: ${side} hand — the fingers fan apart, radians.`,
      `  thumb${side}: vec2f, // @default 0  T1419b: ${side} thumb — x folds it across the palm, y swings it off the palm.`,
    );
  }
  if (cases.length === 0) return { params: "", functions: "", rotate: "" };
  return {
    params: `\n${params.join("\n")}`,
    rotate: " * fingerTurn(u32(j), ctx)",
    functions: `// T1419b: a turn of t radians about the unit axis a (Rodrigues).
fn axisAngle(a: vec3f, t: f32) -> mat3x3f {
  let c = cos(t);
  let s = sin(t);
  let k = 1.0 - c;
  return mat3x3f(
    vec3f(c + a.x * a.x * k, a.y * a.x * k + a.z * s, a.z * a.x * k - a.y * s),
    vec3f(a.x * a.y * k - a.z * s, c + a.y * a.y * k, a.z * a.y * k + a.x * s),
    vec3f(a.x * a.z * k + a.y * s, a.y * a.z * k - a.x * s, c + a.z * a.z * k));
}

// T1419b: the hand knobs' turn of a finger bone, about rest axes measured from the heads.
fn fingerTurn(i: u32, ctx: PointCtx) -> mat3x3f {
  switch i {
${cases.join("\n")}
    default: { return mat3x3f(vec3f(1.0, 0.0, 0.0), vec3f(0.0, 1.0, 0.0), vec3f(0.0, 0.0, 1.0)); }
  }
}
`,
  };
}

/**
 * T1419b — a HAND POSE as skin-kernel pose expressions (`curlL.x` …), for a shot's POSE table.
 * Every field is a number or an expression string (radians, or 0..1 for `point` and `flip`):
 *  - `curl`: every long finger's curl; `spread`; `thumb` (fold) and `thumbOut` (swing);
 *  - `point`: the index finger straightens out of the curl (1 = straight: pointing);
 *  - `flip`: the middle finger straightens out of it (1 = straight).
 */
export interface HandPose {
  readonly curl?: number | string;
  readonly spread?: number | string;
  readonly point?: number | string;
  readonly flip?: number | string;
  readonly thumb?: number | string;
  readonly thumbOut?: number | string;
  /** Per-finger additions to the curl (index, middle, ring, pinky): a looser pinky, a lazier ring. */
  readonly extra?: readonly [number | string, number | string, number | string, number | string];
}

/**
 * T1407b (hands) — THE PISTOL HAND, one pose for every row that holds the pistol (the reference's
 * 0:13, 0:16.5, 0:17.7 and the prism's 0:29): the three lower fingers wrapped round the grip,
 * the index laid half along the frame, the thumb folded over the back of the grip. The prop is
 * the GLB's `figgun` (hands.py), weighted to hand.R, so this pose closes the hand round it.
 */
export const PISTOL_GRIP: HandPose = { curl: 1.35, point: 0.55, thumb: 0.85, extra: [0, 0, 0.05, 0.1] };

export function handPose(side: "L" | "R", pose: HandPose): Record<string, string> {
  const e = (value: number | string | undefined): string => (value === undefined ? "0" : `(${value})`);
  const curl = e(pose.curl);
  const extra = pose.extra ?? [0, 0, 0, 0];
  const keep = [`(1 - ${e(pose.point)})`, `(1 - ${e(pose.flip)})`, "1", "1"];
  const out: Record<string, string> = {};
  LONG_FINGERS.forEach((_, slot) => {
    out[`curl${side}.${"xyzw"[slot]}`] = `(${curl} + ${e(extra[slot])}) * ${keep[slot]}`;
  });
  out[`spread${side}`] = e(pose.spread);
  out[`thumb${side}.x`] = e(pose.thumb);
  out[`thumb${side}.y`] = e(pose.thumbOut);
  return out;
}
