import { describe, expect, it } from "vitest";
import { listExamples } from "./catalogue.ts";
import { buildExampleFiles } from "./example-files.ts";
import { buildStarterComponents } from "./starter-components.ts";

/**
 * The shipped bytes are what the app itself would save (§V88, T153-T156).
 *
 * §V88 rejects a hand-built in-memory graph because an example that only exists as code
 * proves nothing about the format. Hand-written JSON has a quieter version of the same
 * problem: it can be a file the app would never produce and would silently rewrite the
 * first time anyone hit save. So the examples are GENERATED by `buildProjectFile` — the
 * real save path — and this test fails if a shipped file has drifted from its source in
 * `documents.ts`, in either direction.
 *
 * Fix a failure by editing `documents.ts` and re-running:
 *
 *   node --import ./src/tooling/alias-hooks.ts src/examples/build-examples.ts
 */

describe("shipped examples match the save path", async () => {
  // T956: the hologram embeds the DepthPoints definition, so the starter set is
  // authored first — the same defs the build script passes.
  const starterDefinitions = (await buildStarterComponents()).map((built) => built.definition);
  const generated = new Map(buildExampleFiles(starterDefinitions).map((file) => [file.fileName, file.text]));
  const shipped = new Map(listExamples().map((file) => [file.fileName, file.text]));

  it("ships exactly the files the builder writes", () => {
    expect([...shipped.keys()].sort()).toEqual([...generated.keys()].sort());
  });

  it.each([...generated.keys()])("%s is byte-identical to a fresh save", (fileName) => {
    expect(shipped.get(fileName)).toBe(generated.get(fileName));
  });

});
