import { SHARED_UNIFORMS_WGSL } from "../../runtime/backend/shared-uniforms.ts";

/**
 * Stage previz — projector beams in haze, as Custom WGSL · Multi sources.
 *
 * A Render's projectors light SURFACES; they put nothing in the air. These passes do the
 * air. One BEAM pass per projector marches the viewing camera's ray through that
 * projector's frustum (only the stretch of ray inside it, so a narrow cone still gets every
 * sample) and gathers its cookie as in-scattered light — the content itself shows up as
 * rays in the haze, which is the whole point of using projectors as light fixtures.
 *
 *   Input       the projector's cookie (filtered, so the rays sample it bilinearly)
 *   More #1     the viewing render's depth: the march stops at the first surface
 *   More #2     a depth render FROM THE PROJECTOR (a camera on the projector's pose):
 *               anything in front of the lens — a dancer, the riser, the kabuki — shadows
 *               the beam in the air behind it, not just on the floor
 *   More #3     the previous beam pass, so three projectors accumulate into one scatter map
 *
 * The lens model is the Projector node's own (`projectorMatrix`, camera.ts): throw ratio,
 * aspect, lens shift, keystone, roll — every field is driven off the projector node by
 * expression, so re-aiming a projector re-aims its cone. The COMPOSITE pass then attenuates
 * the render by the haze it is seen through and adds the scatter.
 *
 * The air is uniform base density times slow drifting value noise, plus a low fog layer
 * that thickens toward the deck. Extinction uses the base density only (an approximation
 * the eye forgives at concert haze densities).
 */

const VIEW_FIELDS = `  eye: vec3f, // @default [0, 1.75, 15]  Viewing camera position (driven from the camera).
  aim: vec3f, // @default [0, 3.6, 5]  Viewing camera look-at (driven from the camera).
  fov: f32, // @default 45  Viewing camera vertical field of view, degrees (driven).
  far: f32, // @default 120  Viewing camera far plane: depth arrives as distance / far (driven).
  roll: f32, // @default 0  Viewing camera roll, degrees (driven).`;

const VIEW_WGSL = `// The camera's right vector with its ROLL, exactly as camera.ts guardedRolledUp builds a view.
fn rolledRight(forward: vec3f, rollDeg: f32) -> vec3f {
  var up = select(vec3f(0.0, 1.0, 0.0), vec3f(0.0, 0.0, 1.0), abs(forward.y) > 0.999);
  let t = radians(-rollDeg);
  up = up * cos(t) + cross(forward, up) * sin(t) + forward * dot(forward, up) * (1.0 - cos(t));
  return normalize(cross(forward, up));
}

struct Basis {
  f: vec3f,
  r: vec3f,
  u: vec3f,
};

fn basis(origin: vec3f, toward: vec3f, rollDeg: f32) -> Basis {
  var b: Basis;
  b.f = normalize(toward - origin);
  b.r = rolledRight(b.f, rollDeg);
  b.u = cross(b.r, b.f);
  return b;
}

fn depthTexel(uv: vec2f) -> vec2i {
  let size = vec2f(textureDimensions(inputTexture1));
  return clamp(vec2i(uv * size), vec2i(0), vec2i(size) - vec2i(1));
}

fn cameraRay(cam: Basis, uv: vec2f) -> vec3f {
  let size = vec2f(textureDimensions(inputTexture1));
  let tanHalf = tan(radians(params.fov) * 0.5);
  let ndc = vec2f(uv.x * 2.0 - 1.0, 1.0 - uv.y * 2.0);
  return normalize(cam.f + cam.r * ndc.x * tanHalf * (size.x / max(size.y, 1.0)) + cam.u * ndc.y * tanHalf);
}

// Distance along the ray to the first surface, or \`reach\` where the ray hits nothing.
fn sceneDistance(cam: Basis, ray: vec3f, uv: vec2f, reach: f32) -> f32 {
  let d = textureLoad(inputTexture1, depthTexel(uv), 0).r;
  return select(d * params.far / max(dot(ray, cam.f), 1e-4), reach, d >= 0.9999 || d <= 0.0);
}`;

/** One projector's beam in the haze. `accumulate`: add the previous pass (More #3). */
export function beamShader(name: string, accumulate: boolean): string {
  return `${SHARED_UNIFORMS_WGSL}
// Stage previz — the ${name} projector's beam in haze (generated by src/projects/stage-previz/haze.ts).
struct Params {
${VIEW_FIELDS}
  lens: vec3f, // @default [0, 7, 20]  Projector lens position (driven from the projector).
  lensAim: vec3f, // @default [0, 6, -4]  Projector look-at (driven from the projector).
  spin: f32, // @default 0  Projector roll, degrees (driven).
  throwRatio: f32, // @default 1.8  Projector throw ratio (driven).
  aspect: f32, // @default 1.7778  Projector native aspect (driven).
  shiftX: f32, // @default 0  Lens shift X (driven).
  shiftY: f32, // @default 0  Lens shift Y (driven).
  keystoneH: f32, // @default 0  Keystone H, degrees (driven).
  keystoneV: f32, // @default 0  Keystone V, degrees (driven).
  brightness: f32, // @default 1  Projector brightness, nominal at its look-at distance (driven).
  shadowFov: f32, // @default 40  Vertical FOV of the camera that renders the projector's occluders (driven).
  shadowFar: f32, // @default 60  Far plane of that camera (driven).
  density: f32, // @default 0.03  Haze: scattering per metre.
  fog: f32, // @default 0.1  Low fog: extra scattering per metre at the deck, thinning upward.
  fogHeight: f32, // @default 0.8  Metres over which the low fog thins to a third.
  floorY: f32, // @default 1.4  The deck's height: where the low fog sits.
  drift: f32, // @default 0.6  How patchy the haze is (0 = perfectly even).
  anisotropy: f32, // @default 0.55  Forward scatter: beams read brighter looking into the lens.
  gain: f32, // @default 30  Beam visibility: how much light the haze returns.
  reach: f32, // @default 80  Longest march, metres, where the ray hits nothing.
};

@group(0) @binding(0) var inputSampler: sampler;
@group(0) @binding(1) var inputTexture: texture_2d<f32>;
@group(0) @binding(2) var<uniform> frameU: SharedFrame;
@group(0) @binding(3) var<uniform> params: Params;
@group(0) @binding(4) var inputTexture1: texture_2d<f32>;
@group(0) @binding(5) var inputTexture2: texture_2d<f32>;
${accumulate ? "@group(0) @binding(6) var inputTexture3: texture_2d<f32>;\n" : ""}
const STEPS: u32 = 44u;

${VIEW_WGSL}

struct Lens {
  o: vec3f,
  f: vec3f,
  r: vec3f,
  u: vec3f,
  tx: f32,
  ty: f32,
  kx: f32,
  ky: f32,
  nominal: f32,
};

fn makeLens() -> Lens {
  let b = basis(params.lens, params.lensAim, params.spin);
  var l: Lens;
  l.o = params.lens;
  l.f = b.f;
  l.r = b.r;
  l.u = b.u;
  l.tx = 0.5 / max(params.throwRatio, 0.05);
  l.ty = l.tx / max(params.aspect, 0.05);
  l.kx = tan(radians(params.keystoneH)) / l.tx;
  l.ky = tan(radians(params.keystoneV)) / l.ty;
  l.nominal = max(length(params.lensAim - params.lens), 1e-3);
  return l;
}

// A world point through the lens: (u, v) on the cookie and the clip w (w <= 0 behind the lens).
// projectorMatrix: x = xv/tx - 2 shiftX d, w = d + kx xv + ky yv.
fn throughLens(l: Lens, q: vec3f) -> vec3f {
  let v = q - l.o;
  let xv = dot(v, l.r);
  let yv = dot(v, l.u);
  let d = dot(v, l.f);
  let w = d + l.kx * xv + l.ky * yv;
  let n = vec2f(xv / l.tx - 2.0 * params.shiftX * d, yv / l.ty - 2.0 * params.shiftY * d) / max(w, 1e-5);
  return vec3f(n.x * 0.5 + 0.5, 0.5 - n.y * 0.5, w);
}

// The direction (at unit depth) that lands on ndc corner c — the 2x2 inverse of throughLens.
fn cornerRay(l: Lens, c: vec2f) -> vec3f {
  let a = 1.0 / l.tx - c.x * l.kx;
  let b = -c.x * l.ky;
  let e = -c.y * l.kx;
  let g = 1.0 / l.ty - c.y * l.ky;
  let px = c.x + 2.0 * params.shiftX;
  let py = c.y + 2.0 * params.shiftY;
  let det = a * g - b * e;
  return l.r * ((px * g - b * py) / det) + l.u * ((a * py - e * px) / det) + l.f;
}

// The stretch [t0, t1] of the ray o + t·dir that lies inside the beam's pyramid.
fn insideBeam(l: Lens, o: vec3f, dir: vec3f, t0In: f32, t1In: f32) -> vec2f {
  var corners = array<vec3f, 4>(cornerRay(l, vec2f(-1.0, -1.0)), cornerRay(l, vec2f(1.0, -1.0)), cornerRay(l, vec2f(1.0, 1.0)), cornerRay(l, vec2f(-1.0, 1.0)));
  let centre = corners[0] + corners[1] + corners[2] + corners[3];
  var t0 = t0In;
  var t1 = t1In;
  for (var k = 0u; k < 4u; k = k + 1u) {
    var n = cross(corners[k], corners[(k + 1u) % 4u]);
    if (dot(n, centre) < 0.0) { n = -n; }
    let a = dot(n, o - l.o);
    let b = dot(n, dir);
    if (abs(b) < 1e-7) {
      if (a < 0.0) { return vec2f(1.0, 0.0); }
      continue;
    }
    if (b > 0.0) { t0 = max(t0, -a / b); } else { t1 = min(t1, -a / b); }
  }
  return vec2f(t0, t1);
}

// 1 where the lens sees q, 0 where something in front of the lens is in the way.
fn lensSees(l: Lens, q: vec3f) -> f32 {
  let v = q - l.o;
  let d = dot(v, l.f);
  let size = vec2f(textureDimensions(inputTexture2));
  let tanY = tan(radians(params.shadowFov) * 0.5);
  let tanX = tanY * size.x / max(size.y, 1.0);
  let s = vec2f(dot(v, l.r) / (d * tanX) * 0.5 + 0.5, 0.5 - dot(v, l.u) / (d * tanY) * 0.5);
  if (d <= 0.0 || s.x < 0.0 || s.x > 1.0 || s.y < 0.0 || s.y > 1.0) { return 1.0; }
  let stored = textureLoad(inputTexture2, clamp(vec2i(s * size), vec2i(0), vec2i(size) - vec2i(1)), 0).r;
  if (stored >= 0.9999 || stored <= 0.0) { return 1.0; }
  return select(0.0, 1.0, d <= stored * params.shadowFar + 0.06 + 0.004 * d);
}

fn hash(p: vec3f) -> f32 {
  var q = fract(p * 0.1031);
  q = q + dot(q, q.zyx + 31.32);
  return fract((q.x + q.y) * q.z);
}

fn valueNoise(p: vec3f) -> f32 {
  let i = floor(p);
  let f = fract(p);
  let u = f * f * (3.0 - 2.0 * f);
  let a = mix(mix(hash(i), hash(i + vec3f(1.0, 0.0, 0.0)), u.x), mix(hash(i + vec3f(0.0, 1.0, 0.0)), hash(i + vec3f(1.0, 1.0, 0.0)), u.x), u.y);
  let b = mix(mix(hash(i + vec3f(0.0, 0.0, 1.0)), hash(i + vec3f(1.0, 0.0, 1.0)), u.x), mix(hash(i + vec3f(0.0, 1.0, 1.0)), hash(i + vec3f(1.0, 1.0, 1.0)), u.x), u.y);
  return mix(a, b, u.z);
}

fn air(q: vec3f, t: f32) -> f32 {
  let wind = vec3f(0.11, 0.035, -0.06) * t;
  let n = valueNoise(q * 0.45 + wind) * 0.65 + valueNoise(q * 1.3 - wind * 1.7) * 0.35;
  let even = max(1.0 + params.drift * (n - 0.5) * 2.0, 0.0);
  let low = params.fog * exp(-max(q.y - params.floorY, 0.0) / max(params.fogHeight, 0.05)) * (0.5 + n);
  return params.density * even + low;
}

fn hg(cosTheta: f32, g: f32) -> f32 {
  let g2 = g * g;
  return (1.0 - g2) / (12.566371 * pow(max(1.0 + g2 - 2.0 * g * cosTheta, 1e-4), 1.5));
}

fn ign(pixel: vec2f) -> f32 {
  return fract(52.9829189 * fract(dot(pixel, vec2f(0.06711056, 0.00583715))));
}

@fragment
fn fs(@location(0) uv: vec2f) -> @location(0) vec4f {
  let cam = basis(params.eye, params.aim, params.roll);
  let ray = cameraRay(cam, uv);
  let hit = sceneDistance(cam, ray, uv, params.reach);
  let l = makeLens();
  let span = insideBeam(l, params.eye, ray, 0.0, hit);
  var scatter = vec3f(0.0);
  if (span.y > span.x) {
    let jitter = ign(uv * frameU.resolution + vec2f(frameU.absFrame * 5.3, frameU.absFrame * 1.7));
    let dt = (span.y - span.x) / f32(STEPS);
    for (var i = 0u; i < STEPS; i = i + 1u) {
      let t = span.x + (f32(i) + jitter) * dt;
      let q = params.eye + ray * t;
      let p = throughLens(l, q);
      if (p.z <= 0.0 || p.x < 0.0 || p.x > 1.0 || p.y < 0.0 || p.y > 1.0) { continue; }
      let seen = lensSees(l, q);
      if (seen <= 0.0) { continue; }
      let away = q - l.o;
      let d2 = max(dot(away, away), 0.01);
      let cookie = textureSampleLevel(inputTexture, inputSampler, p.xy, 0.0).rgb;
      let phase = hg(dot(away * inverseSqrt(d2), -ray), params.anisotropy);
      scatter = scatter + cookie * (params.brightness * l.nominal * l.nominal / d2 * phase * air(q, frameU.absTime) * exp(-params.density * t) * dt);
    }
  }
  scatter = scatter * params.gain;
${accumulate
    ? "  let prior = textureLoad(inputTexture3, clamp(vec2i(uv * vec2f(textureDimensions(inputTexture3))), vec2i(0), vec2i(textureDimensions(inputTexture3)) - vec2i(1)), 0).rgb;\n  return vec4f(prior + scatter, 1.0);"
    : "  return vec4f(scatter, 1.0);"}
}
`;
}

/** The render seen through the haze, plus the beams. */
export function compositeShader(): string {
  return `${SHARED_UNIFORMS_WGSL}
// Stage previz — haze composite (generated by src/projects/stage-previz/haze.ts).
struct Params {
${VIEW_FIELDS}
  density: f32, // @default 0.03  Haze: extinction per metre (match the beam passes).
  ambient: vec3f, // @default [0.004, 0.0045, 0.006]  Light the haze carries everywhere (the room's own glow).
  reach: f32, // @default 80  Distance assumed where the ray hits nothing, metres.
  knee: f32, // @default 0.75  Highlights above this roll off softly instead of clipping.
};

@group(0) @binding(0) var inputSampler: sampler;
@group(0) @binding(1) var inputTexture: texture_2d<f32>;
@group(0) @binding(2) var<uniform> frameU: SharedFrame;
@group(0) @binding(3) var<uniform> params: Params;
@group(0) @binding(4) var inputTexture1: texture_2d<f32>;
@group(0) @binding(5) var inputTexture2: texture_2d<f32>;

${VIEW_WGSL}

fn scatterTexel(p: vec2i) -> vec3f {
  let size = vec2i(textureDimensions(inputTexture2));
  return textureLoad(inputTexture2, clamp(p, vec2i(0), size - vec2i(1)), 0).rgb;
}

// The half-resolution scatter, bilinear (More is bound unfilterable).
fn scatterAt(uv: vec2f) -> vec3f {
  let p = uv * vec2f(textureDimensions(inputTexture2)) - 0.5;
  let i = vec2i(floor(p));
  let f = p - floor(p);
  let top = mix(scatterTexel(i), scatterTexel(i + vec2i(1, 0)), f.x);
  let bottom = mix(scatterTexel(i + vec2i(0, 1)), scatterTexel(i + vec2i(1, 1)), f.x);
  return mix(top, bottom, f.y);
}

fn shoulder(x: f32) -> f32 {
  let k = clamp(params.knee, 0.0, 0.99);
  return select(x, k + (1.0 - k) * (1.0 - exp(-(x - k) / (1.0 - k))), x > k);
}

@fragment
fn fs(@location(0) uv: vec2f) -> @location(0) vec4f {
  let lit = textureSampleLevel(inputTexture, inputSampler, uv, 0.0);
  let cam = basis(params.eye, params.aim, params.roll);
  let ray = cameraRay(cam, uv);
  let hit = sceneDistance(cam, ray, uv, params.reach);
  let through = exp(-params.density * hit);
  let c = lit.rgb * through + params.ambient * (1.0 - through) + scatterAt(uv) + vec3f(frameU.time * 0.0);
  return vec4f(shoulder(c.r), shoulder(c.g), shoulder(c.b), lit.a);
}
`;
}
