import { SHARED_UNIFORMS_WGSL } from "../../runtime/backend/shared-uniforms.ts";

/**
 * Stage previz — test content for the projector feeds, as Custom WGSL generators (the
 * input is read only so its binding stays live; the picture is made here).
 *
 * BEAMS: what a projector used as a light fixture shows through haze. Four looks, cycling
 * every eight seconds with a one-second dissolve (or held with Look): a pulsing colour
 * wash (the full cone), rotating spokes (rays), bars sweeping left to right (a chase across
 * the cone) and rings expanding from the centre (a tunnel). The sweep is deliberately
 * one-directional: on the flipped stage-left feed it runs the other way, so the pair reads
 * mirror-symmetric from the house.
 *
 * GRID: the alignment chart. Grid lines, a centre cross, an inscribed circle and four
 * coloured corners — red top-left, green top-right, blue bottom-left, yellow bottom-right —
 * so a flip or a rotation anywhere in the chain is unmistakable on the curtain.
 */

export const TEST_BEAMS_WGSL = `${SHARED_UNIFORMS_WGSL}
// Stage previz — beam test content (generated by src/projects/stage-previz/test-content.ts).
struct Params {
  look: f32, // @default -1  -1 cycles the four looks; 0 wash, 1 spokes, 2 sweep, 3 rings holds one.
  hold: f32, // @default 8  Seconds per look while cycling.
  hue: f32, // @default 0  Shifts the palette (0..1 around the wheel).
  level: f32, // @default 1  Overall brightness.
};

@group(0) @binding(0) var inputSampler: sampler;
@group(0) @binding(1) var inputTexture: texture_2d<f32>;
@group(0) @binding(2) var<uniform> frameU: SharedFrame;
@group(0) @binding(3) var<uniform> params: Params;

fn palette(t: f32) -> vec3f {
  return 0.5 + 0.5 * cos(6.2831853 * (t + params.hue + vec3f(0.0, 0.33, 0.67)));
}

fn showLook(index: i32, uv: vec2f, t: f32) -> vec3f {
  let size = vec2f(textureDimensions(inputTexture));
  let p = (uv - 0.5) * vec2f(size.x / max(size.y, 1.0), 1.0);
  switch index {
    case 0: {
      return palette(t * 0.05) * (0.55 + 0.45 * sin(t * 2.2));
    }
    case 1: {
      let a = atan2(p.y, p.x) / 6.2831853;
      let spokes = smoothstep(0.32, 0.5, abs(fract(a * 9.0 + t * 0.08) - 0.5) * 2.0);
      return palette(0.6 + t * 0.03) * spokes * smoothstep(0.02, 0.08, length(p));
    }
    case 2: {
      let bar = smoothstep(0.62, 0.9, abs(fract(uv.x * 2.5 - t * 0.45) - 0.5) * 2.0);
      return mix(vec3f(1.0), palette(0.15), 0.35) * bar;
    }
    default: {
      let ring = smoothstep(0.55, 0.95, abs(fract(length(p) * 3.5 - t * 0.6) - 0.5) * 2.0);
      return palette(0.85 + length(p) * 0.3) * ring;
    }
  }
}

@fragment
fn fs(@location(0) uv: vec2f) -> @location(0) vec4f {
  let keep = textureSampleLevel(inputTexture, inputSampler, uv, 0.0).a * 0.0;
  let t = frameU.absTime;
  var c: vec3f;
  if (params.look >= 0.0) {
    c = showLook(i32(params.look) % 4, uv, t);
  } else {
    let hold = max(params.hold, 1.0);
    let phase = t / hold;
    let index = i32(floor(phase)) % 4;
    let blend = smoothstep(hold - 1.0, hold, fract(phase) * hold);
    c = mix(showLook(index, uv, t), showLook((index + 1) % 4, uv, t), blend);
  }
  return vec4f(c * params.level + keep, 1.0);
}
`;

export const TEST_GRID_WGSL = `${SHARED_UNIFORMS_WGSL}
// Stage previz — alignment grid (generated by src/projects/stage-previz/test-content.ts).
struct Params {
  cells: f32, // @default 16  Grid cells across the width.
  level: f32, // @default 1  Line brightness.
};

@group(0) @binding(0) var inputSampler: sampler;
@group(0) @binding(1) var inputTexture: texture_2d<f32>;
@group(0) @binding(2) var<uniform> frameU: SharedFrame;
@group(0) @binding(3) var<uniform> params: Params;

fn line(d: f32, width: f32) -> f32 {
  return 1.0 - smoothstep(width * 0.5, width * 0.5 + 1.0, d);
}

@fragment
fn fs(@location(0) uv: vec2f) -> @location(0) vec4f {
  let keep = textureSampleLevel(inputTexture, inputSampler, uv, 0.0).a * 0.0 + frameU.time * 0.0;
  let size = vec2f(textureDimensions(inputTexture));
  let px = uv * size;
  let cell = size.x / max(params.cells, 1.0);
  let g = abs(px - cell * round(px / cell));
  var c = vec3f(0.0);
  c = max(c, vec3f(0.55) * line(min(g.x, g.y), 2.0));
  let centre = abs(px - size * 0.5);
  c = max(c, vec3f(1.0) * line(min(centre.x, centre.y), 6.0));
  let edge = min(min(px.x, size.x - px.x), min(px.y, size.y - px.y));
  c = max(c, vec3f(1.0) * line(edge, 12.0));
  let r = length(px - size * 0.5);
  c = max(c, vec3f(1.0) * line(abs(r - size.y * 0.46), 5.0));
  let corner = size.y * 0.16;
  if (px.x < corner && px.y < corner) { c = vec3f(1.0, 0.1, 0.1); }
  if (px.x > size.x - corner && px.y < corner) { c = vec3f(0.1, 1.0, 0.2); }
  if (px.x < corner && px.y > size.y - corner) { c = vec3f(0.15, 0.3, 1.0); }
  if (px.x > size.x - corner && px.y > size.y - corner) { c = vec3f(1.0, 0.9, 0.1); }
  return vec4f(c * params.level + keep, 1.0);
}
`;

/**
 * FX: test content for the ONE feed that drives the pixel lines and the strobes (layout.py's FX
 * map: top half the pixel lines as seen from the house, bottom half the strobes in plan,
 * downstage at the bottom). Top: a rainbow drifting across the stage, and a bright band climbing
 * the seven rows. Bottom: a slow colour wash under a white flash chasing diagonally from
 * downstage stage right — so a wrong row or a mirrored column is plain on the set.
 */
export const TEST_FX_WGSL = `${SHARED_UNIFORMS_WGSL}
// Stage previz — FX feed test content (generated by src/projects/stage-previz/test-content.ts).
struct Params {
  speed: f32, // @default 0.25  Cycles per second.
  level: f32, // @default 1  Overall brightness.
};

@group(0) @binding(0) var inputSampler: sampler;
@group(0) @binding(1) var inputTexture: texture_2d<f32>;
@group(0) @binding(2) var<uniform> frameU: SharedFrame;
@group(0) @binding(3) var<uniform> params: Params;

fn hue(h: f32) -> vec3f {
  return clamp(abs(fract(h + vec3f(0.0, 0.6666667, 0.3333333)) * 6.0 - 3.0) - 1.0, vec3f(0.0), vec3f(1.0));
}

@fragment
fn fs(@location(0) uv: vec2f) -> @location(0) vec4f {
  let keep = textureSampleLevel(inputTexture, inputSampler, uv, 0.0).a * 0.0;
  let t = frameU.time * params.speed;
  var c = vec3f(0.0);
  if (uv.y < 0.5) {
    let up = 1.0 - uv.y * 2.0;                      // 0 at the lowest rack row, 1 at the top truss row
    let band = 1.0 - smoothstep(0.0, 0.16, abs(fract(t * 0.5) - up));
    c = hue(fract(uv.x * 0.8 - t)) * (0.3 + 0.7 * band);
  } else {
    let upstage = 1.0 - (uv.y - 0.5) * 2.0;         // 0 at the downstage edge, 1 at the riser's back
    let phase = fract(t - uv.x * 0.7 - upstage * 0.3);
    let flash = select(0.0, 1.0, phase < 0.06);
    c = hue(fract(t * 0.3 + upstage * 0.25)) * 0.22 + vec3f(flash);
  }
  return vec4f(c * params.level + keep, 1.0);
}
`;
