/**
 * T1587b — THE SENTINEL TUNNEL'S BORE, FROZEN: the input of `point-sweep-bore.gpu.test.ts`.
 *
 * The worked check holds the stock path (Curve, Resample, Curve Frames, Sweep) against a
 * hand-written bore: one grid that a kernel bends round a centre line. That bore belongs to a
 * project another session edits many times a day, and an engine test that read the project's
 * live files would go red on a change nobody ran it for. So what the test needs is COPIED
 * here, text for text, and the test proves a fact about a fixed input: the stock path
 * reproduces THIS bore.
 *
 * Copied on 2026-10-06 from:
 *
 *   src/projects/sentinel-bot/path.ts    at 1bc118e6 (2026-10-05): PATH, CHAMBERS, `pathAt`,
 *                                        `chamberAt`, and the text `pathWgsl()` returns
 *   src/projects/sentinel-bot/tunnel.ts  at 14b66ed2 (2026-10-05): BORE_COLUMNS, BORE_ROWS,
 *                                        BORE_ATTRIBUTES, and the text of BORE_KERNEL
 *
 * Nothing here imports the project, and nothing here is kept in step with it: if the project's
 * bore changes, this is still the bore the check was made against. The WGSL is the project's
 * generated text, byte for byte, comments included.
 */

export interface FrozenPathTerm {
  /** Metres. */
  readonly amplitude: number;
  /** Whole cycles per period. */
  readonly cycles: number;
  /** Radians. */
  readonly phase: number;
}

/** The centre line: `(X(z), Y(z), z)`, each of X and Y a sum of sines of z that repeats every `period` metres. */
export const BORE_PATH: { readonly period: number; readonly x: ReadonlyArray<FrozenPathTerm>; readonly y: ReadonlyArray<FrozenPathTerm> } = {
  period: 960,
  x: [{ amplitude: 14, cycles: 5, phase: 0.4 }, { amplitude: 5, cycles: 13, phase: 1.9 }],
  y: [{ amplitude: 6, cycles: 4, phase: 2.2 }, { amplitude: 2.5, cycles: 11, phase: 0.7 }],
};

/** The halls: every `spacing` metres the bore swells by `swell` of its radius, over `flare` metres either side of `reach`. */
export const BORE_CHAMBERS = { spacing: 96, reach: 13, flare: 7, swell: 0.9 } as const;

const smoothstep = (low: number, high: number, x: number): number => {
  const t = Math.min(1, Math.max(0, (x - low) / (high - low)));
  return t * t * (3 - 2 * t);
};

/** How far into a hall the distance z is: 0 in the bore, 1 across a hall's middle. */
export function boreChamberAt(z: number): number {
  const along = z - BORE_CHAMBERS.spacing * Math.floor(z / BORE_CHAMBERS.spacing);
  return 1 - smoothstep(BORE_CHAMBERS.reach - BORE_CHAMBERS.flare, BORE_CHAMBERS.reach, Math.abs(along - BORE_CHAMBERS.spacing / 2));
}

/** The centre line itself, in float64. */
export function borePathAt(z: number): [number, number, number] {
  const sum = (terms: ReadonlyArray<FrozenPathTerm>): number =>
    terms.reduce((total, term) => total + term.amplitude * Math.sin(((2 * Math.PI * term.cycles) / BORE_PATH.period) * z + term.phase), 0);
  return [sum(BORE_PATH.x), sum(BORE_PATH.y), z];
}

/** Columns round the bore and rows along it. */
export const BORE_COLUMNS = 256;
export const BORE_ROWS = 768;

export const BORE_ATTRIBUTES = "[{\"name\":\"position\",\"type\":\"vec3f\",\"semantic\":\"position\",\"default\":[0,0,0]},{\"name\":\"tint\",\"type\":\"vec4f\",\"semantic\":\"color\",\"qualifier\":\"color\",\"default\":[0,0,0,0]}]";

/** The centre line as WGSL: `pathAt`, `pathTangent`, `pathFrame` and `chamberAt`. */
export const BORE_PATH_WGSL = `// T1561b — the tunnel's centreline (generated by src/projects/sentinel-bot/path.ts).
const PATH_PERIOD: f32 = 960.0;

fn pathAt(z: f32) -> vec3f {
  return vec3f(14.0 * sin(0.0327249235 * z + 0.4) + 5.0 * sin(0.085084801 * z + 1.9), 6.0 * sin(0.0261799388 * z + 2.2) + 2.5 * sin(0.0719948316 * z + 0.7), z);
}

fn pathTangent(z: f32) -> vec3f {
  return normalize(vec3f(0.458148929 * cos(0.0327249235 * z + 0.4) + 0.425424005 * cos(0.085084801 * z + 1.9), 0.157079633 * cos(0.0261799388 * z + 2.2) + 0.179987079 * cos(0.0719948316 * z + 0.7), 1.0));
}

struct Frame {
  origin: vec3f,
  right: vec3f,
  up: vec3f,
  forward: vec3f,
};

// Chambers (src/projects/sentinel-bot/path.ts, CHAMBERS): 0 in the bore, 1 across a hall's middle.
const CHAMBER_SWELL: f32 = 0.9;
fn chamberAt(z: f32) -> f32 {
  let along = z - 96.0 * floor(z / 96.0);
  return 1.0 - smoothstep(6.0, 13.0, abs(along - 48.0));
}

fn pathFrame(z: f32) -> Frame {
  var frame: Frame;
  frame.origin = pathAt(z);
  frame.forward = pathTangent(z);
  frame.right = normalize(cross(vec3f(0.0, 1.0, 0.0), frame.forward));
  frame.up = cross(frame.forward, frame.right);
  return frame;
}
`;

/** The kernel that bends the grid into the bore. */
export const BORE_KERNEL = `// T1561b — the tunnel's bore (src/projects/sentinel-bot/tunnel.ts).
struct Params {
  travel: f32, // @default 0  Distance travelled along the tunnel, metres.
  bore: f32, // @default 2.6  Radius the claws plant on, metres: the ribs' crests.
  relief: f32, // @default 1  How much of the ribs, pipes and plates stands off the liner: 0 is a plain pipe.
  deck: f32, // @default 0.74  How far below the axis the flat deck lies, as a share of the radius; 1 or more is no deck.
};
${BORE_PATH_WGSL}
const ROW: f32 = 0.15000;
const RIB: f32 = 1.60000;
const RUNS: u32 = 9u;
const RUN = array<vec3f, 9>(vec3f(0.4200, 0.0750, 0.1300), vec3f(0.6200, 0.0350, 0.0700), vec3f(0.7000, 0.0350, 0.0700), vec3f(2.5000, 0.0900, 0.1500), vec3f(2.7400, 0.0300, 0.0600), vec3f(1.1800, 0.0280, 0.0550), vec3f(1.9800, 0.0280, 0.0550), vec3f(3.5500, 0.0500, 0.1000), vec3f(5.8500, 0.0500, 0.1000));

fn plate(a: u32, b: u32) -> f32 {
  let x = (a * 747796405u) ^ (b * 2891336453u);
  let w = ((x >> ((x >> 28u) + 4u)) ^ x) * 277803737u;
  return f32((w >> 22u) ^ w) / 4294967295.0;
}

fn process(p: Point, ctx: PointCtx) -> Point {
  var q = p;
  // Rows stand at whole multiples of the row spacing, so the wall holds still while the window slides along it.
  let z = (floor(ctx.params.travel / ROW) + f32(ctx.dim.j) - 180.0) * ROW;
  // The seam is under the deck: the first and last column are the same line.
  let around = f32(ctx.dim.i) / f32(ctx.dim.cols - 1u);
  let theta = (around - 0.25) * 6.2831853;
  let wall = pathFrame(z);
  let radial = wall.right * cos(theta) + wall.up * sin(theta);

  // In a chamber the bore opens out into a hall (path.ts, CHAMBERS).
  let bore = ctx.params.bore * (1.0 + CHAMBER_SWELL * chamberAt(z));
  let liner = bore + 0.05;
  var radius = liner;
  var what = 0.0;
  // Plates: a panel every rib bay and every eighth of a turn, set a little in or out.
  let bay = floor(z / RIB);
  let panel = plate(u32(bay - floor(bay / 600.0) * 600.0), u32(around * 8.0));
  radius = radius - (panel - 0.5) * 0.05 * ctx.params.relief;
  // Pipes and cable runs along the wall.
  let angle = theta - 6.2831853 * floor(theta / 6.2831853);
  for (var i = 0u; i < RUNS; i = i + 1u) {
    let across = abs(angle - RUN[i].x) / RUN[i].y;
    if (across < 1.0) {
      radius = min(radius, liner - RUN[i].z * sqrt(1.0 - across * across) * ctx.params.relief);
      what = 2.0;
    }
  }
  // Ribs: a ring that stands in to the radius the claws plant on.
  let alongBay = abs(z - (bay + 0.5) * RIB);
  let rib = 1.0 - smoothstep(0.08, 0.17, alongBay);
  if (rib > 0.0) {
    radius = min(radius, mix(radius, bore - 0.12, rib * ctx.params.relief));
    what = mix(what, 1.0, step(0.5, rib));
  }
  // The deck: nothing hangs below it.
  let floorAt = ctx.params.bore * ctx.params.deck;
  if (sin(theta) < 0.0 && radius * -sin(theta) > floorAt) {
    radius = floorAt / -sin(theta);
    what = 3.0;
  }
  q.position = wall.origin + radial * radius;
  q.tint = vec4f(what, panel, around, z);
  return q;
}`;
